### ISSUE TITLE
Networks: expand node to show relationships

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1002]
Use case: As a user drawing a VIS diagram, I want to be able to double-click an entity and expand it to see all of the connections it has in the collection backend but that may not yet be shown in the diagram. 

Problems:
a. Entities can have many (thousands) links, so we may need a pre-filter dialog
b. We need to make an API that returns links, but links aren't really a thing in Aleph's data model
c. Theoretically, we could even support property-value based expansions.

As an attempt to deal with b., I added a graph backend to FtM over Christmas: `followthemoney.graph:Graph`. This could be sub-classed by Aleph to implement entity and adjacency retrieval from ElasticSearch, possibly with a generous dose of redis caching in the middle. 

We should go about designing this by getting a good understanding of our desired user experience, and then making a modest API to serve it. Otherwise this is gonna be full GraphQL support quick :)

**Comment by sunu** [comment]
Here's my initial thought on this:

To make graph expansion manageable and useful in the interface, I think we have to cap the number of nodes we present on expansion. I don't know what is good number for maximum nodes to expand - 20 or so at a time may be? We can indicate that there are more matches with a placeholder node marked as "and 100 more" and then we paginate the expansion process.

For a., I feel a good pre-filter criteria for the first iteration would be filtering by edge type. So if we have a company A, we can expand to show all its directors or show all Sanctions on it or show all its owners etc.

The api call will look something like: `/api/2/<ent_id>/expand?schema:Ownership&property:owner` And I think we can use the same structure to request expansion based on property value. For example, `/api/2/<ent_id>/expand?schema:LegalEntity&property:email` to expand based on email. We can differentiate between the 2 types of request based on whether schema is a `Thing` or an `Interest`.

The response can be a serialized Graph object based on `followthemoney.graph:Graph` and the page number, excluded result count etc. WDYT?

**Comment by pudo** [comment]
I think we have to be careful distinguish two different edge sources: forward and backward. Backward edges are the ones the reference API will find: a remote entity that makes mention of the entity we are attempting to expand. But there's also the inverse: a mention of a remote entity within the properties of the current entity.

For example, a `Sanction` is a node entity that has a property called `entity` that references a `LegalEntity`. So when generating the adjacency of the `Sanction`, we need the `LegalEntity` to be included. Same with the upcoming `Event`: it s a node and points to a set of `involvedEntities` which are the `Things` that are participants to the event.

I'm actually wondering if we can break this down to faceting only by property, by using the inverse stub properties defined in the FtM model. You use `Ownership:owner` as an example, but that has an inverse, `LegalEntity:ownershipOwner`, which might be the more precise filter to use here. This way the target is always defined in terms of the properties of the source entity, not the properties of the target or edge entity...

**Comment by sunu** [comment]
Putting down my notes from yesterday's chat here.

We have decided to create 2 endpoints:
1. `exapand/stats/` - which returns counts of nodes generated by the expansion for each property and inverse property. If the total is more than 150 or so, we force the user to drill down in the UI.
2. `expand` - which optionally takes filters like `filter:property=ownershipOwner` where `property` can be both a direct property or an inverse property.

Inverse properties are not directly indexed in ElasticSearch. So we'll have to compute the ElasticSearch query for inverse properties (marked as `stub=True`) by looking up the Schema for the property's range.

**Comment by pudo** [comment]
Resolved in 3.8.1
