### ISSUE TITLE
Refresh my personal API key

### ISSUE THREAD

**Issue by zufanka** [alephdata/aleph#1027]
I did not keep my API key very private (posted it on Slack by accident, not a super breach but still). I'd like an option to "refresh" my API key, meaninig create a new one while the old one would hence become invalid.

Possible front end implementation:
![image](https://user-images.githubusercontent.com/2411066/75261728-c9099180-57eb-11ea-8bb8-ed254c2d01aa.png)

Clicking on the refresh button would prompt a warning "Are you sure you want to reset your API key?"

**Comment by PastNullInfinity** [comment]
As far as I can tell, the way that Aleph is handling changes to the users' data is by sending a `POST`  towards the `api/2/roles/user_id` , which does not make much sense in the context of asking the backend to regen an API token, I'm going forward in creating a new endpoint for the user, something like `api/2/roles/user_id/reset_api`, that simply overrides the current api_key field (on the UI side there will need to be some kind of modal for warning and a refresh of the users data, I'm not much of a React developer but I can give it a shot)

**Comment by pudo** [comment]
This makes perfect sense as an approach, I agree on not "beating" it into REST.

**Comment by pudo** [comment]
Any luck, @PastNullInfinity ?

**Comment by PastNullInfinity** [comment]
Work got the best of me : ) 
I have a branch ready, I'll try to open it in the next couple of days @pudo

**Comment by AZhyrenkov** [comment]
@PastNullInfinity Hey there! So how did it end up?
Did you manage to make a PR of that thing?

**Comment by PastNullInfinity** [comment]
@AZhyrenkov Hey! I've definitely dropped the ball on this PR, honestly hadn't had time in the past years to give real time to this project, that's on me : / 
I'm planning on getting more time for contributions in the next month, I'll make an effort to push a PR for this soon
