### ISSUE TITLE
Invalid Excel as named entity

### ISSUE THREAD

**Issue by zufanka** [alephdata/aleph#1033]
* I found this named entity under "Names"

![image](https://user-images.githubusercontent.com/2411066/75569066-b219a800-5a54-11ea-8678-9b975f473996.png)

* this appears to be extracted from some excel (xls and xlsx) files that give this errors

![image](https://user-images.githubusercontent.com/2411066/75569045-a8904000-5a54-11ea-9dc3-cb11f514502b.png)
![image](https://user-images.githubusercontent.com/2411066/75569453-66b3c980-5a55-11ea-91e2-33e275e12985.png)

* When I downloaded some of them they also looked pretty weird

![image](https://user-images.githubusercontent.com/2411066/75569906-4f291080-5a56-11ea-987f-9b3aa1cb69da.png)

Also looked at them in the source data, they looks the same.
(ping me and I will tell you which data set it is)

Suggestion: not showing Invalid Excels on the front end.

**Comment by pudo** [comment]
Fixed in `followthemoney 1.27.1`.
