### ISSUE TITLE
Installation error - error processing tar file

### ISSUE THREAD

**Issue by bkjkb** [alephdata/aleph#1041]
Hi
I am getting the below error when running docker-compose up -d
 failed to register layer: Error processing tar file(exit status 1): write /usr/lib/python3/dist-packages/Cython/Utility/ExtensionTypes.c: no space left on device

I have tried to look all over on how to fix this error, but had no support.

My system
Ubuntu server 18.04
16GB / 500 GB

**Comment by pudo** [comment]
I think it's saying your hard drive is full. Maybe a little `docker system prune -f`?
