### ISSUE TITLE
No frontend with developer docker

### ISSUE THREAD

**Issue by belisards** [alephdata/aleph#1044]
I am trying to run the docker, however it seems to not activate the front-end. 

Here is the final part of the command `$ sudo make all`

`
Starting aleph_api_1 ... 
Starting aleph_api_1 ... done
Starting aleph_ui_1 ... 
Starting aleph_ui_1 ... done
Attaching to aleph_api_1, aleph_ui_1
api_1               |  * Environment: production
api_1               |    WARNING: This is a development server. Do not use it in a production deployment.
api_1               |    Use a production WSGI server instead.
api_1               |  * Debug mode: off
api_1               | [2020-03-12 01:56:26,018] INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
api_1               | [2020-03-12 01:56:26,022] INFO:werkzeug: * Restarting with stat
api_1               | [2020-03-12 01:56:28,240] WARNING:werkzeug: * Debugger is active!
api_1               | [2020-03-12 01:56:28,242] INFO:werkzeug: * Debugger PIN: 575-171-712
ui_1                | 
ui_1                | > aleph-ui@3.5.1 start /alephui
ui_1                | > node scripts/start.js
ui_1                | 
ui_1                | ℹ ｢wds｣: Project is running at http://172.21.0.8/
ui_1                | ℹ ｢wds｣: webpack output is served from /
ui_1                | ℹ ｢wds｣: Content not from webpack is served from /alephui/public
ui_1                | ℹ ｢wds｣: 404s will fallback to /index.html
ui_1                | Starting the development server...
ui_1                | 
ui_1                | Compiled with warnings.
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | Search for the keywords to learn more about each warning.
ui_1                | To ignore, add // eslint-disable-next-line to the line before.
ui_1                | 
api_1               | [2020-03-12 01:57:55,675] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 01:57:55] "GET /static/js/bundle.js HTTP/1.1" 404 -
api_1               | [2020-03-12 01:57:55,676] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 01:57:55] "GET /static/js/main.chunk.js HTTP/1.1" 404 -
api_1               | [2020-03-12 01:57:55,702] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 01:57:55] "GET /static/js/main.chunk.js HTTP/1.1" 404 -
api_1               | [2020-03-12 01:58:16,685] INFO:werkzeug:172.21.0.1 - - [12/Mar/2020 01:58:16] "GET / HTTP/1.1" 404 -

`
If try to access localhost:5000, I get this error: {"status": "error", "message": "This path does not exist."}

Any tip about it?

**Comment by pudo** [comment]
I think you may need to go to port 8000 instead :)

**Comment by belisards** [comment]
Thanks! I tried with the port 8080 but it does not work as well. I get just a blank page.

$ sudo make web
docker-compose -f docker-compose.dev.yml  up -d --remove-orphans \
	postgres elasticsearch ingest-file \
	convert-document
aleph_redis_1 is up-to-date
aleph_convert-document_1 is up-to-date
aleph_postgres_1 is up-to-date
aleph_elasticsearch_1 is up-to-date
aleph_ingest-file_1 is up-to-date
docker-compose -f docker-compose.dev.yml  up api ui
aleph_redis_1 is up-to-date
aleph_postgres_1 is up-to-date
aleph_elasticsearch_1 is up-to-date
aleph_convert-document_1 is up-to-date
aleph_ingest-file_1 is up-to-date
Starting aleph_api_1 ... 
Starting aleph_api_1 ... done
Starting aleph_ui_1 ... 
Starting aleph_ui_1 ... done
Attaching to aleph_api_1, aleph_ui_1
ui_1                | 
ui_1                | > aleph-ui@3.5.1 start /alephui
ui_1                | > node scripts/start.js
ui_1                | 
api_1               |  * Environment: production
api_1               |    WARNING: This is a development server. Do not use it in a production deployment.
api_1               |    Use a production WSGI server instead.
api_1               |  * Debug mode: off
api_1               | [2020-03-12 16:11:12,449] INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
api_1               | [2020-03-12 16:11:12,463] INFO:werkzeug: * Restarting with stat
api_1               | [2020-03-12 16:11:15,003] WARNING:werkzeug: * Debugger is active!
api_1               | [2020-03-12 16:11:15,126] INFO:werkzeug: * Debugger PIN: 575-171-712
ui_1                | ℹ ｢wds｣: Project is running at http://172.21.0.8/
ui_1                | ℹ ｢wds｣: webpack output is served from /
ui_1                | ℹ ｢wds｣: Content not from webpack is served from /alephui/public
ui_1                | ℹ ｢wds｣: 404s will fallback to /index.html
ui_1                | Starting the development server...
ui_1                | 
ui_1                | Compiled with warnings.
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | ./node_modules/pdfjs-dist/build/pdf.js
ui_1                | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
ui_1                | 
ui_1                | Search for the keywords to learn more about each warning.
ui_1                | To ignore, add // eslint-disable-next-line to the line before.
ui_1                | 
api_1               | [2020-03-12 16:13:22,233] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:22] "GET /static/js/main.chunk.js HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:22,233] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:22] "GET /static/js/bundle.js HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:22,247] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:22] "GET /static/js/main.chunk.js HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:22,600] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:22] "GET /favicon.ico HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:25,794] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:25] "GET /static/js/bundle.js HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:25,803] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:25] "GET /static/js/main.chunk.js HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:31,899] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:31] "GET /static/js/bundle.js HTTP/1.1" 404 -
api_1               | [2020-03-12 16:13:31,911] INFO:werkzeug:172.21.0.8 - - [12/Mar/2020 16:13:31] "GET /static/js/main.chunk.js HTTP/1.1" 404 -


~$ curl http://0.0.0.0:8080/
<!DOCTYPE html>
<html data-api-endpoint="/api/2">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div id="root"></div>
  <script src="/static/js/bundle.js"></script><script src="/static/js/main.chunk.js"></script></body>
</html>

**Comment by pudo** [comment]
When you say you get a blank page, what shows in the browser console? I think this may be an issue with `react-dev-utils` having released a new version, 3.6.0 will fix it.

**Comment by belisards** [comment]
Here is what I get in the browser console:
```

DevTools failed to parse SourceMap: chrome-extension://ekhagklcjbdpajgpjgmbionohlpdbjgc/browser-polyfill.js.map
0.0.0.0/:9 GET http://0.0.0.0:8080/static/js/bundle.js net::ERR_ABORTED 404 (NOT FOUND)
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension://nndknepjnldbdbepjfgmncbggmopgden/map/js/dm_content.js.map
DevTools failed to parse SourceMap: chrome-extension://nndknepjnldbdbepjfgmncbggmopgden/client/dist2/js/vendor.js.map
DevTools failed to parse SourceMap: chrome-extension://nndknepjnldbdbepjfgmncbggmopgden/client/dist2/js/dm_content_script.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map
DevTools failed to parse SourceMap: chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map
30.0.0.0/:9 GET http://0.0.0.0:8080/static/js/main.chunk.js net::ERR_ABORTED 404 (NOT FOUND)
DevTools failed to parse SourceMap: chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
```

**Comment by pudo** [comment]
Yes that looks like the `react-dev-utils` issue. Can you see if this issue continues to exist with `3.6.0` (just released) and re-open if it does?

**Comment by belisards** [comment]
Now it's working! Thanks.

I would just suggest to include the instructions about the `.env` file in the docs.

**Comment by pudo** [comment]
Which information about `.env` are you referring to? I think there's some mention of it here: “A single death is a tragedy; a million deaths is a statistic.”
