### ISSUE TITLE
Proposal: introduce mutable flag on entities

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1105]
Users are confused by the distinction between personal (mutable) datasets and (immutable) source datasets. It's confusing that you cannot create a quick diagram inside a source dataset, or run a wizard that turns the top mentioned person and company names across your documents into entities that you can cross-reference.

A possible fix to this could be to introduce a `mutable` flag on all entities, which would delineate the source material from the analytical stuff created by users as they analyze the information. This way people could place diagrams and other analysis in the same collection as the source information, but both could be cleanly delineated in the UI and all the manual stuff could be deleted if you want to restore the original state.

Simon also proposed an (alternative?) solutions of making nested datasets. In that scenario, you'd be able to place multiple personal datasets into a source dataset -- so you could have a dataset inside a dataset, and the nested one has your analysis...

(based on discussion with @simonwoerpel)

**Comment by simonwoerpel** [comment]
i'd like a `mutable` flag as a quick solution for further experiments. or, the distinction i see in such entities is more like "is it created in a reproducable way from an evidence source" (e.g. from a mapping) or "did it fall out from some custom user data wrangling" (aka a quick & dirty wizard from a user)

so, maybe a solution could be as well something like `evidence: 'source'` vs `evidence: 'user_generated'` ?

for long-term, i still like the idea of nested collections, but maybe this goes hand in hand with a general overthinking of collection vs. casefile  :slightly_smiling_face:

**Comment by simonwoerpel** [comment]
but okey, the `mutable` flag would do the same trick :point_up:

**Comment by pudo** [comment]
After some discussion with @mynameisfiber, the proposed rules are these:

* Stuff added as documents is always immutable
* Stuff added through diagrams, table editor is always mutable
* The bulk API and the mappings API take a flag, available only to platform admins.
