### ISSUE TITLE
Slashes in search query lead to error

### ISSUE THREAD

**Issue by phdowling** [alephdata/aleph#1118]
Searching e.g. "Company a/b" in the web interface or API leads to a crash:
```bash
 curl 'https://aleph.occrp.org/api/2/entities?filter%3Aschemata=Thing&highlight=true&limit=30&q=company%20a%2Fb' -H 'authority: aleph.occrp.org' -H 'accept: application/json, text/plain, */*'
```
```json
{"status": "error", "message": "token_mgr_error: Lexical error at line 1, column 12.  Encountered: <EOF> after : \"/b\""}
```

There might be other special chars that are not handled, this is one I came across today.

**Comment by pudo** [comment]
You've basically angered the ElasticSearch gods, not the Aleph gods. We're sending the query into ElasticSearch as a `query_string` and that interprets this as an unbalanced regex. We can mitigate this either a) by making ES errors less visible (e.g. `lenient: True` [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)), or b) by trying to pre-parse the query .. I'm not sure I want to get into that, to be honest. Do you think it'd be better if the error was just not shown, and the `a/b` part discarded?

**Comment by pudo** [comment]
btw If you're trying to look up companies, it might be better to use the [`/match` API](https://redocly.github.io/redoc/?url=https://aleph.occrp.org/api/openapi.json#tag/Entity/paths/~1api~12~1match/post) anyway - that does more precise queries.

**Comment by phdowling** [comment]
I think it might just be a matter of escaping certain chars, or of using a different analyzer.
Here's a SO thread on the issue: https://stackoverflow.com/questions/31963643/escaping-forward-slashes-in-elasticsearch 

Regarding /match: is that what's used to find "similar" entities in the web interface? It always needs a reference entity, not just a search string, correct?

**Comment by pudo** [comment]
No, the `/match` API lets you submit a sort of stub FtM entity (doesn't need to have an ID, or exist in the database -- it's basically just a way to say "match name X in the name field, birthday Y in the birthday field".

Regarding the original question -- I've done a bit more research and we're already using `query_string` in lenient mode where it tries to correctly handle malformed inputs. Short of building a query string parser into Aleph and randomly hacking up the syntax, there's very little we can actually do to fix this. Applying random regex to this is bound to backfire, so I'm a massive -1 on that.
