### ISSUE TITLE
ui_1 Failed to compile.

### ISSUE THREAD

**Issue by jmapdt** [alephdata/aleph#1155]
Hi, 

When trying to do a make all, I get a failed to compile regarding node js module for the ui component:

ui_1                | Starting the development server...
ui_1                |
api_1               | [2020-05-07 18:26:23,009] WARNING:werkzeug: * Debugger is active!
api_1               | [2020-05-07 18:26:23,010] INFO:werkzeug: * Debugger PIN: 208-658-879
ui_1                | Failed to compile.
ui_1                |
ui_1                | ./node_modules/@blueprintjs/core/lib/esnext/components/forms/numericInput.js 60:31
ui_1                | Module parse failed: Unexpected token (60:31)
ui_1                | File was processed with these loaders:
ui_1                |  * ./node_modules/babel-loader/lib/index.js
ui_1                | You may need an additional loader to handle the result of these loaders.
ui_1                | |       const delta = this.updateDelta(direction, e);
ui_1                | |       const nextValue = this.incrementValue(delta);
ui_1                | >       this.props.onButtonClick?.(+nextValue, nextValue);
ui_1                | |     };

**Comment by pudo** [comment]
I've seen this before (cf. https://github.com/palantir/blueprint/issues/4112) but didn't realise it affected our production versions. Which version are you running against?

**Comment by jmapdt** [comment]
thats some quick follow-up :) thanks. I git cloned,

commit b580a455c01539f9a472636cd159d7db25518ec4 (HEAD -> master, tag: 3.7.1, origin/master, origin/HEAD)
Author: Friedrich Lindenberg <friedrich@pudo.org>
Date:   Thu Apr 30 09:27:37 2020 +0200

    Bump version: 3.7.0 → 3.7.1

I m not super versed in nodejs :)

**Comment by pudo** [comment]
> I m not super versed in nodejs :)

![unnamed](https://user-images.githubusercontent.com/41628/81565771-31532280-939a-11ea-9f03-32435072568f.jpg)

So the current work-around is pinning `"@blueprintjs/core": "3.18.1",` in `ui/package.json`.

**Comment by jmapdt** [comment]
awesome. Thank you :)
