### ISSUE TITLE
convert-document - failed to read path from javadlx

### ISSUE THREAD

**Issue by jmapdt** [alephdata/aleph#1159]
When trying to index files, it is stuck at 67%. I had this with both docker-compose dev and prod.. 

convert-document_1  | [2020-05-13 21:20:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
convert-document_1  | [2020-05-13 21:20:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:3000 (1)
convert-document_1  | [2020-05-13 21:20:08 +0000] [1] [INFO] Using worker: threads
convert-document_1  | [2020-05-13 21:20:08 +0000] [9] [INFO] Booting worker with pid: 9
convert-document_1  | INFO:convert.converter:Starting headless LibreOffice...
convert-document_1  | javaldx failed!
convert-document_1  | Warning: failed to read path from javaldx
convert-document_1  | LibreOffice 6.3 - Fatal Error: The application cannot be started.
convert-document_1  | User installation could not be completed.

Based on other forums posts, it looks like it could be due to /home/app/.config not being owned by  app user? unless I messed up something on my site config-wise :|

thanks

**Comment by pudo** [comment]
Yeah, I've seen this reported intermittently, and it's probably related to what user the docker container is running as. Can you maybe have a play with the relevant section of the docker-config file and report back? 

https://github.com/alephdata/aleph/blob/master/docker-compose.yml#L29-L34

**Comment by jmapdt** [comment]
works. Somehow I didnt have those permissions, sorry.
