### ISSUE TITLE
csv export for deeplearning related tasks

### ISSUE THREAD

**Issue by x0rzkov** [alephdata/aleph#1195]
Hi guys,

Hope you are all well !

Something related to my previous issue, I wanted to know how is it possible to export all indexed pdfs from a dataset into a csv file that I can use for nlp/deep learning tasks.

Does it requires custom coding to build such export ? 
Is there a wizard exporter available ? 

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by simonwoerpel** [comment]
you can export the documents and their extracted text via the [alephclient command-line utility](https://docs.alephdata.org/developers/alephclient).

`alephclient stream-entities -f <foreign_id> -s Document > data.jsonl`

this will export all documents as ftm entities, you will have 1 entity per page (1 json object per line), so you might need to wrangle it a bit afterwards depending on your needs...

**Comment by lucmichalski** [comment]
Thanks for your reply, awesome...

I ll give a try today

**Comment by pudo** [comment]
If you install `followthemoney` on the client, you can also do: 

```
alephclient stream-entities -f <foreign_id> | ftm export-csv -o some_folder
```

This will generate a file for each schema type with each returned entity.
