### ISSUE TITLE
how to customise the home page ?

### ISSUE THREAD

**Issue by x0rzkov** [alephdata/aleph#1196]
Hi guys,

Hope you are all well !

Quick question about how to customise the home page as I would like to have looking like yours (dixit this screenshot)

<img width="1241" alt="Screenshot 2019-09-03 at 08 57 04" src="https://user-images.githubusercontent.com/56916043/83961775-bbf24900-a896-11ea-9519-1897e068bec6.png">

Thanks for any inputs or insights on that

Cheers,
X

**Comment by simonwoerpel** [comment]
There is no customizing. This is the default homepage for non-authenticated users. The items in the top bar ("Profile") seem a bit outdated in this screenshot. If you are not logged in, the homepage looks like this: https://aleph.occrp.org/

**Comment by sunu** [comment]
You can set `ALEPH_APP_TITLE`, `ALEPH_APP_DESCRIPTION` and `ALPEH_LOGO` in the settings. I think that's all the customization we do for our homepage.

**Comment by lucmichalski** [comment]
That s enough for now, I ll check that today

**Comment by pudo** [comment]
Assuming this is resolved.
