### ISSUE TITLE
how to increase the number of jobs/connection pool of processing tasks ?

### ISSUE THREAD

**Issue by x0rzkov** [alephdata/aleph#1197]
Hi,

Hope you are all well !

I was wondering if it is possible to increase the number of jobs while processing documents. I have a 240Go RAM and 16 cores CPU, and would like to use the full potential of my specs.

Thanks for any insights or inputs on that topic.

Cheers,
X

**Comment by x0rzkov** [comment]
I have the following error because the pool of socket in the request package is too low.

```bash
INFO:alephclient.crawldir:Upload [16->None]: b947ca541d24fdf1486a388b733218a4c92eb8a9.data.pdf
INFO:alephclient.crawldir:Upload [16->None]: bf80d91c8b942743ac296a950709f7be7ca205f5.json
INFO:alephclient.crawldir:Upload [16->None]: a5586fa73744f0239524541fe44e46ca15f028d1.json
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: XX.XXX.XX.XXX
```

Is it possible to increase it or to provide a value by a cli flag ?

Cheers,
X

**Comment by sunu** [comment]
To increase the number of concurrent jobs by executed by Aleph's workers, you can increase the number of worker containers you're running by using `docker-compose --scale` (https://docs.docker.com/compose/reference/scale/).

The connection pool issue in `alephclient` needs some changes in the code. Setting the pool's maxsize to the number of threads we use (`settings.THREADS`) should be a sensible default. Happy to accept a PR for that if you would like to make one :slightly_smiling_face:

**Comment by pudo** [comment]
To be super clear: this doesn't actually cause any problems. It's just Python `requests` realising it has created way more connections than it needs after all uploads are complete, and tearing them down.
