### ISSUE TITLE
Add a GDPR notice in the UI?

### ISSUE THREAD

**Issue by PastNullInfinity** [alephdata/aleph#1218]
I'd like to propose the addition of a generic GDPR compliant notice for what kind of data is stored/gathered with Aleph. 
I'm thinking about simply extending the Footer component, add a link there and a new route. I'm not a lawyer (or a React developer), but I'd be happy to contribute a PR for at least implementing the UI changes

**Comment by pudo** [comment]
Thanks for the suggestion! We're currently working on a way to present text pages on the app (#1216), and a Terms of Use document for the OCCRP instance is being lawyered. The question of GDPR compliance is very complex given that different EU MS have transposed Arts 85 & 86 of the regulation in vastly different ways (some, I think, not at all). OCCRP itself is a US entity, so we do not have a responsible DPA in Europe.

**Comment by pudo** [comment]
Finally have our legalese up on the site! Closing.
