### ISSUE TITLE
Mini-issues in UI 3.8.3

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1231]
* [ ] In the notifications list, icons and entity links are very oddly spaced
* [ ] Download button in entity preview pane has no icon padding
* [ ] The "add entity to diagram" dialog may need some visual polish. Perhaps the buttons want to live side by side? Or is this really a menu popping out of the button? (With auto-load, like in the expand menu)

**Comment by pudo** [comment]
What could work, maybe even with a little "New" button as an input group?

**Comment by kjacks** [comment]
<img width="369" alt="Screen Shot 2020-06-25 at 14 00 01" src="https://user-images.githubusercontent.com/6720200/85715886-3242d800-b6ec-11ea-89b8-a10c82d23941.png">

I wasn't able to re-create the issue with the entity preview Download button padding

**Comment by pudo** [comment]
Oh, sorry this is only in RTL probably

**Comment by kjacks** [comment]
Ahh got it got it :)
