### ISSUE TITLE
Node value type selector

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1253]
In the diagrams editor (yea this is a react-ftm ticket but I'm filing here to keep things together), I would like to be able to select which property type values should be turned into diagram nodes implicitly. By default, it might even make sense at this point to do `entity` only. Here's what browsing some email looks like at the moment:

<img width="1181" alt="Screenshot 2020-07-03 at 15 24 24" src="https://user-images.githubusercontent.com/41628/86473622-89c2f280-bd41-11ea-99f2-e58167e41513.png">

**Comment by kjacks** [comment]
@pudo for aleph network diagrams, is a user's value node type configuration something that should be stored in the diagram json?  Or in a user's data or local storage or something else?

**Comment by pudo** [comment]
I'd put it in the layout, I think ... :)

**Comment by kjacks** [comment]
True true - sounds good!

**Comment by pudo** [comment]
Loooooking good. Very cryptic, but that's life.
