### ISSUE TITLE
Make edge labels ignore clicks

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1254]
This is a @pudo bug, I guess. I have this irresistible urge to single- and double-click edge labels. When I double-click the edge label the "new entity" dialog pops up. Maybe we could just catch & ignore that event on the edge label.

**Comment by kjacks** [comment]
So we need to have the single click event to bring up the editing ability for the edge in the EntityViewer.  But I can catch the double click event in order to prevent it from propagating.

**Comment by pudo** [comment]
Thanks @kjacks!
