### ISSUE TITLE
Introduce "List" entity set type

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1271]
As a user, I want to be able to (MVP):

* Add an entity in my personal dataset to a new or existing list inside that dataset
* View a list of entities in the table editor
* Create a new entity inside a list context

Later on we might want to: 

* Add an entity from a search result or an arbitrary collection to a list in a different personal dataset
* Convert a whole search result to a list in a personal dataset
* View a list that contains entities I may not be able to write, or that I may not even be allowed to see
* Create a grouping in a diagram that becomes a sub-list of the diagram automatically

**Comment by kjacks** [comment]
Little things I would maybe add:

MVP:
- Search within a list (presumably we get this for free, but just to be sure)
- Export a list as a csv?

Later:
- Create a list directly from a mapping? when mapping tabular data into structured entities
- Perform set operations on a list? (i.e. add/delete a property value of all members of a list)
- Would sub-lists be allowed in a default list?
- Convert a list into its own personal dataset? (not really sure the use-case here, and probably has some weird data duplication issues too...)

**Comment by pudo** [comment]
Oooh yes the export stuff seems essential! 

I love all the suggested expansions here, especially the set operations - I feel a whole line of work could be buried there. Is every xref a list operation? Can also use this to browse, e.g. to expand out on a property type? 

One thing we may have to decide relatively soon is how large we want entitysets to be able to be. If we make them small (all the entities are returned in a response like now), then the mapping thing may work. But if they're just flags like collection_id, then we could automatically make each mapping output into a list....
