### ISSUE TITLE
Make IngestWorker pipeline more flexible

### ISSUE THREAD

**Issue by malteos** [alephdata/aleph#1312]
Hi @pudo et al.,

as you know I'm working on adding more processing steps to the ingest worker (translation, topic detection, ...). To make the integration of additional processing easier and to minimize the changes in the original code, it would be great to make the pipeline more flexible.

The aleph client has already the pipeline as a setting (see https://github.com/alephdata/aleph/blob/main/aleph/queues.py#L59). But the ingest worker has still fixed processing steps (see https://github.com/alephdata/aleph/blob/main/services/ingest-file/ingestors/worker.py#L40-L65).

What about refactoring the processing steps (OP_INGEST, OP_ANALYZE, ...) from string names to classpaths (e.g., `analyze` => `ingestors.tasks.AnalyzeStage`)? And then load the responding modules based on the classpath?

The goal should be that one could change the pipeline just by changing the environment variable:

```
ALEPH_INGEST_PIPELINE=ingestors.tasks.AnalyzeStage,maltes_extra_ingestors.tasks.TranslateStage,pudos_ingestors.AnotherStage
```

What do you think about this? If this doesn't sound too bad I could start with a PR.

Best,
Malte

**Comment by pudo** [comment]
Did you check out https://docs.alephdata.org/developers/adding-text-processors ?

**Comment by malteos** [comment]
I wasn't aware of this one ;)

**Comment by malteos** [comment]
How can I add multiple processors? Comma-separated?

```
ALEPH_INGEST_PIPELINE=analyze:translate,analyze:foo
```

**Comment by pudo** [comment]
No, colon:

``ALEPH_INGEST_PIPELINE=analyze:translate:foo``
