### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by pauleil** [alephdata/aleph#1313]
Trying to export data for a sizable dataset (but <10k entries) fails w/a 502. 
To replicate: try to export 2,898 emails from [this Kremlin dataset](https://aleph.occrp.org/search?filter%3Acollection_id=1614&filter%3Aschema=Email).

After 10-20 min the download starts, and fails with a Network error (usually after downloading 1-4mb).

**Comment by pudo** [comment]
Yep, we're working on building a better bulk export system. cf. #1282.
