### ISSUE TITLE
Cannot register new user

### ISSUE THREAD

**Issue by EnterpriseT** [alephdata/aleph#1337]
Setup:  access through ssh tunnel to Debian 9 with fresh Aleph install.
Trying to register new user, but no email sent

Following error:
`Aleph (http://localhost:8080/)
api_1               | [2020-08-30 23:14:06,440] ERROR:aleph.logic.mail:Error sending email [<Role(None,None)>]: please run connect() first`

Any ideas?

**Comment by EnterpriseT** [comment]
my fault: incorrectly fill this section in aleph.env
`# Provide a valid email to send alerts from:
ALEPH_MAIL_FROM=
ALEPH_MAIL_HOST=
ALEPH_MAIL_ADMIN=
ALEPH_MAIL_USERNAME=
ALEPH_MAIL_PASSWORD=
ALEPH_MAIL_PORT=25
ALEPH_MAIL_USE_TLS=false`

but after that, again:
` Module not found: Can't resolve '@formatjs/intl-utils' in '/alephui/src/components/Notification'`
[https://github.com/alephdata/aleph/issues/1338](already mention here)

**Comment by EnterpriseT** [comment]
in docker's logs found out error message: `"KA" is too short` (KA - it's just a login name). But with longer login, other message: `Email is already registered`.

Here two suggestions: make error messages bit more detailed. The second one put the link to solving user issues (through keycloak - etc.)

**Comment by pudo** [comment]
PR very welcome for a better error message.
