### ISSUE TITLE
Error occurs: Can't resolve '@formatjs/intl-utils' 

### ISSUE THREAD

**Issue by EnterpriseT** [alephdata/aleph#1338]
Setup: Debian 9, access through ssh tunnel as localhost:8080
During browsing various pages error: **(in Dev mode)**

` ./src/components/Notification/Notification.jsx
ui_1                | Module not found: Can't resolve '@formatjs/intl-utils' in '/alephui/src/components/Notification'
ui_1                | Compiling...
ui_1                | Failed to compile.
`

**Comment by raziel130889** [comment]
I have the similar problem

**Comment by EnterpriseT** [comment]
I have installed **npm** and `intl-utils`: on some pages it disappears, but, the error apperas during approval of new user with link from email.
`npm i @formatjs/intl-utils`

**Comment by pudo** [comment]
Can you pull the latest version and make sure to run `make build`?

**Comment by EnterpriseT** [comment]
Thank very much. The error went away!
