### ISSUE TITLE
Web UI won't start 

### ISSUE THREAD

**Issue by jigsawsecurity** [alephdata/aleph#1350]
Have you guys seen this before?

ui_1                | Error from chokidar (/alephui/node_modules/jest-snapshot/node_modules/.bin): Error: ENOSPC: System limit for number of file watchers reached, watch '/alephui/node_modules/jest-snapshot/node_modules/.bin'

**Comment by pudo** [comment]
Can't reproduce on my system. Can you share once you find steps to fix?

**Comment by jigsawsecurity** [comment]
Was a result of a failed upgrade. Once I reran the upgrade it resolved the issue and the ui then started.
