### ISSUE TITLE
Export fail: Network file (.VIS) from Server (Production ver) to Aleph Desktop

### ISSUE THREAD

**Issue by EnterpriseT** [alephdata/aleph#1363]
1) Exported network file (.vis) from Server (Production)
2) Check file in Notepad++, file contains all data (nodes, companies etc)
3) Open it in Desktop (windows 10) - Blank screen

Also tried: creation file on Desktop, then import into Server. then Export, but not luck: same blank area: no any node.

**Comment by pudo** [comment]
@kjacks Mind having a look at this?

**Comment by kjacks** [comment]
@pudo yep - will take a look :)

**Comment by kjacks** [comment]
@EnterpriseT We just published a new release of Aleph Data Desktop (downloadable [here](https://github.com/alephdata/datadesktop/releases/) that hopefully resovles the issue you were facing. When testing, importing and exporting files from Aleph production seems to be working alright on the Mac version. I haven't been able to test the Windows version, so if you give it a try, that would be very helpful :)

**Comment by EnterpriseT** [comment]
Tested on Windows 10: import\export from Production server - **works!**
Thank you!
