### ISSUE TITLE
Show transliterated names in UI

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1371]
We want to be able to show latin transliterations of names and addresses in other languages in the user interface next to the original alphabet. 

When serving an entity, the API should include the transliterated string fragments.

**Comment by EnterpriseT** [comment]
This will be very useful! To automatically add new property: "transliteration".
And maybe for the network diagram has switch button (or icon on toolbar): transliteration ON/OFF: diagram change all names according to that button.
