### ISSUE TITLE
HTTP 413 Error

### ISSUE THREAD

**Issue by aaronsdevera** [alephdata/aleph#1396]
Getting an error when attempting to upload via webapp or API. Doesn't make too much sense, as prior instances of Aleph I have run handled much larger files...

<img width="535" alt="Screen Shot 2020-10-11 at 11 25 15 PM" src="https://user-images.githubusercontent.com/5042762/95701987-06a31980-0c19-11eb-8665-27b565d4b5d7.png">

<img width="459" alt="Screen Shot 2020-10-11 at 11 24 46 PM" src="https://user-images.githubusercontent.com/5042762/95701965-f723d080-0c18-11eb-835d-8934dbb358b2.png">

```
<html>

<head>
	<title>413 Request Entity Too Large</title>
</head>

<body bgcolor="white">
	<center>
		<h1>413 Request Entity Too Large</h1>
	</center>
	<hr>
	<center>nginx/1.14.1</center>
</body>

</html>
```

**Comment by pudo** [comment]
It looks like nginx is refusing to accept the file because of a file size upload limit. There's much documentation available on this, see e.g. https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size 

(see also: https://github.com/alephdata/aleph/blob/main/SUPPORT.md)

**Comment by aaronsdevera** [comment]
OK, but where am I supposed to apply the fix? I have never seen this error before from Aleph.
would it be in the host's `/etc/nginx/nginx.conf`?

**Comment by pudo** [comment]
If your host machine provides a reverse proxy in front of the aleph system (probably a good idea), yes. The other nginx, which is used to serve the UI in production mode, already has a limit of 2TB set: https://github.com/alephdata/aleph/blob/main/ui/nginx.conf

**Comment by pudo** [comment]
Assuming this is resolved.
