### ISSUE TITLE
Azure OAuth Fails with Mismatched State Error

### ISSUE THREAD

**Issue by mudsill** [alephdata/aleph#1403]
Following the configuration provided on alephdata.org

`ALEPH_OAUTH_NAME=Azure
ALEPH_OAUTH_BASE_URL=https://login.microsoftonline.com/organizations/oauth2/v2.0/
ALEPH_OAUTH_AUTHORIZE_URL=https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
ALEPH_OAUTH_TOKEN_URL=https://login.microsoftonline.com/common/oauth2/token
ALEPH_OAUTH_SCOPE=openid profile email user.read
ALEPH_OAUTH_TOKEN_METHOD=POST
`

produces a 401 error. However, I can see clearly in Azure AD that the request was approved. Digging into the logs (removing my client_id), I see:

`Saving authorize data: {'redirect_uri': 'http://localhost:8080/api/2/sessions/callback', 'nonce': '75Mmj7lfViE7vMwb6cN0', 'url': 'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?response_type=code&client_id=xxx&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fapi%2F2%2Fsessions%2Fcallback&scope=openid+profile+email+user.read&state=%2F&nonce=75Mmj7lfViE7vMwb6cN0', 'state': '/'}
`

followed by
`
WARNING:aleph.views.sessions_api:Failed OAuth: <MismatchingStateError "mismatching_state">
`

and

`
"GET /api/2/sessions/callback?code=xxx&state=%2f&session_state=xxx HTTP/1.1" 401 144
`

It seems that setting state to `%2F` is the culprit--not sure why this is happening? Tested with Google and same result.

**Comment by pudo** [comment]
We don't have an Azure endpoint to test against, so I'd really appreciate a PR to fix this.

**Comment by mudsill** [comment]
Will give it a shot.

**Comment by mudsill** [comment]
So, having looked into it, the problem seems to be Flask sessions not persisting between requests. State comparison is performed by `BaseApp._retrieve_oauth2_access_token_params` in `authlib/integrations/base_client/base_app.py`:

`
request_state = params.pop('state', None)
state = self.framework.get_session_data(request, 'state')
if state != request_state:
            raise MismatchingStateError()
`

`framework.get_session_data()` accesses the Flask `session` object.

I don't think this is a configuration issue—at least, I can't identify one that's present both on my local environment and on the Azure cluster. They're production environments and secret keys are set etc. Any thoughts?

The `handle_azure_oauth` method in `aleph/oauth.py` is also using an out-of-date syntax for `authlib`'s `jwt.decode`, and I have a branch fixing that.

**Comment by pudo** [comment]
So, Flask `session` may not really work because we're not using cookies. I was hoping it'd be possible to configure authlib to use redis instead: https://docs.authlib.org/en/latest/client/flask.html#using-cache-for-temporary-credential - but that probably still needs us to tell how to identify the client....

**Comment by mudsill** [comment]
So the difficulty is that `authlib` is using Flask session explicitly in `flask_client.integration.set_session_data`:

```
from flask import current_app, session
...
    def set_session_data(self, request, key, value):
        sess_key = '_{}_authlib_{}_'.format(self.name, key)
        session[sess_key] = value
```

It only uses the cache for request tokens. We could use `Flask-Session` to store the session on redis, though.

**Comment by mudsill** [comment]
Referring here for CORS/session tracking: https://stackoverflow.com/questions/52733540/flask-session-dont-persist-data. Don't know if this solution raises any further issues?

**Comment by mudsill** [comment]
If cookies are to be avoided at all costs, the only thing I can think of is retrieving and saving the session data set by `authlib` manually in `/api/2/sessions/oauth`, and then retrieving and resetting it in `/api/2/sessions/callback` before `authorize_access_token()` is called. Seems pretty hacky, though.

**Comment by pudo** [comment]
We now support Flask sessions in `develop` (and the next version of Aleph) again, to make authlib happy. Would be great if you could check if that fixes Azure support.

**Comment by mudsill** [comment]
Working on my end.

**Comment by pudo** [comment]
thanks for testing
