### ISSUE TITLE
My index progress stuck in %67

### ISSUE THREAD

**Issue by ByUnal** [alephdata/aleph#1425]
![image](https://user-images.githubusercontent.com/43930582/97287040-29f2d900-1855-11eb-839b-957691d72f9c.png)

How can I get through this ? I did
```
aleph update
aleph reindex
```
But It did not work.

**Comment by pudo** [comment]
https://docs.alephdata.org/developers/technical-faq#my-import-is-stuck-at-67-whats-wrong

**Comment by ByUnal** [comment]
Thanks, fixed.
