### ISSUE TITLE
Remove EntitySetItems/Entities from EntitySetSerializer

### ISSUE THREAD

**Issue by mynameisfiber** [alephdata/aleph#1428]
Even if a user has read access to an `EntitySet`, they may not have read access to all of the `EntitySetItem`s within that set. In order to mitigate the chances for this leak, we are removing the embedding of `EntitySetItem`s or `Entity`s  within the output of `EntitySetSerializer` in order to force the user to get that data through `GET /entityset/XXX/items` or `GET /entityset/XXX/entities`. Those endpoint will properly filter their output given the calling user's role.

This PR depends on changes to diagrams so that they don't depend on this embedding. @kjacks can you ping this issue when you think we're ready to switch over?

**Comment by pudo** [comment]
Done in 3.9.5.
