### ISSUE TITLE
Adding datasets in Public

### ISSUE THREAD

**Issue by ByUnal** [alephdata/aleph#1435]
How can add my datasets to be shown here ?
![image](https://user-images.githubusercontent.com/43930582/97719522-3aff4c80-1ad8-11eb-8bdf-3f676648bf2e.png)

**Comment by pudo** [comment]
Just added this to the FAQ yesterday: https://docs.alephdata.org/guide/frequently-asked-questions#how-can-i-make-a-dataset-public

**Comment by ByUnal** [comment]
Thank you, I managed.
Fixed.
