### ISSUE TITLE
entity recognition inconsistent or depends on MIME Type

### ISSUE THREAD

**Issue by colonyshipforsale** [alephdata/aleph#1436]
I tested entity recognition and country mapping after experiencing inconsistent results after an upgrade. 

Now using 3.9.4 with docker-compose. Testresults and comments below:

### while using the same picture, the entity recognition for a .png file failed to parse 4 entities compared to a .jpeg file

<img width="1296" alt="NER_MIME_INCONSISTENCE_I" src="https://user-images.githubusercontent.com/73785468/97806286-38793000-1c5b-11eb-8cf2-ecec892f8082.png">

- https://user-images.githubusercontent.com/73785468/97806350-8a21ba80-1c5b-11eb-969f-f15ddc252b1d.jpeg
- https://user-images.githubusercontent.com/73785468/97806357-8e4dd800-1c5b-11eb-8f38-88c0cca9ba9e.png

- the picture size differs, but is this difference causing this issue? Quality wise the 2 formats look good enough for OCR ..?
- shall I reformat png files to jpeg, since it provides more matches? Basically .jpeg is recommended?

### country entities are not parsed at all or parsed as a name entity

<img width="1259" alt="II After web based import" src="https://user-images.githubusercontent.com/73785468/97805392-17faa700-1c56-11eb-9921-f311826fbf9d.png">

- i created a few .txt files with country names and made screenshot as .png, .jpeg
- NER recognized "united states of america" as person and failed to recognize "sweden" and "netherlands" at all

netherlands
- https://user-images.githubusercontent.com/73785468/97807053-edf9b280-1c5e-11eb-8f03-fbe2dadde78c.jpg
- https://user-images.githubusercontent.com/73785468/97807056-f0f4a300-1c5e-11eb-8bab-139fae54d3da.png
- https://github.com/alephdata/aleph/files/5471183/netherlands.txt

sweden
- https://user-images.githubusercontent.com/73785468/97807080-1b466080-1c5f-11eb-9c72-62cc6bf939fe.jpg
- https://user-images.githubusercontent.com/73785468/97807082-1e415100-1c5f-11eb-986d-b83ba280ea90.png
- https://github.com/alephdata/aleph/files/5471188/sweden.txt

united states of america
- https://user-images.githubusercontent.com/73785468/97807105-403ad380-1c5f-11eb-83cd-1ef7887e3362.jpg
- https://user-images.githubusercontent.com/73785468/97807107-4335c400-1c5f-11eb-8a3d-bef307bee815.png
- https://github.com/alephdata/aleph/files/5471192/united.states.of.america.txt

### summary
Not sure if it is ok to raise this issue here since it is mostly concerning OCR quality? The previous aleph versions seemed to work better in this regard? Let me know if i can provide anything else and appreciate the efforts you put into this! 

kr

**Comment by pudo** [comment]
Some of this is beyond our control: the issue with JPEG and PNG probably relates very specifically to how Tesseract 4.x performs extraction - it may be worthwhile to raise a ticket on their bug tracker with the two comparison files. Of course some degradation from compression is to be expected, I'm not a good judge of whether this is indicative of a defect beyond that. 

Regarding NER, the decision of what is detected as a person/company or location is made by [spaCy](https://github.com/explosion/spaCy), we also depend on this - and don't really have the resource to train our own models with a better outcome than what explosion.ai does. Their project is very fast-moving, though - we've also noted the odd regression.

**Comment by colonyshipforsale** [comment]
Thanks for the tesseract hint i will retest with a few changes done to the pictures. I will post if i find methods that improve results.

I see your point regarding NER with Text files, i think spaCy failing to recognize a country in the above text file or even labelling it as a name is actually quite a bad? 

I would close the issue though as it is outside the alpeh scope?

**Comment by pudo** [comment]
Yeah I might close it - obviously it's desirable for these things to work better, but I cannot think of concrete measures to take with regards to how we integrate spaCy and tesseract that would improve things. Maybe we need to be relaxed about the world and hope for cool updates on both tools in the future.
