### ISSUE TITLE
make upgrade gives me same Error all the time

### ISSUE THREAD

**Issue by ByUnal** [alephdata/aleph#1438]
when I restart the Aleph search, I'm doing
`make build `(It works successfully), then
`make upgrade`
I'm confronting this error all the time. I checked logs file in elasticsearch container, I saw nothing there. Is there anyone can help ?
![image](https://user-images.githubusercontent.com/43930582/97867366-c4a05b80-1d1e-11eb-9376-705314cbf730.png)

Even with this error, `make web` and `make worker` work fine, and I can use aleph search properly.

**Comment by pudo** [comment]
It just means elasticsearch hasn't finished booting up when the upgrades are attempting to run. You can run `make services`, wait a little bit, then `make upgrade`....

**Comment by ByUnal** [comment]
Thanx. It worked. Fixed

**Comment by ByUnal** [comment]
It started give errors again like this. Elasticsearch is gone read-only mode,
I tried the solution here, twice
https://docs.alephdata.org/developers/technical-faq#elasticsearch-has-gone-into-read-only-mode-why

But It didn't work. What should I do ?

![image](https://user-images.githubusercontent.com/43930582/98514611-cb792200-227a-11eb-9947-8989ea99f3df.png)

**Comment by pudo** [comment]
Provide more disk space, or delete some data? This really isn't related to Aleph, so the ES forums might provide better help.
