### ISSUE TITLE
unable to add bulk imports to list / diagram

### ISSUE THREAD

**Issue by mouflon72** [alephdata/aleph#1445]
since the update to 3.9.4 (which fixed the imported mappings, thank you!) i can't select a destination list or diagram in the bulk import window any more. 

if i click a list or diagram in the sidebar, the sidebar just closes, but the selection does not show up any more under the "Select a List or Diagram" button.

**Comment by pudo** [comment]
I can't seem to reproduce this. Can you give some more detail or try with the latest version?

**Comment by mouflon72** [comment]
I am on the latest version (3.9.4). Only other hint I found (don't know if it's related at all), in the developer console I see:
`papaparse.min.js:7 GET http://localhost:8080/api/2/archive?token=(token redacted in case this matters) 401 (UNAUTHORIZED)`

**Comment by pudo** [comment]
Cannot reproduce, please reopen with more data on your deployment - it feels to me like it's an S3 issue, not linked to lists/diagrams.
