### ISSUE TITLE
After reindex still no entities found

### ISSUE THREAD

**Issue by haarts** [alephdata/aleph#1447]
This is a bit of a follow up from #1412. 

I've since updated my aleph install by doing a git pull and spinning up the docker containers again. 
I'm able to successfully complete the `aleph reindex-full` and related commands.
On the UI how ever I do see the two datasets I've imported and I can browse through them. Searching in the main search box yield no hits what so ever. 

Is there a way to inspect the indexes?

**Comment by haarts** [comment]
I've nuked all volumes and tried again. It works now, so I'll chalk it up to some messed up state.

**Comment by ByUnal** [comment]
What do you mean by that ?
I uploaded two different txt files. After I search anything in that files from search space, aleph returned nothing.
Also, It happened to me when I upload .json file. I couldn't reach the content by using search, and there was no shown entities
