### ISSUE TITLE
Fully split development and deployment config

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#146]
At the moment, we're getting a bunch of issues resulting from bugs related to the semi-docker development setup. This means it's virtually impossible to actually deploy Aleph, either in production or in development. Here's what I'd like to do:

* Make sure the deployment configuration is separate from the development configuration, and make sure it is very stable. A deployment install should be as simple as pulling a particular github tag, and running ``docker-compose up``. 
* Go back to recommending developers perform a docker-less install. The semi-docker route has proven itself brittle, and breaks the Makefile and various other settings for those who do have a native install.

What do you think, @stas?

**Comment by stas** [comment]
There was previously some related discussions in #130 about this.

I did a little bit of research on this topic, and Docker peeps suggest providing two separate compose files as the best practice (which kinda' makes sense).

What I am worried about though, is the `aleph-base` image that keeps growing and requires significant time to rebuild. It might be better if we keep maybe python apart from nodejs and have separate containers running one and the other. As for dev/prod, we already started splitting requirement files, and I think we could just leverage that to keep things prod-ready.

My experience so far with Docker is definitely not a :heart: story. But I try to imagine providing the cross-platform support for the installation procedures outside the Docker, and It gives me :cold_sweat:.

So I'd pick any solution that will take us as little time as possible and let us focus on our real tasks :)

**Comment by pudo** [comment]
@stas -- I've finally merged docker_settings and default_settings in the commit above. Would appreciate a sanity check.

I'm still a little torn regarding the best route forward on the developer setup. Have been using a native install on OS X for a while, and while getting the dependencies installed is a good chunk of work, the resulting install is really smooth, and I don't have to block off 4GB of memory for docker (memory allocation on the Mac is static). On the other hand, I see the appeal of just putting it all in a container and being done with it.

Regarding a separate Node.js container: excellent idea. Let's do it as we get into the new UI.

**Comment by stas** [comment]
@pudo is it possible we just get rid of the `default_settings` somehow?

`flask.config.get_namespace` somehow already does a part of the job. My biggest concern is that we no longer load the values from the `os.environ` directly. This means we need to copy environment directives for any flask plugin that might need some (my current use-case is related to `flask-simpleldap`).

**Comment by stas** [comment]
A note on something worth keeping in mind, the `aleph.datasets` is using a configuration directive `SCHEMA_YAML` that uses physical file(s) to load dataset mappings. The way it is right now, requires probably mounting a volume with the relevant files.

**Comment by stas** [comment]
@pudo could you review this changeset:
https://github.com/stas/aleph/compare/ldap...stas:one_config_file?expand=1

I pulled all the settings into one single file that can be fed to Docker.
There's a bit of pre-processing happening there by leveraging JSON.
Other than the breaking changes at the configuration level, this should get Aleph closer to be a 12factor app.
If you think this is a good direction, I'll prepare a PR and make sure the CI uses the new config too.

**Comment by pudo** [comment]
Hm. This is pretty desperate in terms of achieving 12 factor at any cost of ugliness. Piping JSON into object in as JSON via environment variables just doesn't strike me as making the world a better place. Mapping dictionaries into weirdly denormalised variable names doesn't either. It just beats sane design, and still doesn't get us all the way there (see the ``DATASETS_YAML`` issue).

The existing approach of overriding ``settings.py`` has been working perfectly well. Which real problem are we solving here? How many new ones are we creating in the process?

**Comment by stas** [comment]
@pudo, It is ugly, I take that. But you're being subjective here, please review the current challenges of maintaining the default_settings:
* it requires editing it to pass any new settings over to Aleph, this is frustrating (see Flask configuration settings, see Flask-SimpleLDAP configuration settings, see OAUTH)
* it is confusing, you have 2 files, one to feed to Docker one to feed to python to crunch the docker one?!
* it is not friendly to 12factor, so why are we pushing the Docker?
* finally, the codebase is 130 sloc lighter, less code means less maintenance and you'll never have to write a new line of python to deploy Aleph

So instead of having to deal with all above, I do prefer to write some ugly settings once and forget about it. Keep in mind, that this is an idea, we can throw it away or improve it.

I'm also not pushing for anything, but please be a bit more objective on the current challenges of having to deal with the deployments and maintenance of such a simple aspect which is _configuration of Aleph_.
