### ISSUE TITLE
swap NEP5 token

### ISSUE THREAD

**Issue by wasikatsi** [alephdata/aleph#1463]
under this function
it would be great to
build a swap function
for NEP5 aleph token
because the nep5 swapper
isnt functioning for
O3 wallets. thank you!

**Comment by wasikatsi** [comment]
i mean this link
https://swap.aleph.im/#/
isnt swapping

**Comment by pudo** [comment]
I think you're on the wrong repo. This is an anti-money laundering tool, you're looking for the opposite, I believe.

**Comment by wasikatsi** [comment]
perhaps you can forward this question to the right place? have no idea how to use this github tool
I want to SWAP my NEP5 aleph token into ERC20 aleph token and the link i mentioned is rubbish,
thanks a lot
