### ISSUE TITLE
Navigating directly to entity UI URL redirects to authentication page

### ISSUE THREAD

**Issue by CharlieJKendall** [alephdata/aleph#1465]
The migration to support OIDC appears to have prevented anonymous access to a large number of data via Aleph when navigating directly from a UI URL returned from the API. To reproduce:

**Request**
`GET https://aleph.occrp.org/api/2/entities/cc9b9e581c29e76969ee9470a25cfa78d3fad735.cdbf16c911fa234ce4d4bb31088c23887b459de3`

**Data Returned**
```
{
	"schema": "Person",
	"mutable": false,
	"properties": { ... },
	"score": 1.0,
	"shallow": false,
	"id": "cc9b9e581c29e76969ee9470a25cfa78d3fad735.cdbf16c911fa234ce4d4bb31088c23887b459de3",
	"writeable": false,
	"links": {
		"self": "https://aleph.occrp.org/api/2/entities/cc9b9e581c29e76969ee9470a25cfa78d3fad735.cdbf16c911fa234ce4d4bb31088c23887b459de3",
		"references": "https://aleph.occrp.org/api/2/entities/cc9b9e581c29e76969ee9470a25cfa78d3fad735.cdbf16c911fa234ce4d4bb31088c23887b459de3/references",
		"tags": "https://aleph.occrp.org/api/2/entities/cc9b9e581c29e76969ee9470a25cfa78d3fad735.cdbf16c911fa234ce4d4bb31088c23887b459de3/tags",
		"ui": "https://aleph.occrp.org/entities/cc9b9e581c29e76969ee9470a25cfa78d3fad735.cdbf16c911fa234ce4d4bb31088c23887b459de3"
	},
	"collection": { ... }
}
```

Navigate to the `ui` URL provided in the `links` node in a browser where no relevant cookies are present (I reproduced with a Chrome incognito window).

**Expected:** Displayed the Aleph UI page for the given entity in a browser.
**Actual:** Redirected to the authentication view.

**Comment by kjacks** [comment]
Fix coming: https://github.com/alephdata/aleph/pull/1459/commits/2457f56488360193f6f4f0a8605c11788381b53a

**Comment by pudo** [comment]
Fixed in prod.

**Comment by CharlieJKendall** [comment]
Looks good - thanks guys!
