### ISSUE TITLE
Table Editor - Target not selecting in link creation dialog

### ISSUE THREAD

**Issue by brrttwrks** [alephdata/aleph#1474]
- [ ] creating links fail when target is not in initial dropdown list

**Comment by kjacks** [comment]
From @brrttwrks : "I am adding entities in a list and creating links between them. When I select a target, and I have to search for it in the drop down in order to select it, the entity won't select. It will only select if the entity I select as a target is in the existing list in the drop down."

**Comment by pudo** [comment]
Fixed in 3.9.8 (not yet in OCCRP prod).
