### ISSUE TITLE
Can't delete entities in table editor

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1477]
When I select an entity in the table editor and then click the "delete" button there, the API receives a request to delete `/api/2/entities/undefined`.

**Comment by kjacks** [comment]
will be fixed by: https://github.com/alephdata/aleph/pull/1459/commits/25d06c817069ebf17dad4e0eacf9ce0367c496e1

**Comment by pudo** [comment]
Just to make sure: we're also using this in the document manager (and it works there) - fixing it for the table editor won't break the document manager, right?

**Comment by pudo** [comment]
Not fixed, unfortunately, @kirk.

**Comment by kjacks** [comment]
Damn :( Ok I'm going to run through this this morning and standardize the deletes to always take an entityId.

**Comment by pudo** [comment]
Fixed in 3.9.8 (not yet in OCCRP prod).
