### ISSUE TITLE
Table Editor - Entity properties sometimes not saving

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#1478]
@brrttwrks:
"values entered into table sometimes don't get saved - not sure what conditions are"

@pudo:
"You create an entity and assign it a bunch of properties but only the first column (name) gets stored"

**Comment by pudo** [comment]
For debugging, maybe consider going into `aleph/views/entities_api.py` and adding this to the `update()` function:

```python
import time
time.sleep(.5)
```

**Comment by pudo** [comment]
Haven't seen this in a while - I understand the fix is not perfect, but it seems to do the job in practice.
