### ISSUE TITLE
Structured logging for Aleph on Production

### ISSUE THREAD

**Issue by sunu** [alephdata/aleph#1479]
Downsides of Aleph's unstructured text logs: 
- log entries in Stackdriver show up as text blobs with incorrect level indicators in production
- we can't analyze these logs easily - either with filters provided by Stackdriver or with something like Google's Datastudio tools.

Downside of JSON logs:
- Hard to read in local dev environment

Ideally, we want to
- format our logs as JSON that Stackdriver can parse correctly in the production environment and include context info like request_id, service name, hostname etc
- format them as human readable text on local dev environment

Logging tools to consider:
- [python-json-logger](https://pypi.org/project/python-json-logger/)
- [structlog](https://www.structlog.org/en/stable/)

**Comment by pudo** [comment]
In particular I think we really want this info: 

When running in the API: 

* The client IP
* The user role_id if any
* The session ID
* Possibly a random ID to trace a particular request through all of its log output

When running in the worker: 

* The task metadata (job_id, task name)
* A random ID for a particular task being processed 
* Start time of the processing

**Comment by pudo** [comment]
Looks like the aleph part of this is done - gonna probably have to move it to servicelayer at some point to use in memorious as well.
