### ISSUE TITLE
Wrong OpenID Connect provider hostname

### ISSUE THREAD

**Issue by billder677** [alephdata/aleph#1480]
The new configuration is not using the urls given in the Open ID Connect provider's configuration url.

I'm running Aleph in a Kubernetes cluster together with a Keycloak instance in the same namespace. I'm using SERVICE names and INGRESS fqdn to access pods internally and externally.

What I did:

- Configure `ALEPH_OAUTH_METADATA_URL` to my Keycloak instance according to `aleph.env.tmpl`
- Because Keycloak runs in kubernetes I have to set the hostname to Keycloak's service name because the first request comes from Aleph API pod internally
- The url becomes `http://SERVICE/auth/realms/FOO/.well-known/openid-configuration`

- Output from `.../openid-configuration`:
`
{
    "issuer": "https://INGRESS/auth/realms/FOO",
    "authorization_endpoint": "https://INGRESS/auth/realms/FOO/protocol/openid-connect/auth",
    [...]
}  
`
- Then I want to "Sign in via OAuth"
 
Expected behaviour:

- Redirect to `https://INGRESS/auth/realms/FOO/protocol/openid-connect/auth?response_type=[...]`

Current behaviour:

- Redirect to `https://SERVICE/auth/realms/FOO/protocol/openid-connect/auth?response_type=[...]`
- This is not working because the SERVICE is not exposed externally

It seems that the hostname set in `ALEPH_OAUTH_METADATA_URL` is kept instead of using the entry in `.../openid-configuration`. Setting the INGRESS fqdn in `ALEPH_OAUTH_METADATA_URL` breaks the API because that fqdn cannot be used internally.

**Comment by pudo** [comment]
Weird issu. Are you totally certain that Keycloak will return `INGRESS` URLs in the `openid-configuration` when that endpoint is accessed from within the cluster? Is there anyway to make the FQDN usable for local traffic, or is this some sort of firewall security thing kicking in?

**Comment by billder677** [comment]
> Are you totally certain that Keycloak will return `INGRESS` URLs in the `openid-configuration` when that endpoint is accessed from within the cluster?

Yes, I double checked that a couple of times.

> Is there anyway to make the FQDN usable for local traffic, or is this some sort of firewall security thing kicking in?

Maybe a CoreDNS bug I am working on with our Kubernetes admin. There is no firewall rule prohibiting traffic. To be fair, we are running a rather old cluster on version 1.12. We hope to migrate to a current version soon.

On a side note: Are there any plans for an official helm chart?

**Comment by billder677** [comment]
> Are you totally certain that Keycloak will return `INGRESS` URLs in the `openid-configuration` when that endpoint is accessed from within the cluster?

I checked with the browser and not from within the pod... Using curl inside the pod actually shows the `SERVICE` url.

> Is there anyway to make the FQDN usable for local traffic, or is this some sort of firewall security thing kicking in?

Apparently it is a CoreDNS bug in our rather old version 1.12 of Kubernetes that prevents FQDN resolution. We are hoping to migrate to a current version soon.

Anyway, thanks for enlightening me. :)
