### ISSUE TITLE
Aleph ui doesn't open

### ISSUE THREAD

**Issue by ByUnal** [alephdata/aleph#1485]
![image](https://user-images.githubusercontent.com/43930582/100432585-d9b4a400-30aa-11eb-9e0a-26a3aad84051.png)
I confronted with this issue. I even deleted and built all over again the program. But It didn't work either. How can I solve this ? Thanks.

**Comment by pudo** [comment]
duplicate #1482 - can you pull the latest?

**Comment by ByUnal** [comment]
Fixed.
