### ISSUE TITLE
[object Object] in delete folder URL path

### ISSUE THREAD

**Issue by mattcg** [alephdata/aleph#1488]
Steps to reproduce:

1. Upload folder
2. Delete folder

Aleph v3.9.5

**Comment by pudo** [comment]
This is fixed in 3.9.6. Can you confirm?

**Comment by mattcg** [comment]
Missed that release, sorry. Will check and confirm once helm chart is updated.

**Comment by mattcg** [comment]
Confirmed fixed in 3.9.6.
