### ISSUE TITLE
net::ERR_INSUFFICIENT_RESOURCES in Chrome during folder upload

### ISSUE THREAD

**Issue by mattcg** [alephdata/aleph#1489]
Attempting to upload a folder with just over 5000 files using the web ui. It appears too many simultaneous xhr POST requests are being made. Happy to privately provide sample data.

**Comment by pudo** [comment]
Maybe @felixebert can you have a look at this? Actually sounds like the DOM is dying.

**Comment by mattcg** [comment]
Nice work Felix. I'll test as soon as the new release is deployed but if anyone else confirms the fix before then feel free to close this issue!
