### ISSUE TITLE
No error message when permission denied to see a diagram

### ISSUE THREAD

**Issue by markjohnnightingale** [alephdata/aleph#1493]
Apparently I don't have the permission to see this diagram: https://aleph.occrp.org/diagrams/7974ef719c79474c960cdc01d4b43b23

However when I visit the page, I just see 'never-ending spinner' which continues forever. I only realised that it was a 'permissions' error by opening the console and looking at the JS error :)

**Comment by pudo** [comment]
Fixed in 3.9.8 (not yet in OCCRP prod).
