### ISSUE TITLE
Result highlights aren't being shown 

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1500]
Especially in page searches within a`Pages` entity.

**Comment by kjacks** [comment]
I think this might be a backend issue? I'm noticing that even with the highlight query params set in the entities query, the API is returning a result without a `highlight` key on the Page entity.

![Uploading Screen Shot 2020-12-07 at 12.54.22.png…]()

**Comment by pudo** [comment]
This now tries to highlight within `properties.*` and is more permissive by disabling analyser matches via `require_field_match`.
