### ISSUE TITLE
PDF page rotation/orientation ignored

### ISSUE THREAD

**Issue by mattcg** [alephdata/aleph#1511]
With the attached PDF:

 - some pages of the PDF in Aleph PDF viewer show up landscape others show up portrait
 - all pages of the same PDF in Apple Preview show up portrait (this is in fact how text is visually laid out)
 - after running `pdfimages -all` on the PDF, one can see that the dumped jpgs are landscape (one is portrait)
 - `pdfinfo -f 1 -l 8` shows that pages wrongly displayed in landscape orientation on Aleph have "rot: 270", others "rot: 0"
 - problem seems to be that this rotation attribute is not being respected by the PDF viewer in Aleph UI, or is not being provided correctly by pdflib

Test PDF:
[20. STSA LNG Sale and Purchase Agreement amendment agreement dated 14 December 2017.pdf](https://github.com/alephdata/aleph/files/5672780/20.STSA.LNG.Sale.and.Purchase.Agreement.amendment.agreement.dated.14.December.2017.pdf)

**Comment by pudo** [comment]
Fixed in 3.9.8 (not yet in OCCRP prod).

**Comment by mattcg** [comment]
Nice work @kjacks
