### ISSUE TITLE
Implement 'last seen by you' in localStorage

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1516]
"As a reporter going through I leak, I want to know which documents I've already visited, and which ones are yet to be explored."

Implement a function in the UI that stores the last time a visitor has viewed an entity, either in full screen or preview mode. Visited entity have a little eye behind their links, with a tooltip that shows the last visit time ('3 mins ago', 'May 3, 2020').

This should not require the user to be logged in (it's just a redux state). Maybe visits older than two months should be deleted.

**Comment by mattcg** [comment]
So annoying that we have to reinvent the browser history engine. Wish browsers would expose this data for the current origin.

**Comment by kjacks** [comment]
Solved in #1628
