### ISSUE TITLE
Export network diagrams for embedded use

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1553]
As a user, I want to be able to export a network diagram so that I can embed it into a story. The embed should be an HTML snippet suitable for use as an iframe in a CMS. We should either provide a direct download of the HTML snippet, or export URL that will not expire. 

Here's the steps: 

* Make an HTML template that has two parameters: the diagram data, and a place to inject a current version of ReactFTM. 
* Add ReactFTM to the backend docker image so it can be included in the diagram. 
* Code to generate non-expiring archive URLs
* UI: Button to trigger export.
* UI: Dialog that shows iframe sample code. 

The overall behaviour we want is:

* Interactivity of the network diagram without any backend interaction
* Maybe show the sidebar with all properties? Or some sort of hover popup?
* Once an export is produced, updating the diagram will not automatically change the embed (we need to make this explicit in the UI).

**Comment by kjacks** [comment]
Just to be sure i get the full user flow:
- User clicks diagram export button in the UI
- This sends a request to the diagram-export endpoint passing the diagram id as a param
- The server injects the corresponding diagram data and minified version of current react-ftm into a predefined html template
- This file is then served from somewhere
- The url is returned in the api response
- The user is shown a sample iframe code with the returned url as src

**Comment by pudo** [comment]
Yep. Sound good to you?

**Comment by kjacks** [comment]
@pudo Let me know if I'm on the right track here...

Ok so I've modifed react-ftm and the package will now be distributed with in its /dist:

- react-ftm.js  // existing module library

- react-ftm-embed.js // embed script 
    - can be loaded via script tag on any html page
    - attaches renderEmbed func to window object

- index.html // embed template 
    - pre-populated with react-ftm-embed.js script + call to renderEmbed().  
    - Expects title, data, publicPath as data attributes 
        - if we want to make tables embeddable as well then we could add a type attribute and the rest is already set to go to support it
        - Should it accept a locale as a param? Right now it defaults to English
    - this could be a ejs or hbl template or something? I wasn’t sure what injection method would be easiest so I left it with temp. placeholders but was unsure on syntax
