### ISSUE TITLE
PDF infinite loading when re-fetching

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#1570]
Steps to reproduce:
- click a document-type search result -> the pdf is correctly loaded in entity preview pane
- click "Expand" -> when loading the entity screen, pdfViewer hangs and never re-fetches the pdf

I'm a bit miffed by this one. It only happens when attempting to load a pdf that has already been previously fetched before, and seems to have something to do with pdf-js's internal diffing mechanism for the file parameter to its Document component, which prevents the request for the necessary pdf from ever being sent.

From react-pdf [docs](https://github.com/wojtekmaj/react-pdf): "Warning: Since equality check (===) is used to determine if file object has changed, it must be memoized by setting it in component's state, useMemo or other similar technique."

I was able to fix this issue by adding a short sleep() in between steps 3 and 4 above, but this is less than ideal. It also seemed to be resolved by importing react-pdf components using standard syntax instead of dynamically on mount, but need to be sure this wouldn't jeopardize the worker in prod.

**Comment by pudo** [comment]
I've noticed this bug and it's so incredibly annoying. It'd be brilliant to find a clean solution :)

**Comment by theinfinityproject** [comment]
I have a similar problem that might be related. None of my uploaded pdfs are displayed. It says in the view pane: "Failed to load PDF file." Searching for keywords within a pdf works though and this too:

> * click a document-type search result -> the pdf is correctly loaded in entity preview pane

**Comment by pudo** [comment]
So much faster now... thanks!
