### ISSUE TITLE
Crazy UI behaviour when uploading

### ISSUE THREAD

**Issue by mattcg** [alephdata/aleph#1578]
1. Create a dataset.
2. Click upload and select a largeish folder for upload.
3. The upload dialog disappears almost immediately and the page goes nuts as uploads continue and the UI appears to refresh constantly.
4. The is no way to monitor upload progress.

Expected behaviour:

The upload dialog remains visible and UI polling is temporarily disabled until it finishes or is cancelled.

Aleph 3.9.9.

https://user-images.githubusercontent.com/282964/105188996-cbc45200-5b34-11eb-80cb-426c94c20faf.mov

**Comment by pudo** [comment]
@kjacks maybe we don't want the ingest action to mutate at all? We could still have the dialog call the `forceMutate` thing once at the end of the whole process....

**Comment by pudo** [comment]
Can you confirm this is fixed in 3.9.10 and re-open if not? When I tried it now, it's not an issue any more.
