### ISSUE TITLE
Write access for judgements

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#1580]
Expected behavior: 
I create two investigations containing an entity of the same name. They appear in each others' respective similar screens, and I should then have write access to make judgements between them to build a profile.

But the writeable flag is set to false for all judgements regardless of my collection write access.

**Comment by pudo** [comment]
Ok, I think this was simple. Can you verify the issue was this?

**Comment by kjacks** [comment]
This seems right to me - because before the collection_id in that line in the similar serializer would have always been null, instead of using the entity collection_id to determine writeability?

**Comment by pudo** [comment]
Cool!
