### ISSUE TITLE
Tiny UI issues

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1591]
1) Looks like a tiny regression in the Xref UI: 

<img width="311" alt="Screenshot 2021-01-26 at 10 54 06" src="https://user-images.githubusercontent.com/41628/105829609-e11dfe00-5fc4-11eb-8a6e-541e5763c666.png">

2) And when a collection opens, it always briefly flashes: "Dataset is empty" before showing the stats. This should read `collection.shallow === false` to know if the full collections object with the stats has been loaded....

**Comment by pudo** [comment]
This UI issue is also still here (the box is supposed to be golden): 

<img width="707" alt="Screenshot 2021-01-26 at 10 57 13" src="https://user-images.githubusercontent.com/41628/105830029-4c67d000-5fc5-11eb-9ff3-bcbd0d8e8f82.png">

**Comment by pudo** [comment]
4) One more really weird one: what's that drop down? It shows no menu.... 

<img width="996" alt="Screenshot 2021-01-26 at 17 23 24" src="https://user-images.githubusercontent.com/41628/105873040-5c020b80-5ffb-11eb-814c-102331268bb0.png">

**Comment by kjacks** [comment]
All of these should be addressed by #1596 except number 3 above (the Profile golden issue). I really am struggling to reproduce this - it's golden as expected in develop and I'm still not really able to make profile judgements to test it in prod
