### ISSUE TITLE
aleph module is missing on local development with docker-compose

### ISSUE THREAD

**Issue by wpf500** [alephdata/aleph#163]
This normally first manifests itself as the error "No ingestors found" (e.g. https://github.com/pudo/aleph/issues/135)

The build process for the [pudo/aleph](https://hub.docker.com/r/pudo/aleph/) image clearly does [install the module](https://github.com/pudo/aleph/blob/master/Dockerfile#L12), the proof is:
```bash
$ docker run pudo/aleph ls /aleph/aleph.egg-info
PKG-INFO
SOURCES.txt
dependency_links.txt
entry_points.txt
namespace_packages.txt
not-zip-safe
top_level.txt
```

However, when you follow the `docker-compose` instructions, its no longer there, as shown:
```bash
$ docker-compose up
$ docker-compose run app ls /aleph/aleph.egg-info
ls: cannot access /aleph/aleph.egg-info: No such file or directory
```

This is because [docker-compose.yml](https://github.com/pudo/aleph/blob/master/docker-compose.yml) mounts your local repo to `/aleph` in the container, overwriting the `/aleph` path created in the [Dockerfile](https://github.com/pudo/aleph/blob/master/Dockerfile). The other build commands (various `pip installs` etc.) only have effect because they install files outside of that path. Obviously for developers who had previously run `pip install -e .` on their machines, this problem wouldn't show up.

Therefore, adding a step to run `pip install -e .` locally in the developer installation guide will fix this. It does however makes me wonder why Python requirements aren't just bundled into pudo/aleph-base and the containers then based off that? Or I guess the project should use a virtualenv and developers then install the requirements locally too.

**Comment by wpf500** [comment]
Actually, you'd have to run `pip install -e .` inside the docker container, otherwise it'll try to install lots of things globally on the local machine

**Comment by stas** [comment]
@wpf500 thanks for digging into this.

It looks like a very :snake: issue. Apparently the `.egg-info` is what the development mode does in order to tell python the package is installed. I went through their docs, and it looks like _this is the way it works_™.

I actually asked @pudo previously whenever we do actually need a `setup.py`, and this issue brings this question back on the table. Currently the `setup.py` is not actually used for it's original purpose (requirements.txt is still handling the deps). And I still think we have no reasons to keep the `setup.py`, @pudo if we get the ingestors plugged the other way around?

**Comment by pudo** [comment]
Well, it is used for all sorts of plugins at the moment (ingestors, analyzers, crawlers, etc.) and it is generally the way that aleph's turned into a Python package (i.e. enable absolute imports). So removing the outright seems like it would break many things and fix none.

**Comment by wpf500** [comment]
I'm not sure that this is about how aleph is packaged, although as a side note Python eggs are a very common format so it seems sensible.

I think the problem here is we are using Docker a bit strangely. We take an image (pudo/aleph) which has everything pre-installed and overwrite a small part of that installation (`/aleph`). This feels very brittle. I think containers should only use images "additively" (is that word?!), i.e. we base things on top of the image, not modifying what's already there.

Having thought about it some more, I think the simplest solution would be to base the services in docker-compose.yml on pudo/aleph-base and build them (basically what docker-compose.prod.yml does). Its probably not quite that simple but seems to be more in the right direction.

pudo/aleph can then become a fully built container, as suggested [here](https://github.com/pudo/aleph/issues/130#issuecomment-276050008), making it easier for people to experiment with aleph.

I'm happy to have a go at this if that sounds good?

**Comment by stas** [comment]
@wpf500 it is not an aleph issue. It is related to the way development of a Python package is done. As long as the `.egg-info` is present, you can make edits to the package (any package). The problem, as you pointed, is once you mount the repository any previously generated files/folders are gone.

We had the same issue with bower/npm, but I managed to move it outside the mounted folder.

I guess for now, we will have to document that an initial `pip install -e .` is required. This is painful, but requires the minimum of changes.

@pudo alternatively, in future, we could consider a more pluggable architecture. I believe there are frameworks to handle the same issue outside the `setuptools`.

**Comment by pudo** [comment]
I disagree. What's broken here is the way we do docker; we should stick with standard Python packaging and make that actually work, rather than digging ourselves deeper into hacks that are meant to allow a slightly broken docker lifestyle. Perhaps we can make this part of a boot script that gets run as the docker CMD?

**Comment by stas** [comment]
Sounds good, I'll add it to the make file in this case.
