### ISSUE TITLE
How to speed up

### ISSUE THREAD

**Issue by rider8581** [alephdata/aleph#1630]
Good day.

I have been testing this project with some of the document data and it is working awesome.

Thank you for sharing.

However, it is taking a little long time to process the excel files of millions of rows that I have uploaded.

My server has enough CPU/RAM resources but it is not fully used.

Are there any configuration parameters to process the file in the parallel mode so that it can be faster?

Kindly guide me if it is possible.

**Comment by pudo** [comment]
Indexing a spreadsheet that big is less than ideal. Aleph will only make the first 100MB searchable, that's the limit for a document in ElasticSearch. If applicable, you should consider mapping the spreadsheet to FtM data (Aleph's internal ontology) and then loading the entities into Aleph after generating them. You can find an intro to that process here: https://docs.alephdata.org/developers/followthemoney/ftm and here: https://docs.alephdata.org/developers/mappings

**Comment by pudo** [comment]
Is this resolved?
