### ISSUE TITLE
302 redirect response from api

### ISSUE THREAD

**Issue by rider8581** [alephdata/aleph#1635]
I am using the release version of 3.9.11

And the API returns 302 response for all HTTP requests to redirect to https.

(for example, when I request to http://api:5000/api/2/metadata, it returns 302 response to redirect to https://api:5000/api/2/metadata)

`api_1               | {"time": "2021-02-18T02:03:25.077292", "took": 0.0, "status": 302, "logger": "werkzeug", "timestamp": "2021-02-18 02:03:25.078241", "message": "172.16.60.8 - - [18/Feb/2021 02:03:25] \"\u001b[32mGET /api/2/metadata HTTP/1.1\u001b[0m\" 302 -", "severity": "INFO"}
api_1               | {"time": "2021-02-18T02:03:25.776541", "took": 0.0, "status": 302, "request_logging": true, "logger": "aleph.views.context", "timestamp": "2021-02-18 02:03:25.776597", "message": "Request handled", "severity": "INFO"}
api_1               | {"time": "2021-02-18T02:03:25.776541", "took": 0.0, "status": 302, "logger": "werkzeug", "timestamp": "2021-02-18 02:03:25.777186", "message": "172.16.60.8 - - [18/Feb/2021 02:03:25] \"\u001b[32mGET /api/2/metadata HTTP/1.1\u001b[0m\" 302 -", "severity": "INFO"}
`
![image](https://user-images.githubusercontent.com/52605718/108294379-b53e0480-718d-11eb-8a20-3235fb856f50.png)

Kindly guide me if I missed any configuration.

**Comment by pudo** [comment]
try adding the following to your environment configuration: 

```
ALEPH_FORCE_HTTPS=false
ALEPH_URL_SCHEME=http
```

But I'd advise you to look into setting up a TLS solution before you expose this to the public internet :)

**Comment by rider8581** [comment]
Your solution works but as you mentioned, since the UI runs on https and API runs on HTTP, there are some errors on UI like mixed contents.
How can I configure API to run on https?
