### ISSUE TITLE
Entity Search for Exact match

### ISSUE THREAD

**Issue by rider8581** [alephdata/aleph#1640]
I am trying to search entities with an exact match like "nicholas_911",

![image](https://user-images.githubusercontent.com/52605718/108654259-3532da00-74c0-11eb-8e09-3ab330fe8ac2.png)

But it is returning not only an exact match of my word but also too many false-positive results.

I think it is returning all matches of "nicholas" rather than "nicholas_911".

Please help me fix this issue.

thank you.

**Comment by pudo** [comment]
I think the way ElasticSearch parses this, nicholas_911 is two tokens. You probably need to mess significantly with the analysers if you want to avoid this. For most of the data we deal with, however, that sort of tokenisation is desirable - so I'm closing this.

Please also have a look at https://github.com/alephdata/aleph/blob/main/CONTRIBUTING.md regarding support.
