### ISSUE TITLE
Set the `X-Opaque-Id` header on Elasticsearch requests so that running tasks within Elasticsearch can be traced back to a request

### ISSUE THREAD

**Issue by sunu** [alephdata/aleph#1723]
Elasticsearch [cat task management API](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/cat-tasks.html#cat-tasks) can list detailed information about running tasks within the cluster and it's very helpful in debugging performance issues.

But to identify a running task and associate it with a request, `X-Opaque-Id` header must be set referring to the request id or a trace id. https://www.elastic.co/guide/en/elasticsearch/reference/current/tasks.html#_identifying_running_tasks

**Comment by pudo** [comment]
Fixed in #1730.
