### ISSUE TITLE
Sanctions not downloadable anymore

### ISSUE THREAD

**Issue by fastbone** [alephdata/aleph#1740]
When you run make sanctions it results in multiple errors.

e.g.
https://storage.googleapis.com/occrp-data-exports/ca_dfatd_sema_sanctions/ca_dfatd_sema_sanctions.json

<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>

**Comment by pudo** [comment]
Yep, there's a bit of a transition happening - crawlers aren't in our rotation for the moment. I'm trying to get funding to work on the sanctions data project for a couple of months from September. See https://github.com/pudo/opensanctions to track progress (and welcome to file tickets there).
