### ISSUE TITLE
FATAL:  could not write init file

### ISSUE THREAD

**Issue by yuvalfis** [alephdata/aleph#1753]
Hi,
I'm trying to run aleph on my local computer. on creating aleph_app_run I get an error:

```  
File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  could not write init file
```

I would like to know how can solve this issue.
Thanks.

**Comment by pudo** [comment]
This sounds like postgres is failing to boot correctly on your machine. Can you check out `docker-compose logs postgres` to see if there are more error messages? I assume there's some sort of funky interaction between docker and your file system, but that sort of stuff is a little bit outside the scope of aleph - the people who package postgres for docker might be more help.
