### ISSUE TITLE
[Question] Filter Example in the Docs do not work?

### ISSUE THREAD

**Issue by colonyshipforsale** [alephdata/aleph#1764]
Hi,

It seems **Filtering source data** as described in the docs do not work? See @ https://docs.alephdata.org/developers/mappings

Aleph generated **all 653** entities instead of the filtered (conservative & not male) **67 entities**.

- **Can anyone give me a hint, maybe i am doing something wrong? Source data and YML are acc. to the docs.**
- **I want to use mixed entities in a CSV and only load specific rows ... i suppose the filter would let me do that, no?**

To reproduce:

> I am using the UI and Version 3.10.0 (docker)
> 
> I uploaded the CSV and **before generating the entities** i loaded **filters.yml** (see below)
> 

**source data**

> http://bit.ly/uk-mps-csv

**filters.yml**

> ```
> gb_parliament_57:
>   queries:
>   - csv_url: http://bit.ly/uk-mps-csv
>     filters:
>       group: "Conservative"
>     filters_not:
>       gender: "male" 
>     entities:
>       member:
>         schema: Person
>         keys:
>         - id
>         properties:
>           name:
>             column: name
> ```

**Comment by colonyshipforsale** [comment]
I now tried a different approach instead of the yml filters and solved it with an awk script that separates a (multi entity) CSV into smaller (2 entity type) CSV's that depict relations between 2 entities like eg. person <-> company or company <-> company and so on. 

I will try to  to dynamically generate the mapping.yml file for each CSV and periodically reingest the CSV's and YML files all based from a single CSV sheet that I use for data capture of entity & link data.

If the filtering example mentioned earlier is in fact working and not a bug, then this issue can be closed (solved with workaround).

**Comment by pudo** [comment]
I have to ask because I'm curious: how did you decide that doubling the complexity of your load process was an easier option than checking the code for the filters and seeing why they didn't work as expected on your CSV file, maybe submit a PR to `followthemoney`? 

(Ref: https://github.com/alephdata/followthemoney/blob/master/followthemoney/mapping/source.py#L22 )

**Comment by colonyshipforsale** [comment]
> I have to ask because I'm curious: how did you decide that doubling the complexity of your load process was an easier option than checking the code for the filters and seeing why they didn't work as expected on your CSV file, maybe submit a PR to `followthemoney`?
> 
> (Ref: https://github.com/alephdata/followthemoney/blob/master/followthemoney/mapping/source.py#L22 )

Thanks for the pointers, I confess after checking it, I still don't understand whether the problem was of my own test setup or a bug, hence why i cautiously wrote the issue as [question] - after all the problem sometimes might be sitting between the screen and chair :)

I don't have a good test <-> code grasp yet. The workaround it is a quick solution while I find out whether it can be solved with the filters? Shall we reopen this, I am happy to contribute with eg. retests? Let me know .. thx!
