### ISSUE TITLE
Emails contain invalid URLs

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1804]
https://github.com/alephdata/aleph/blob/main/aleph/logic/util.py#L39 - route doesn't exist in the UI. Probably should.

**Comment by kjacks** [comment]
@pudo Interesting - what was the case where this led to a broken link?

**Comment by pudo** [comment]
yes! When you receive an email notification a la "User X has created a new network diagram called Z", Z will be a link to `aleph....org/sets/ZID`. This is on the premise that `/sets/` is a route that will redirect you to `/diagrams/`, `/timelines/` etc based on the entity set type. Seems like a cool feature to have, wdyt? Otherwise, you'll need to dispatch on type in the backend, should also be easy to do.

**Comment by kjacks** [comment]
Definitely! totally agree that this makes sense to catch that case on the routing end - I'll add it in to the router
