### ISSUE TITLE
Re-ingest does not re-ingest files from storage

### ISSUE THREAD

**Issue by mattcg** [alephdata/aleph#1814]
I'm not sure if this is a bug or it's supposed to work this way. I was attempting to debug why ingest suddenly stopped working on our Aleph instance.

Steps to reproduce:

1. Create a new investigation on an Aleph instance that is configured to use S3-compatible backend - latest Minio in this case.
2. Upload any files to the documents section of the investigation.
3. Search for files.
4. Re-ingest the files with the index option ticked.

What happens:

1. The files upload successfully and each file can be downloaded.
2. Preview for the files doesn't work and no text is indexed. Results only show up only if the search term appears in the filename.
3. When re-ingesting and running `mc admin trace --all --verbose my-minio` nothing prints, indicating that Aleph is not hitting Minio even when attempting re-ingest, so it's not a case of incorrect permissions (which would show a 403) or anything like that.
4. `kubetail -n aleph` shows no errors.

**Comment by pudo** [comment]
I'm not sure this is a re-ingest issue, it just sounds like the ingestor doesn't work in the first place. Is there anything (remarkable or mundane) visible in the logs for `ingest-file` docker containers in after uploading the documents? Do they a) start processing the documents (a message a la `Ingest: <E(id:schema)>`), b) report an error while doing so?

**Comment by mattcg** [comment]
So the MIME type is correctly detected as `application/pdf` - this is what shows up in the sidebar for the file.

Yes, there are messages from the `aleph-ingest-file` containers, for example:

`[aleph-worker-6ff89fbf45-45kqt] 2021-05-25 16:44:04.929706 [debug    ] Ingest entity [redacted]: Index.pdf [aleph.queues]`

followed by:

`[aleph-ingest-file-7c7c7f8f9d-bkzkp] 2021-05-25 16:42:25.700152 [debug    ] Ingest: <E('[redacted]','Index.pdf')> [ingestors.worker] `.

But nothing else apart from these debug messages. Not even an error. And it isn't hitting the storage backend.

**Comment by mattcg** [comment]
I forgot to say that you're right that this is an ingest issue and not strictly re-ingest. The behaviour is exactly the same when new files are uploaded.

**Comment by pudo** [comment]
I think there may an issue that prevents the PDF support from loading when the ingestor service starts up. I've made changes to the component that would make these issues more apparent. Can you try and deploy `ingest-file:3.14.3` and report if that crashes on startup? (I hope so :/)

**Comment by mattcg** [comment]
I'm a bit reluctant to do that on our production system but will do it if you think it's worthwhile. The problem isn't restricted to PDFs however. It's the same for all file types.

I just tried uploading a docx:

- upload succeeds
- logs show:

```
[aleph-api-84c544cf58-wcwd5] 2021-05-29 10:48:54.672442 [debug    ] Ingest entity [2772804.035e4e25a9757f93077974c0d623fac996bb64a2]: XYZ.docx [aleph.queues]  
[aleph-api-84c544cf58-wcwd5] 2021-05-29 10:48:54.705518 [info     ] Request handled                [aleph.views.context] request_logging=True 
[aleph-api-84c544cf58-wcwd5] 10.42.0.0 - - [29/May/2021:10:48:54 +0000] "POST /api/2/collections/1/ingest?sync=true HTTP/1.1" 201 74 "https://[redacted]/investigations/1" "[redacted]" 
[aleph-api-84c544cf58-wcwd5] 2021-05-29 10:48:55.122943 [info     ] Request handled                [aleph.views.context] request_logging=True 
[aleph-api-84c544cf58-wcwd5] 192.168.9.7 - - [29/May/2021:10:48:55 +0000] "GET /healthz?ready HTTP/1.1" 200 16 "-" "kube-probe/1.18" 
[aleph-worker-6ff89fbf45-9pbvs] 2021-05-29 10:48:55.222225 [info     ] Task [1]: index (started)      [aleph.worker]  
[aleph-worker-6ff89fbf45-9pbvs] 2021-05-29 10:48:55.228258 [debug    ] [f7d4850d2de14ce79d6e884bb9b27472] Indexed 1 entities [aleph.logic.collections]  
[aleph-worker-6ff89fbf45-9pbvs] 2021-05-29 10:48:55.243384 [info     ] Task [1]: index (done)         [aleph.worker]  
[aleph-ingest-file-7c7c7f8f9d-bkzkp] 2021-05-29 10:48:54.926700 [debug    ] Ingest: <E('2772804.035e4e25a9757f93077974c0d623fac996bb64a2','XYZ.docx')> [ingestors.worker]  
```

- mime type is detected as `
application/vnd.openxmlformats-officedocument.wordprocessingml.document`
- "No preview is available for this document" when you attempted to preview the file
- document contents is not indexed and the document only shows up when searching the filename

**Comment by mattcg** [comment]
> Can you try and deploy `ingest-file:3.14.3` and report if that crashes on startup? (I hope so :/)

Update: I deployed it and it and the behaviour is identical - no crash, no error logs.

**Comment by Rosencrantz** [comment]
Hey @mattcg 

Thanks for the update, have there been any changes in the underlying architecture recently that might have caused this to start happening? From what you've said, it sounds like you'd not get this issue locally, but only when you're running on AWS?

**Comment by mattcg** [comment]
Hi Steve! This is on k8s managed using Rancher. There was no architecture change that I can remember.

**Comment by Rosencrantz** [comment]
Thanks @mattcg. We'll see if we can figure out what is going on

**Comment by sunu** [comment]
@mattcg Hi Matthew! Have you made any more progress on figuring out the cause of the issue? If not, I will schedule some time to  look more into it later this week.

I have a few question to help in debugging. Can you download the uploaded files through Aleph's UI? Does the same problem occur if you upload a plaintext file where no complicated conversion or text extraction is required? Can you upload files into Minio from a ingest-file container using servicelayer directly from a shell to check if there are no configuration issues?

**Comment by mattcg** [comment]
Hey sunu! No progress yet. I'm happy you can schedule time to help with this :)

> Can you download the uploaded files through Aleph's UI?

Yes.

> Does the same problem occur if you upload a plaintext file where no complicated conversion or text extraction is required?

Yes, same problem. The file upload 'succeeds' but searching for a keyword that appears in the txt file yields no results.

> Can you upload files into Minio from a ingest-file container using servicelayer directly from a shell to check if there are no configuration issues?

You're pushing my k8s knowledge beyond its limit :) But if it helps, file uploads to Minio actually succeed when using the Aleph UI to upload.

**Comment by sunu** [comment]
Hi @mattcg! I didn't have much success in reproducing this issue locally. Would you or someone on your team be up for discussing this issue on a call some time this week?

**Comment by mattcg** [comment]
Yes, of course. Let's arrange a time on slack.

**Comment by mattcg** [comment]
Thanks to @sunu for helping with debugging. The `ARCHIVE_*` environment variables were set in `global.env` instead of `global.commonEnv` in the values YAML so `ARCHIVE_TYPE` was defaulting to `file` in the `ingest-file` pods. But at the same time, errors were being swallowed by `ingest-file` commit https://github.com/alephdata/ingest-file/commit/a3146c41403d8cb015fc4ff43608d9c33a7b8f62 fixes that.
