### ISSUE TITLE
Fix up facets API for non-standard property types

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#1819]
Via #1803, users can choose random index fields to facet on, especially all the `properties.bla` fields. However, facets need some post-processing to be useful to the user - e.g. country codes are supposed to be expanded into codes and labels. This happens in a manner that's currently hard-coded to certain index fields here: 

https://github.com/alephdata/aleph/blob/main/aleph/search/result.py#L76

We need to make this more flexible to that it supports all `followthemoney.types:registry.groups` and all properties defined in ftm.

**Comment by kjacks** [comment]
<img width="516" alt="Screen Shot 2021-06-02 at 12 51 01" src="https://user-images.githubusercontent.com/6720200/120468358-69604580-c3a1-11eb-8fd5-4ceb93029565.png">

versus 

<img width="565" alt="Screen Shot 2021-06-02 at 12 51 49" src="https://user-images.githubusercontent.com/6720200/120468381-711fea00-c3a1-11eb-901d-47712d89bc2f.png">
