### ISSUE TITLE
documentation how to set up a crawler

### ISSUE THREAD

**Issue by vwormer** [alephdata/aleph#183]
It would be very nice to have a documentation on how to set up a crawler that is able to import structured data from a external (graph) database.

**Comment by pudo** [comment]
Sorry I haven't responded to your email yet, I was on holiday! Here's the documentation, we just hadn't linked it to the home page yet: https://aleph.readthedocs.io/en/latest/mappings.html

**Comment by pudo** [comment]
And here, @smmbllsm has filed an example mapping for the US sanctions: https://github.com/alephdata/aleph/pull/181/commits/c2d1a7162c0651e145779dffc8f344ef7dcaf36d

**Comment by pudo** [comment]
Closing for now. Please let me know if you want to discuss further.
