### ISSUE TITLE
Export_Search_Kulibayev.zip

### ISSUE THREAD

**Issue by Laemmergeier** [alephdata/aleph#1885]
Dear Sir or Madame,

My Export of the search for "Kulibayev" (within Aleph) was apparently to large:

"Export_Search_Kulibayev.zip":

 
"This data export was aborted before it was complete, because the total size of the
exported entities exceeds the limits set by the system operators.
 
Contact the operator to discuss bulk exports."

I would be happy if someone could provide a download link with all the data.

Best

**Comment by sunu** [comment]
Hi, I believe we have replied to your email concerning data export. Closing this issue since it's related to OCCRP's Aleph instance and not Aleph the software.
