### ISSUE TITLE
Search results: handle date filter values with varying precision

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#1893]
With the ability to add date-type property filters introduced in #1803 , users can now select individual dates to filter search results by. 

Though the rest of Aleph supports dates of varying precision (i.e. YYYY, YYYY-MM, or YYYY-MM-DD), the filter value processing in the backend incorrectly converts all dates to January first of the given year.

Solution 1: Modify backend date processing to support varying precision of dates

Solution 2: Utilize the date histogram for all date-type properties

<img width="1115" alt="Screen Shot 2021-07-14 at 14 09 55" src="https://user-images.githubusercontent.com/6720200/125619913-54160a4e-0278-43c7-906f-69d18c73c0de.png">

**Comment by sunu** [comment]
IMO we should rather show less helpful information than wrong/misleading information. So I would prefer we used a histogram for dates until the backend can handle date precision correctly.

@pudo has made a library for precision handling and there is a PR against FtM to integrate that: https://github.com/alephdata/followthemoney/pull/441. Hopefully it'll make handling date precision easier.
