### ISSUE TITLE
Copy existing entities and documents into new collections

### ISSUE THREAD

**Issue by rhiaro** [alephdata/aleph#196]
To save re-typing names of entities or re-processing documents to add them to a new collection, it would be nice to have a button to add any existing entity to a collection, or to bulk add them from a list.

**Comment by rhiaro** [comment]
Also useful? When you create a new entity in a collection and aleph automatically cross-references it with documents, ability to directly add the documents in that list to the collection.

**Comment by pudo** [comment]
Closing this for now, as it may very well end up being a Case/Collection distinction, which could make this much easier.
