### ISSUE TITLE
Khmer language is not supported 

### ISSUE THREAD

**Issue by arky** [alephdata/aleph#1986]
It is not possible to ingest Khmer language documents for OCR as the language is available in the investigation. 

![image](https://user-images.githubusercontent.com/808895/135480797-5adb0fe2-80ba-4fda-8a8e-4dfb1920cc53.png)

**Comment by sunu** [comment]
Hi @arky, we would appreciate the help for sure. We have some documentation on how to add a new language to Aleph at https://docs.alephdata.org/developers/technical-faq#how-do-i-add-support-for-a-new-language-to-aleph. The second part of the section describes how to add a new language for the ingestion pipeline.

If you could make a PR to add Khmer language support, we would be happy to merge that in. And we would be happy to help you along the process.

**Comment by arky** [comment]
Thank you @sunu I have added support for ingestion of Khmer documents. Unfortunately there isn't a spacy model for Khmer language yet.

**Comment by sunu** [comment]
Thanks a lot @arky! I'll make sure we merge your PRs in next week before the next Aleph release.

**Comment by sunu** [comment]
OCR support for Khmer language is now available in Aleph 3.12.0
