### ISSUE TITLE
Accessibility - Colour Blind Friendly Icon Selection

### ISSUE THREAD

**Issue by frasercrichton** [alephdata/aleph#2006]
Hi there,

I'm red/green/blue colour blind and struggling a bit with your colour selection icons on entities:

<img width="249" alt="Screen Shot 2021-10-11 at 3 06 41 PM" src="https://user-images.githubusercontent.com/52700324/136723383-e807d6e0-673c-4b13-9577-305bb4a01af6.png">

Could you add some labels so I know what's Red/Green/Blue, please?

**Comment by frasercrichton** [comment]
Thanks @Rosencrantz !

**Comment by Rosencrantz** [comment]
@kjacks As discussed, in the short term let's add a 7th "color" that opens a palette picker so it's possible to select whichever color you want. 

@frasercrichton Will having a color picker help to resolve the contrast issue? We felt this was a relatively quick fix, and possbily a starting point for something a bit more robust in the future.

**Comment by tillprochaska** [comment]
Closed in https://github.com/alephdata/react-ftm/pull/838
