### ISSUE TITLE
Network Diagram Labels

### ISSUE THREAD

**Issue by frasercrichton** [alephdata/aleph#2009]
With the network diagrams, the automatic `...` ellipsis and summarised text aren't working so well for me. It would be really good if the user could control the label length or have a mode that just displayed full-length strings. I know there are no easy options here - just a thought.

**Comment by frasercrichton** [comment]
I LOVE your network diagrams! Look forward to seeing how they develop and thanks for looking at this.

**Comment by tillprochaska** [comment]
Fixed in https://github.com/alephdata/react-ftm/pull/837
