### ISSUE TITLE
notification label when table is part of a file

### ISSUE THREAD

**Issue by jlstro** [alephdata/aleph#2044]
Aleph displays excel (libre office, open office...) files like folders and the individual worksheets within a file like files within a folder. This may lead to confusion, for example when a search returns a table and the user does not realize that there is more in the same file to look at for context (or when dowloading the file). 

There should be a notification or warning label that encourages the user to go up one level and look at the entire file.

<img width="1031" alt="Screenshot 2021-11-04 at 16 29 05" src="https://user-images.githubusercontent.com/3785873/140355508-78e06af2-bf72-4080-a8bd-6a959f03675f.png">

**Comment by kjacks** [comment]
@jlstro So the proposal is some kind of message at the top of the TableViewer in Aleph that says "You're viewing one sheet of a potentially larger workbook, view the entire workbook here"?

**Comment by jlstro** [comment]
Yes, that's exactly what I had in mind :)
