### ISSUE TITLE
Folder structure view not available to users without editing permission

### ISSUE THREAD

**Issue by jlstro** [alephdata/aleph#2045]
The upper documents tab (see screenshot) is only visible to users who have writing/editing permissions in a dataset. This means that users with read-only rights cannot navigate the folder structure at all. 

The tab should be accessible for all users. To avoid confusion with the entity type also called documents (the one below, in the screenshot) it should be renamend to folder structure, file tree, something like that. 

This probably touches on https://github.com/alephdata/aleph/issues/1946...

<img width="489" alt="Screenshot 2021-11-04 at 16 33 10" src="https://user-images.githubusercontent.com/3785873/140360525-2b809abe-ad4a-44b4-85a1-8afec390e3a7.png">

**Comment by kjacks** [comment]
@jlstro I go back and forth on this:

- On the one hand, I definitely see the case where a user wants to navigate the folder structure of a dataset, and will gain some understanding from the structure itself, in addition to the documents contained within.

- On the other hand, I think it needs to be implemented in a way that avoids the inevitable confusion of opening a dataset, seeing something called "Files" or "File tree" or something at the top, and expecting all of the dataset's contents to be there. Many/most datasets will consist mostly of entities that aren't present in this File view, and I can imagine it being quite confusing to see open dataset that has a ton of content, but an empty file tree view.

**Comment by jlstro** [comment]
Maybe it should be somewhere else on the page? Less prominent?
