### ISSUE TITLE
Tagging entities in a collection

### ISSUE THREAD

**Issue by rhiaro** [alephdata/aleph#205]
Entities in a collection could be tagged to add more information and aid filtering/sorting/highlighting, in particular to call out key players in an investigation as opposed to entities added for background or completeness.

Maybe related to adding free text notes to entities and documents.

**Comment by pudo** [comment]
I wonder if we're talking about a controlled vocabulary here, or about a free-form tagging thing. I imagine encouraging some type of coherence in the tags (such as "PEP", "Key Player" ...) may actually be good in terms of making this more useful...

**Comment by pudo** [comment]
Superseded by #334.
