### ISSUE TITLE
Improve task queuing and processing

### ISSUE THREAD

**Issue by sunu** [alephdata/aleph#2127]
### Current issues
We are facing 2 issues with out current home-grown task queuing and processing system:

- It doesn't handle failed workers and hanging tasks too well. This results in jobs stuck at 99% or 100%. See https://github.com/alephdata/aleph/issues/1839
- We run out of memory when under load of increased rate of incoming tasks over an extended period of time. This is mainly because we use Redis to store pending tasks. Redis is an in-memory database. So it can only hold tasks equivalent to the available RAM.

### Features we want
Ideally we want the following from our task queuing and processing system:

1. It should mark tasks as failed or retry them when a worker is killed with SIGKILL/SIGTERM.
2. It should mark tasks as failed or retry them when a worker is killed with ACPI G2 (https://cloud.google.com/compute/docs/instances/spot#preemption), power loss etc.
3. It should write tasks to disk if there is not enough memory available.
4. We should be able to query it to see the current state of the queue. We need this to be able to show processing status for collections.
5. Optionally, it would be good to have a broker that can run in-memory. This would be helpful if we want to use the same task queuing and processing system for Memorious. Currently Memorious cli in development mode can run against fakeredis which is more convenient than running Redis in a docker container.

### Implementation options
We have a few options on how to implement this:
- With a Redis based library like RQ: https://python-rq.org/
- With RabbitMQ: https://www.rabbitmq.com/
- With something like Kafka which will also act as our event store (See https://github.com/alephdata/aleph/issues/2128)

### Feature matrix

This is based on my current assumptions. So it might not be entirely based in reality.

|                                              | RQ | RabbitMQ | Kafka | Current Implementation |
|----------------------------------------------|----|----------|-------|------------------------|
| 1. Retry/mark failed on SIGKILL/SIGTERM      | ✔  | ✔         | ❔     | ✔                      |
| 2. Retry/mark failed on spot node preemption | ✔   | ✔         | ❔     | ❌                      |
| 3. Use disk when memory is full              | ❌  | ✔         | ✔     | ❌                      |
| 4. Query for state                           | ✔   | ✔         | ❌     | ✔                       |
| 5. Run in-memory if possible                 | ✔   | ❌        | ❌     | ✔                      |

**Comment by anderser** [comment]
Have you looked at Celery (https://docs.celeryproject.org/en/stable/getting-started/introduction.html)? I have used that for a lot of task queues. Very stable and I think it could do what you need.

**Comment by sunu** [comment]
Aleph used to use Celery a few years back. IIRC it worked well when it did but sometimes the workers used to just hang and it was hard to debug problems in general. Also using something a bit low level than Celery gave us some extra flexibility when it came to code structuring and simplified the debugging experience quite a bit.

**Comment by pudo** [comment]
If I recall correctly, the reason we kicked out Celery was a) to lose the rabbitmq dependency, b) to be able to do really precise reporting on queue fill state. The former is more relevant for memorious, where running rabbitmq makes it much much heavier. The latter was the main reason, and it's probably a bit wrong in that there is Flower (the monitoring tool) and it obviously does inspection just fine.

I feel as a civic tech project, Aleph should always fall back onto the most boring technology solution that will do the job, and for Python task processing, Celery is certainly that (definitely more than using raw amqplib, as attractive is that may be in terms of ease of transition). 

Some random thoughts regarding celery:

* I love the idea of not implementing our own worker. We're certainly only doing 30% of the signals handling we should be. 
* We really want some way of doing bulk fetching of tasks to make the indexer happy...
* We should be able to use topics and exchanges to query the task count per collection and produce the most basic of status bars: https://docs.celeryproject.org/en/stable/userguide/routing.html#manual-routing 

I haven't done research on rq and other options yet, so will add more thoughts once I get around to that. 

p.s. Maybe the answers for aleph and memorious on what to queue with want to be different? Aleph wants total safety at the price of fat infra -> celery, and memorious to be easily installable but maybe require some repeated runs -> rq? Weirder things have happened, and we shouldn't fetishise servicelayer :)

**Comment by sunu** [comment]
Yes, I'm prototyping that as well. I'm using pika (https://github.com/pika/pika) to make the existing worker fetch tasks from RabbitMQ. I've got it working with the Aleph worker. `ingest-file` is next.

Batch processing for indexing jobs is doable by using a high enough `prefetch_count` and a timer. We may need a separate queue and channel for indexing jobs though since `prefetch_count` is channel wide setting.
