### ISSUE TITLE
Adopt Dart Sass as a replacement for node sass

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#2146]
node-sass is now deprecated and we should update to use dart-sass. However, dart-sass is currently incompatible with. the ARM based M1 macs.

Once dart is supported on the M1 architecture, update to use it and deploy with Aleph.

**Comment by sunu** [comment]
See https://github.com/alephdata/aleph/pull/2145 and https://github.com/alephdata/aleph/issues/2140 for more context.

**Comment by tillprochaska** [comment]
We’re now using Dart Sass, the changes will be included in the next release.
