### ISSUE TITLE
Improve API documentation

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#215]
We need to: 

* Decide what the authoritative location for API documentation is, or whether we want to use some sort of swagger generator.
* Document the new JWT token-based auth, perhaps to the point where we can get rid of API keys?
* Document the Xref API
* Document some best practices for using the API in general

Do we also want to think about making a Python client library for Aleph?

/cc @rhiaro @noelmas

**Comment by pudo** [comment]
Move API docs to Sphinx

**Comment by pudo** [comment]
Some bits that are out of date vs. the actual API:

* Make a clear distinction between the /api/2/search, /document and /entities APIs and their similarities.
* Remove the cooccurrence API docs, the API is gone 
* Remove collection special facet on /search APIs
* Document how to generate a JWT token using password-based and OAuth login. 

Other than that, really good progress.

**Comment by rhiaro** [comment]
Okay I did 3/4 of those. Someone else should take the JWT stuff, or else explain it to me and then I'll write it.
