### ISSUE TITLE
Revamp the links data model

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#216]
Do research at:

* ORBIS documentation 
* OpenOwnership documentation 
* OpenCorporates
* Convo with @lejlac, Miranda 

Also: do we want to rename Legal Entity to something else?

**Comment by rhiaro** [comment]
Useful things from the [Beneficial Ownership standard](http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html):

* [ Interest ]
  * type
    * shareholding
    * voting-rights
    * appointment-of-board
    * influence-or-control
  * interestLevel
    * direct
    * indirect
    * unknown
  * details
  * annotation
  * startDate
  * endDate
  * share
    * [ Share ]
      * exact
      * minimum
      * maximum
      * exclusiveMinimum
      * exclusiveMaximum

Maybe most of our LegalEntity-Organisation links could be covered by different types of Interest.

**Comment by rhiaro** [comment]
From the [Open Corporates API](https://api.opencorporates.com/documentation/API-Reference):

* statements
  * type (I couldn't find a definitive list, but the ones I saw are):
    * subsidiaries
    * shareholdings
    * acquisitions
    * branches
    * licence
  * subject company/entity
  * object company/entity
  * predicate (a string like "had Licence")
  * source
  * properties (eg. jurisdiction, category)
* relationship - like 'current status' between two entities. "These relationships are computed automatically from ... `statements` associated with each company"
  * relationship_type (e.g. subsidiary, shareholding)
  * relationship_properties (e.g. ownership percentage)
  * confidence (1-100)
  * parent_name/type
  * child_name/type
* entity/company
  * all the usual stuff
  * controlling_entity: "This is the controlling parent of the company in question, and is derived either from explicit subsidiary or parent data, or from a company having a majority equity stake in the company"
  * ultimate_beneficial_owners
  * branch_status: F (foreign), L (local) or null (unknown)
  * home_company: "when a company is a branch of an out-of-jurisdiction company, this is the 'home' company (if we know it), including the name, jurisdiction_code, company_number and opencorporates_url"

**Comment by rhiaro** [comment]
[Org-id](http://org-id.guide/about) provides a schema for disambiguating company IDs from different jurisdictions:

```
{
    "scheme": "GB-COH",
    "id": "09506232
}
```

**Comment by rhiaro** [comment]
The ORBIS model appears to contain metadata for the following kinds of links between entities:
* Shareholders
* Immediate parents
* Domestic ultimate owner
* Global ultimate owner
* Controlling shareholders
* Ownership graph
* Subsidiaries
* Hidden ownership
* Branches
* Portfolio
* Portfolio history
* Controlling portfolio
* PE firms
* Divesting shareholders
* Divesting shareholders intermediaries
* Headquarters
* Mergers & acquisitions
* Royalty agreement

And has a concept of a 'corporate group' with size (no. of companies therein).

**Comment by rhiaro** [comment]
Re: `LegalEntity`, OpenCorporates calls things its not sure about `Placeholder`

**Comment by pudo** [comment]
Now at https://github.com/alephdata/followthemoney/issues/3
