### ISSUE TITLE
keycloak oauth redirect

### ISSUE THREAD

**Issue by sunflowerno0b** [alephdata/aleph#2160]
hi there,

I have a keycloak oauth redirect issue. Ive attached an output of the logs. Searching previous issues I found [this](https://github.com/alephdata/aleph/issues/868) but that was for google oauth. It appears that there might be a mishandling of the exchange between keylcoak and my aleph instance. Any suggestion? 

Same settings have been made for my production, which works just fine; oddly enough.

![Screen Shot 2022-03-14 at 10 22 17 AM](https://user-images.githubusercontent.com/68705196/158208740-a94591ba-6718-4812-975d-331a7b1b95cb.png)

**Comment by sunu** [comment]
Hey @sunflowerno0b, is this a local development instance? To me it looks like Aleph is not getting a valid JSON response back from Keycloak. Is Keycloack up and running without any problems? Can you access the admin dashboard there?

If everything is fine with Keycloak, we'll need some help from you to figure out the problem. Can you inspect the response from keycloak using a debugger?

**Comment by sunu** [comment]
Hey @sunflowerno0b, what does your `ALEPH_OAUTH_KEY` setting look like? Does it have an `_` (underscore) in it? Keycloak seems to be complaining about an underscore.

`java.io.IOException: Bad Base64 input character decimal 95 in array position 23` - ascii character code 95 is an underscore.

**Comment by sunflowerno0b** [comment]
I was able to fix - the issue with was with the `ALEPH_OAUTH_SECRET` appears my password was too complex, might be a good idea to outline what symbols are allowed. While my secret did not contain an underscore, it included other symbol types for additional security measures.

**Comment by sunu** [comment]
Thank you for reporting back with the fix @sunflowerno0b!
