### ISSUE TITLE
ALEPH_SAMPLE_SEARCHES doesn't seem to work

### ISSUE THREAD

**Issue by siccovansas** [alephdata/aleph#2174]
I have changed some values in `aleph.env` which works fine (e.g., `ALEPH_APP_TITLE`, `ALEPH_UI_URL`, etc.). The text I added to `ALEPH_SAMPLE_SEARCHES` doesn't work though. My mainpage still shows 'Vladimir Putin, TeliaSonera'.

See: https://github.com/alephdata/aleph/blob/e59c95b201313bbe40cd036f5d2aeb0f8b599639/aleph.env.tmpl#L21

**Comment by sunu** [comment]
The home page is now configured via Markdown and the sample searches are also configured similarly through markdown frontmatter: https://github.com/alephdata/aleph/blob/63177535f647cbc206b3455a2025f93bb2619bb1/aleph/pages/home.en.md?plain=1#L6

We should document that and remove the unused `ALEPH_SAMPLE_SEARCHES` setting

**Comment by msmych** [comment]
Hi, please check https://github.com/alephdata/docs/pull/11 and https://github.com/alephdata/aleph/pull/2242

**Comment by Rosencrantz** [comment]
Thanks for this @msmych we will take a look.

@sunu I may well be missing something here, but it feels kind of odd to have this information in a markdown file. Wouldn't it make sense to incorporate it into the translations text?

**Comment by sunu** [comment]
@Rosencrantz We generally translate hard-coded terms in the ui. These placeholder search terms are meant to be configurable though.

Closing this issue since I think we have taken care of updating the documentation. Thanks a bunch @msmych!
