### ISSUE TITLE
Aleph vs Datashare/Giant?

### ISSUE THREAD

**Issue by ninoppp** [alephdata/aleph#2178]
Hey there

I'm currently checking out different platforms for investigations to set up for a small organization. 
While we're doing local testing, I'd also like to ask you directly:

What are the main differences between Aleph and alternatives, such as the ICIJ's Datashare or The Guardian's Giant? Which features do the others not have, which ones is Aleph missing? 

Thanks for bothering :)

**Comment by pudo** [comment]
What is your evaluation so far?

**Comment by ninoppp** [comment]
I'm quite torn. To me it seems, that Datashare is quite specialized for collaborative investigation of a single, messy leak. Aleph is more focussed on connecting the dots once you already have some idea of what you've got. Didn't do enough testing yet to judge the technical side yet. 

As for [The Guardian's Giant](https://github.com/guardian/giant), I don't really see yet how it stands out..

**Comment by pudo** [comment]
Wow I didn't know Guardian had made Giant public. That's amazing news. What I think is special about it is a) good engineering, b) making it super simple to browse directory structures. You might laugh at that as a killer feature, but it's often what leak work focusses about. Aleph does a good (but not fantastic) job at it, while Datashare IMO is held back a bit by Apache Tika and really struggles with file hierarchies.

Between Aleph and Datashare, one thing I'd point out is that Aleph has support for importing and analysing structured data: company or voter registries, procurement data, bank transactions etc. Datashare doesn't do that at all, but you could work around it by combining Datashare with project-specific instances of Datasette (which is proving really cool for more and more investigations).

**Comment by ninoppp** [comment]
Oh well doesn't seem like a lot of people know.
![image](https://user-images.githubusercontent.com/101364396/160101243-b8d249a1-f894-44e9-b8b4-39b454b90841.png)

Do I see it correctly, that all of the three have more or less the same data analyzing/entity linking/file format extraction capabilities?

**Comment by pudo** [comment]
With regards to documents, Datashare and Giant both use Tika, so they're equivalent. Aleph uses it's own tech, which allows us to use document data and generate semantic networks from it (e.g. a graph of email communications). The long and short of it: if you just want to take a bunch of documents and search for words, they'll all do it. How they let you analyse and interact is where the differences start.

**Comment by ninoppp** [comment]
Hmm okayy... I guess so it's just fuck around and find out or is there a comparison somewhere I can take a look at?
Also, I'm taking from your messages that you would recommend Giant over Datashare?

**Comment by ninoppp** [comment]
I'm aware of that and weighing your opinion as such :)
And your absolutely right, if the comparison doesn't exist I should probably make it myself.

**Comment by Rosencrantz** [comment]
@ninoppp Going to close this ticket as it seems as though this conversation has come to an end.
