### ISSUE TITLE
WARNING:alephclient.util:Error: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

### ISSUE THREAD

**Issue by PitaHat** [alephdata/aleph#2198]
Hi there,

When trying to crawldir that includes larger files (large - ~30gb - MBOX files for instance) I get the following error:

`WARNING:alephclient.util:Error: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')), back-off: 2.43s`

This error gets repeated multiple times. Sometimes the file does get through, but often it get stuck in this loop. The issue is clearly related to keeping constant connection. I'm running everything on a local server, so not sure how I fix this. Would increasing the number of ingest-file etc workers fix the issue? Please advise.

**Comment by PitaHat** [comment]
I'm using the default configuration - NGINX allowed to handle uploads of unlimited size. Nothing seems to improve the situation.

**Comment by PitaHat** [comment]
Ok here is an interesting thing in the logs, which occurs when i get the error. How to avoid having a worker timeout?

```
api_1               | [2022-04-22 10:13:14 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:211)
postgres_1          | 2022-04-22 10:13:16.273 UTC [121] LOG:  unexpected EOF on client connection with an open transaction
api_1               | [2022-04-22 10:13:16 +0000] [1] [WARNING] Worker with pid 211 was terminated due to signal 9
api_1               | [2022-04-22 10:13:16 +0000] [243] [INFO] Booting worker with pid: 243
```

**Comment by sunu** [comment]
Ah, right, you can add `--timeout 3600` in the gunicorn command in the docker-compose file. Could you please make a PR with it as well if that fixes the issue?

**Comment by PitaHat** [comment]
Issue fixed with the flag - many thanks!. Submitted a PR.
