### ISSUE TITLE
Show snippet for 'document' text in search results

### ISSUE THREAD

**Issue by HeleenE** [alephdata/aleph#2200]
The search results in Aleph show a snippet when the search term is found in a text property of an entity, it would be nice if we could expand this behaviour to also show snippets when the term is found in the text of a document.

**Comment by anderser** [comment]
I suppose this might be related to this other issue about highlighting not working (or being inconsistent): https://github.com/alephdata/aleph/issues/2138

**Comment by Rosencrantz** [comment]
Hey @HeleenE As @anderser points out it does seem to be related to #2138, I think that it's close enough that I am going to shut this down as a duplicate.
