### ISSUE TITLE
Xref status

### ISSUE THREAD

**Issue by rhiaro** [alephdata/aleph#221]
An api endpoint to indicate when an xref was last run and if it's currently ongoing/done would be useful.

**Comment by pudo** [comment]
This would be pretty hard to actually determine: all you have is the number of entities to be cross-referenced and the status of the queue you are using to cross-reference them. There [seems to be some introspection facility](https://stackoverflow.com/questions/5544629/retrieve-list-of-tasks-in-a-queue-in-celery), but it's not exactly a clean thing to do.

**Comment by pudo** [comment]
Still can't figure out how to do this. Gonna mark "wontfix" for now.
