### ISSUE TITLE
When using OAuth, adding an existing user to `ALEPH_ADMINS` doesn't elevate them to admin

### ISSUE THREAD

**Issue by sunu** [alephdata/aleph#2211]
`handle_oauth` and `Role.by_foreign_id` doesn't check `ALEPH_ADMINS` while loading a role: https://github.com/alephdata/aleph/blob/5663e30d9138c2ff3137caf40a9afbdca896223d/aleph/oauth.py#L88

**Comment by msmych** [comment]
Hi, please check if this makes sense https://github.com/alephdata/aleph/pull/2246

btw is there plan to introduce unit tests for BE? Might help designing APIs, catch bugs early, have more use cases in code. Also unit tests are fast to run so it's easy to run those continously while updating code.

**Comment by sunu** [comment]
Thanks @msmych, we would appreciate any contribution adding more tests for sure. We do have a few unit tests style tests but a majority of our tests tend to be integration tests. And more unit tests would be great!

**Comment by msmych** [comment]
Hey @sunu could you review this minor fix:

https://github.com/alephdata/aleph/pull/2273/

not related to the issue above, but rather the discussion about unit tests. I added tests to the existing `test_view_util.py` and it works fine but requires full setup, would be much better having a separate lightweight `make unit-test` command. I think can be implemented as a part of https://github.com/alephdata/aleph/issues/2176

**Comment by sunu** [comment]
Hey @msmych, thanks a lot for the PR. Unfortunately I haven't had the time to look at it yet. Will do so as soon as I can get some time.
Re #2176, I have done the bare minimum work needed to run the tests with pytest as part of #2199. We can definitely add an additional command to run unit tests only.
