### ISSUE TITLE
Create a release on GitHub for new versions of Aleph

### ISSUE THREAD

**Issue by siccovansas** [alephdata/aleph#2213]
It would be awesome if new versions of Aleph are published as a [release](https://github.com/alephdata/aleph/releases) on GitHub. Currently the latest versions are already [tagged](https://github.com/alephdata/aleph/tags), but a release would make it possible for other users of Aleph to use GitHub's 'Watch' feature to be notified when a new release is available and update their installation (AFAIK there is currently no way to be easily notified of new Aleph versions e.g. via an RSS feed or announce newsletter/mailing list).

**Comment by pudo** [comment]
We currently tag releases using `bump2version`, which handles increasing the version numbers in various places of the code base. I'm not entirely sure how we'd automate things beyond that, perhaps that where we'd head into `auto` territory? 

* https://jwodder.github.io/kbits/posts/auto-bump2version/ 
* https://github.com/intuit/auto 

Do you have a proposal for how best to do this?

**Comment by siccovansas** [comment]
Hi @pudo, thanks for you quick reply!

I'm not familiar with those tools, but `auto` seems like a possible solution indeed. On the other hand it might be easier to manually create a release when a new Aleph version is available.

**Comment by sunu** [comment]
@siccovansas If you're interested in an rss feed, github tags do have one. eg: https://github.com/alephdata/aleph/tags.atom

**Comment by Rosencrantz** [comment]
@siccovansas Just throwing an additional piece of information in here... It's not automated, its not built into github and it may not be exactly what you are looking for, but we do have the @alephdata twitter account that we use predominately to communicate new releases

**Comment by Rosencrantz** [comment]
@pudo @sunu This seems like a simple process with very little overhead for us. It also has the advantage of auto generating release notes. I've just created a release for 3.12.2, lets try this over the next few releases and see if it proves valuable. I will creating a ticket for us to update documentation to include this step when doing a release.

@siccovansas Thanks for highlighting this. I'm going to close this ticket out and create another to update our documentation.
