### ISSUE TITLE
new user not authorized?

### ISSUE THREAD

**Issue by RMHogervorst** [alephdata/aleph#2225]
I run aleph in a kubernetes cluster.
I created a user in the shell.
this user is also visible in the postgres database.
When I log in with a wrong password I get  a prompt that the user or password is wrong (So far so good)
When I log in with the right password I get a 403 uncaught exception.

specifically, (according to chrome developertools), there is a request to  /api/2/role/4 with result a json: `{"status","error","message":"You are not authorized to do this.", "roles":[1]}`
The other request is to /api/2/alerts?limit=9999

**Comment by RMHogervorst** [comment]
I see no rows in permissions, no rows in role_membership

Did I create a user without permissions?

**Comment by RMHogervorst** [comment]
oh wait it does say somewhere I should run aleph upgrade from shell too!

**Comment by RMHogervorst** [comment]
upgrade does not fix the problem

**Comment by sunu** [comment]
Can you check whether Aleph is sending an authrization token in the request header for the request to `api/2/roles/4`? From the error message it looks to me like Aleph is treating you like an anonymous user.

**Comment by RMHogervorst** [comment]
I think this is enough for me to get on track, I will get back when I found a solution, thanks for the help!

**Comment by Rosencrantz** [comment]
@RMHogervorst Do you have an update on this issue. Did you manage to find a solution?

**Comment by RMHogervorst** [comment]
I havent solved it yet but it seems the forwarding didnt work as expected

**Comment by RMHogervorst** [comment]
So the requests were stripped of the auth header

**Comment by Rosencrantz** [comment]
@RMHogervorst This ticket has been very quiet. Were you ever able to resolve this issue?

**Comment by RMHogervorst** [comment]
To be honest I gave up
