### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by infojunkie** [alephdata/aleph#226]
Hello,

I'm trying to spin up the Docker environment as per https://aleph.readthedocs.io/en/latest/installation.html#development-installation-steps but I am unable to get to the web front-end. I ran `make web` which is not documented afaict, and here's what `docker ps` tells me:

```
kratib@neoluddite:~/src/meedan/aleph$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                NAMES
2fbd1e59745b        aleph_app             "/aleph/contrib/de..."   32 seconds ago      Up 32 seconds       0.0.0.0:5000->5000/tcp, 8000/tcp     aleph_app_run_1
ddc5c35e15cb        postgres:9.4          "docker-entrypoint..."   27 minutes ago      Up 27 minutes       5432/tcp                             aleph_postgres_1
e8e58ffef9e2        elasticsearch:5.4     "/docker-entrypoin..."   27 minutes ago      Up 27 minutes       9200/tcp, 9300/tcp                   aleph_elasticsearch_1
23c1a1d8a358        rabbitmq              "docker-entrypoint..."   27 minutes ago      Up 27 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   aleph_rabbitmq_1
```

But then, when I visit http://localhost:5000, I just see
```
{"status": "error", "message": "This path does not exist."}
```

Also, the documented URL http://lvh.me:13376 does not seem to exist on my local.

Help please!

**Comment by pudo** [comment]
Thanks for this feedback, Karim. 

* ``make web`` - we need to document that.
* Same with updating the docs wrt. :13376

But, here's the weird part: from what I can tell you have a working aleph2 install. It just doesn't have a UI. The API is mounted at ``/api/2``. You can either travel over to aleph-ui and point that against your install, but it's still super basic. Or you can check out the ``stable`` branch, which has the old Angular1 UI going as a monolith.

Of course, before aleph 2 is born, we'll want to make the UI build as part of the docker env, but for now there's just too little of it around.

**Comment by infojunkie** [comment]
Thanks. And just to make sure I understand, the API full address would be http://localhost:5000/api/2 ? This also gives me 404.

Feel free to close this if there's nothing mroe to be done until UI v2 exists.

**Comment by pudo** [comment]
Try http://localhost:5000/api/2/metadata, or http://localhost:5000/api/2/search. 

I'm leaving this open to cover the two docs issues. @rhiaro how about it?

**Comment by infojunkie** [comment]
Got stuff for http://localhost:5000/api/2/metadata - thanks!
