### ISSUE TITLE
CI workflows failing due to `countrynames` being incompatible with Python 3.8

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/aleph#2340]
* Our GitHub Actions builds are currently failing.
* It seems they are being run with Python 3.8 (because we’re not specifying anything explicitly).
* The `countrynames` package now uses `cache` instead of `lru_cache`, which was introduced only in Python 3.9.
 
* [Example](https://github.com/alephdata/aleph/runs/6928735739) of a GH Actions run failing
* [Relevant `countrynames` commit](https://github.com/alephdata/countrynames/commit/4cd5907b39febb0de2d0668a9fde6a3056cca65f)

**Comment by sunu** [comment]
This should be fixed now by https://github.com/alephdata/countrynames/pull/34
