### ISSUE TITLE
BUG: 500 response if limit is set to zero

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/aleph#2370]
**Describe the bug**
#2361 implemented a change that returns an error response if the total number of results is larger than zero, but the list of results is empty.

There is however a legitimate situation where such a response is expected. When an API consumer explicitly sets `limit=0`. Aleph’s PDF viewer [does that](https://cs.github.com/alephdata/aleph/blob/bf63ad80b7a7f2b593f9ebfab610645d87f8ad80/ui/src/viewers/PdfViewer.jsx#L255) in order to get the total number of pages without actually requesting any pages.

**To Reproduce**
1. Create an investigation.
2. Upload a document.
3. Click on "Documents" in the sidebar.
4. Open the network tab in browser dev tools-
5. Click on the document. You should see an infinite loading spinner.
6. You should be able to see a request to the `entities` endpoint with `limit=0`.

**Expected behavior**
The API should not return an error response in this case as an empty list of results is actually expected.

**Comment by tillprochaska** [comment]
I can think of another similar situation: If a query has 100 results and an API consumer sends a request with e.g. `offset=200`, that would also return an empty list of results.

**Comment by sunu** [comment]
So we have 2 legitimate cases where empty results should be allowed with a non-zero total - when `limit==0` and when `offset>=total`. I can introduce those checks.

**Comment by tillprochaska** [comment]
@sunu, yes, there might be more cases though (but I couldn’t think of any other so far).

**Comment by Rosencrantz** [comment]
@Rosencrantz Can you verify whether this issue is now resolved
