### ISSUE TITLE
BUG: Skeleton in table previews displayed after loading has finished

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/aleph#2377]
**Describe the bug**
When displaying a table with only a few rows, skeletons are still displayed even after the data has been loaded.

**To Reproduce**
1. Create a new investigation.
2. Upload a table document with less than 4 rows (see example CSV file).
3. Wait until Aleph has processed the document.
2. Go to the "Documents" section in the investigation.
3. Open the table document.
4. Skeletons are displayed in the first 4 rows (if they aren’t replaced by rows of the table document).

**Expected behavior**
After the table data has been loaded, skeletons shouldn’t be displayed anymore.

**Screenshots**

https://user-images.githubusercontent.com/1512805/177121034-e8411af7-42f6-4f9e-9d31-a51e1d52e5df.mov

**Additional context**
* [Example CSV file](https://github.com/alephdata/aleph/files/9038000/example_table.csv) that can be used to reproduce the bug

**Comment by pudo** [comment]
Hahaha that looks like a cleanly implemented bug. I guess it's meant to describe the header row?

**Comment by tillprochaska** [comment]
Thanks, that makes sense!
