### ISSUE TITLE
BUG: Dropdown resets to top on UI refresh during re-index

### ISSUE THREAD

**Issue by monneyboi** [alephdata/aleph#2415]
When i'm trying to add an entity type that's not yet in the list in an investigation, but whenever i scroll down, the dropdown keeps resetting to the top.

![image](https://user-images.githubusercontent.com/86304937/180790089-81941abd-e590-4ff5-8d6d-e6673dabda8e.png)

I think this happens because the investigation is being indexed, causing the UI to be refreshed every ~5? seconds, causing the dropdown to reset to the top.

**Comment by tillprochaska** [comment]
> I think this happens because the investigation is being indexed, causing the UI to be refreshed every ~5? seconds, causing the dropdown to reset to the top.

Yes! Blueprint’s `Select2` component will try to scroll the active option into view every time the component rerenders. If no option is selected, it tries to scroll the first option into view. Setting the `scrollToActiveItem` property to `false` solves this.

https://blueprintjs.com/docs/#select/select2

**Comment by Rosencrantz** [comment]
@tillprochaska Fixed this, should be available in our next release.
