### ISSUE TITLE
BUG: Aleph document viewer multiplies the total number of document pages by 2

### ISSUE THREAD

**Issue by brrttwrks** [alephdata/aleph#2424]
**Describe the bug**
The document viewer appears to be multiplying the total number of document pages by 2. The result is when you paginate after the middle page (the actual final page) Aleph returns a page not found error.

**To Reproduce**
1. Go to: https://aleph.occrp.org/entities/2142622.9080b676ec7fc6f56d7b6a9efdf2f2efc1ecf184#page=69
2. Paginate to the next page, you'll get an error. This next page, 70, is one page more than the middle page of the total (138).
3. Download the document and open it in a PDF viewer and you'll see that the actual total pages is 69.

Ex 2:
1. Go to: 

The ingestor appears to be broken:
1. Aleph viewer shows that Aleph tries to process the doc, but then fails, yet creates the document entity object:
2. Go to page: https://aleph.occrp.org/entities/2142622.9080b676ec7fc6f56d7b6a9efdf2f2efc1ecf184#page=69
3. See error:
```
No preview is available for this document
Could not extract PDF file: OSError('Error opening file: /tmp/ingestor-rwoma32t/c14e5b88770eae7b1037a79bf9d5d0b98d8a95eb.sl/RCS9_Product_Training_v1.pdf')
```

These errors are in the dataset: https://aleph.occrp.org/datasets/182

**Expected behavior**
The expected behavior is that the viewer only show and request pages that are actually there :)

**Screenshots**
Not applicable. 

**Additional context**

**Comment by tillprochaska** [comment]
@sunu This seems to be a cache issue. For example 1, the API returns a total number of 138 page entities ([request](https://aleph.occrp.org/api/2/entities?filter%3Aproperties.document=2142622.9080b676ec7fc6f56d7b6a9efdf2f2efc1ecf184&filter%3Aschema=Page&limit=0&offset=0&q=)).

**Comment by tillprochaska** [comment]
> Aleph viewer shows that Aleph tries to process the doc, but then fails, yet creates the document entity object:
> Go to page: https://aleph.occrp.org/entities/2142622.9080b676ec7fc6f56d7b6a9efdf2f2efc1ecf184#page=69

@brrttwrks Did you mean to link to another document or page here? I can’t see that error message ("Could not extract PDF file").

**Comment by tillprochaska** [comment]
@brrttwrks Has this issue ever occurred in other datasets since Nov last year?

**Comment by brrttwrks** [comment]
I have not encountered that error in a good while, but haven't actively sought it out either.

**Comment by Rosencrantz** [comment]
@brrttwrks Going to optimistically close this in the hope that it is resolved. If it comes up again, please let me know.
