### ISSUE TITLE
FEATURE: Use an global object with a constructor for Flask settings intead of the module `settings.py`

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#2435]
**Is your feature request related to a problem? Please describe.**

I cannot set arbitrary environment variables and in particular I need to set `SQLALCHEMY_POOL_RECYCLE`.

**Describe the solution you'd like**

The module `settings.py` should not be the object that is used to configure the flask app. It should (ideally) be injected as parameter and passed around to `create_app` and `create_view` functions, but as less invasive method, having a global object like this in `settings.py` will be minimal refactoring.

```python
# in settings.py

class Settings:
    def __init__(self) -> None:
        self.SOME_VAR = env.get("ALEPH_SOME_VAR")
        
        other_var = env.get("ALEPH_OTHER_VAR")
        if other_var is not None:
            self.OTHER_VAR = other_var

        # etc.

SETTINGS = Settings()

# in core.py
def create_app(config={}):
    configure_logging(level=logging.DEBUG)
    app = Flask("aleph")
    app.config.from_object(settings.SETTINGS)
```

**Describe alternatives you've considered**

In theory all this logic could be done in the module itself, but I've been doing flask development for a decade, and I genuinely think that many of the patterns in the flask docs are weird and obtuse, especially in large production applications.

Not that a single loop over all `ALEPH_*` env vars would not be enough as it seems that the aleph devs want to be able to set some defaults and also some flask extensions don't coerce strings to ints so this would have to be handled by known cases.

In some applications I've worked on in the past, we'd treated all env vars as JSON and then we could loop over them more efficiently and arbitrarily and doing a `json.loads(env_var)`. This would be a breaking change (maybe) depending on how the helm charts are constructed.

**Comment by brassy-endomorph** [comment]
This is extremely important to me because our Aleph instance is basically useless since I can't set the SqlA config values I need to make it work and I'm really not trying to monkey patch or self host containers with a diff applied to allow for this.

Could the team respond to this? I can make the PR but I really don't want to put the work in only to have it hang in pending indefinitely.

**Comment by Rosencrantz** [comment]
Marking this as closed now that it is scheduled for deployment and release
