### ISSUE TITLE
FEATURE: Improved documentation of app config env vars

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#2438]
**Is your feature request related to a problem? Please describe.**

As an aleph admin, I don't want to have to look through source code to figure out how to configure my aleph instance.

**Describe the solution you'd like**

Full documentation of every env var that can be set to change the behavior of the app (excluding vars like `LC_*`).

E.g., 

| **Name** | **Flask Equivalent** | **Required** | **Default** | **Explanation** |
|---|---|---|---|---|
| `ALEPH_DATABASE_URI` | `SQLALCHEMY_DATABASE_URI` | yes |  | The connection string to the Postgres database |
| `ALEPH_APP_TITLE` |  | no | Aleph | The name of the app in the UI |

Relates to #2437

**Comment by brassy-endomorph** [comment]
This was the direct cause of #2428

**Comment by tillprochaska** [comment]
The new technical documentation now contains a [reference of the configuration options](https://docs.aleph.occrp.org/developers/reference/configuration-options/) as well as [How-to guides](https://docs.aleph.occrp.org/developers/how-to/operations/) on how to configure certain Aleph features.
