### ISSUE TITLE
BUG: Local server instance: Alephdata website disappears after login with ipad

### ISSUE THREAD

**Issue by Physik310** [alephdata/aleph#2447]
**Describe the bug**
I have setup my own alephdata instance and encountered the following issue. I can remotely access the login page and login with a previously created user. With a Windows Laptop I can normally browse the site after login, create an investigation and upload documents, etc.  The same is also for a laptop with a Linux Debian OS. When I login with an Ipad, I see how the website loads for the page /notifications and builds up and I can briefly see the website but then it immediately disappears and I only see a blank site. If I type in the subpage /investications, which doesn't exist, the website loads normally and shows an error message that the site doesn't exist. If I manually type in the subpage /investigations, the site also loads normally and I can see the available investigations. If I click on on investigations, the same issue happens. The site loads and then disappears to a blank page. If I go back to the /investigations subpage and click on notifications to open the subpage /notifications, the same issue happens again. I have tried multiple browsers (Safari, Chrome, duckduckgo). What do the notifications subpage and an investigation's page have in common that this issue happens on these sites? Might this be related to elasticsearch? (The same happened when I used the browser midori on a debian system.)

**To Reproduce**
1. Login to a local server instance with an Ipad
2. The webpage loads and disappears to a blank site immediately after.

**Expected behavior**
The website should not disappear to a blank site after logging in with an Ipad.

**Comment by tillprochaska** [comment]
Hi @Physik310, thanks for reporting this bug. A fix will be available in the next release of Aleph (see #2488).
