### ISSUE TITLE
How does it extract email, phone number, name, etc?

### ISSUE THREAD

**Issue by rider8581** [alephdata/aleph#2448]
Hello there!
Thank you for your contribution.
I have been using this project to analyze some of my data and it works amazing.
The most attracting is the fact that it can parse my documents and extract the some meaningful information including email, phone number, etc.
I wanna this feature for some of my other project to parse the text and extract those information.
Are there any module or sub project for this which I can use for this extraction?
Kindly let me know.
Thank you!

**Comment by Rosencrantz** [comment]
Hi @rider8581 

Thanks for taking the time to reach out. Most of the work that we've done to extract content from documents exists in our ingest-file library. You might be able to use this in your own projects.

https://github.com/alephdata/ingest-file

Kind regards
