### ISSUE TITLE
BUG: Documentation in Aleph for Memorious is not up to date

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#2458]
**Describe the bug**
I’ve been using your Memorious project to create and run crawlers. I see in the documentation page linked below that there is meant to be a user interface for managing all the running crawlers, but I cannot find this anywhere when running Memorious myself. Is this still a feature and I’m failing to find it, or has it been removed?
 
[https://docs.alephdata.org/developers/memorious#memorious-management-interface](https://www.google.com/url?q=https://docs.alephdata.org/developers/memorious%23memorious-management-interface&source=gmail-imap&ust=1660657374000000&usg=AOvVaw2hNw0fWkTJu355-5gGLQVh)

**To Reproduce**
Click the link above

**Expected behavior**
No mention of Memorious UI

**Additional context**

**Comment by tillprochaska** [comment]
This is no obsolete as I’ve removed the section about Memorious from the tech docs in favor of the stand-alone Memorious docs (which do not reference the UI anymore).

https://github.com/alephdata/aleph/pull/3569
