### ISSUE TITLE
Fetching more than 10000 results

### ISSUE THREAD

**Issue by sargisaleksanyan** [alephdata/aleph#246]
Hi . I am having trouble of getting more then 10 000 documents .For example when I make request to this api https://data.occrp.org/api/1/entities?facet=countries&facet=schemata&facet=dataset&facet=collections&filter:dataset=cy_companies&limit=1000&offset=9500  it returns 500 error with the following message {   "status": "error",   "message": "Result window is too large, from + size must be less than or equal to: [10000] but was [10500]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting." }

**Comment by pudo** [comment]
Yes, that's a limit of the backend we're using, ElasticSearch. If you're trying to download the whole Cyprus dataset, I'll trade you the raw CSV files for an interesting Armenian set -- companies?

**Comment by sargisaleksanyan** [comment]
thank you for your email. In fact, we can download Cyprus registry from the original source, we simply wanted to see if we could have "shortcuts" since 99% of what we have seen your website was publicly available data.  Also, we simply assumed your organization  being a publicly funded one would rather go for open data provision, sharing anything from us being only an optional thing and not a condition. Anyway thank you for your time and in case you think you can provide the CSV without swap agreements we will be most happy to receive, if not, we anyway wish you the best of luck.

**Comment by pudo** [comment]
We're always happy to provide data to other public interest projects, but it does entail a bit of work to do bulk exports. We hope to provide self-serve exports at some point, but haven't gotten around to building that our yet. Since I have no idea of what your agenda is, I don't really have an incentive to do free work for you, it would be an abuse of our funding. Good luck.
