### ISSUE TITLE
BUG: No such command 'import-ocds'

### ISSUE THREAD

**Issue by agarofalo-larus** [alephdata/aleph#2480]
**Describe the bug**
I've found [here](https://docs.alephdata.org/developers/followthemoney/ftm#importing-open-contracting-data) on the documentation the command `ftm import-ocds` to import Open Contracting Data Standard (OCDS), but the command seems it doesn't exist anymore.

**To Reproduce**
1. Launch the `ftm import-ocds` command and you will obtain a _No such command 'import-ocds'_ error
2. Launch `ftm --help` the command `import-ocds` is not present in the list of the available commands

**Expected behavior**
Have the `ftm import-ocds` available in the ftm tool

**Screenshots**
![image](https://user-images.githubusercontent.com/60467115/186159946-3b8dc930-9542-4837-8989-5c929d6bc568.png)
![image](https://user-images.githubusercontent.com/60467115/186160129-3b06d0c7-c306-43b0-903a-8fbb97d2c62b.png)

**Additional context**
-/-

**Comment by agarofalo-larus** [comment]
OK, thank you so much, but what part of the documentation does this mention?

**Comment by agarofalo-larus** [comment]
OK, thank you so much, but where in the documentation is this mentioned?

**Comment by pudo** [comment]
In the new section you're about to write?

**Comment by agarofalo-larus** [comment]
I'm just asking where this information is in the documentation because I haven't found it. I wouldn’t want it to be my fault.

**Comment by tillprochaska** [comment]
Updated the docs in https://github.com/alephdata/docs/pull/20.
