### ISSUE TITLE
BUG: Convert-Document crashes the server

### ISSUE THREAD

**Issue by PitaHat** [alephdata/aleph#2504]
**Describe the bug**
A server running Aleph crashes when converting a large number of non-pdf files (docx, etc).

The server is quite beefy and the crash occurs notwithstanding how many convert-document services are running. 

Based on running processes, when converter is engaged, I get a `soffice.bin` process running at 100 percent capacity. The converter does not time out always remains engaged.

Meanwhile, on the aleph logs I get this:

```
ingest-file_3       | 2022-09-07 16:15:11.092337 [debug    ] Converting [xxxxxxxx01.01.2022.docx] to PDF (attempt 77)... [ingestors.support.convert] 

ingest-file_1       | 2022-09-07 16:15:11.092365 [debug    ] Converting [yyyyyyyyyyyyyyyyyy..docx] to PDF (attempt 80)... [ingestors.support.convert] 
```

Additionally, I get this in the logs:

`ingest-file_3       | 2022-09-07 16:15:08.991342 [info     ] Converter not available: 503 Server Error: SERVICE UNAVAILABLE for url: http://172.19.0.2:3000/convert?timeout=7200 (attempt: 73) [ingestors.support.convert] `

One temporary fix this is to kill the LibreOffice process, but the issue comes back in the next 20 mins.

Are there any fixes to this? I'm running basically a default Docker config on Aleph.

**Comment by Rosencrantz** [comment]
Hi @PitaHat this might be related to Redis running out of memory for tasks, can you see the whether the Redis node goes down when you try to ingest a huge number of files?

**Comment by Rosencrantz** [comment]
Hi @PitaHat 

Are you able to provide us with an example document that you know causes this issue to occur? It'd help us determine the root cause of the issue.

**Comment by Rosencrantz** [comment]
@PitaHat We've now removed convert-document from Aleph. This feature has been incorporated into the ingest-file lib.
