### ISSUE TITLE
Update pyahocorasick to latest version

### ISSUE THREAD

**Issue by pombredanne** [alephdata/aleph#251]
We pushed a 1.1.6 recently, FYI

**Comment by pudo** [comment]
Damn, that's what I call full-service library maintainership :) Thanks!

**Comment by pombredanne** [comment]
@pudo :D For all your know, I could be a smart bot powered by a CNN ;)
More seriously I stumbled on your code that I found quite cool, and even cooler that it use pyahocorasick, checked your reqs, and found them outdated ;)

**Comment by pombredanne** [comment]
That being said, that makes me think of possible great automated service to authors :)

**Comment by pombredanne** [comment]
I will likely use some of your wares, such as fingerprints, to help with copyright holder normalization in another project of mine, https://github.com/nexB/scancode-toolkit

**Comment by pudo** [comment]
Oh, that looks like a super neat use case for it, too. Make sure to install pyICU if you do, to enable better non-latin support...

**Comment by pombredanne** [comment]
@pudo Thank you!

**Comment by pombredanne** [comment]
though I might not need pyICU because I think I transliterate during my detection AFAIRC... I'll need to dig and see.

**Comment by pombredanne** [comment]
and software code copyright tend to be spread on much fewer locales than tax haven ;)
