### ISSUE TITLE
BUG: healthz endpoint not working in the UI

### ISSUE THREAD

**Issue by lyz-code** [alephdata/aleph#2519]
**Describe the bug**
We're trying to monitor the health of the application but the `/healthz` endpoint is not working.

**To Reproduce**
1. Go to https://your-aleph.com/healthz
4. See error "The requested page could not be found."

**Expected behavior**
We'd like to see some data to monitor if the application is working correctly

**Additional context**
I tried the `/healthz` endpoint as it was discussed on https://github.com/alephdata/aleph/issues/483, and I saw that the helm chart is using it for the readiness probe

**Comment by tillprochaska** [comment]
Hi @lyz-code! As Aleph is a single-page applicaion rendered on the client, the error you see is a "soft" error, i.e. the HTTP status code returned for `/healthz` is `200 OK`.

That means that the `/healthz` endpoint can indeed be used for automated monitoring of the UI service.

If you’re looking for a UI that displays information about Aleph’s system status, we actually do have a UI that displays information about tasks processing at `/status`.

> We'd like to see some data to monitor if the application is working correctly

If you’d like to request a user interface to display other monitoring information, please open a feature request issue and include detailed information about the information you need as well as well as the use case. Thanks!

**Comment by lyz-code** [comment]
Hi @tillprochaska, thank you for answering so quick. I thought that the `/healthz` endpoint not only checked that the UI is up, but also that the connection with the rest of the components is working.

If the UI is working, both `/` and `/healthz` gives a 200, if it's not both give a 502, so to monitor if the UI is working, we could use any of them.

I opened the issue because it happened to us that the UI was working but the API wasn't or the connection with the Elasticsearch was broken. As the UI was still returning a 200, the issue went unnoticed by us until the users told us about it. We wanted to make sure that this doesn't happen again.

Is there any endpoint that we can use from an unauthenticated monitoring tool to see if the connection with the API and the underlying databases are working? Or is the only way to create alerts based on the logs?

Thanks again :)

**Comment by tillprochaska** [comment]
Hi @lyz-code, as far as I know, there’s no single endpoint that can be used for that. The API has a [`healthz` endpoint](https://github.com/alephdata/aleph/blob/main/aleph/views/base_api.py#L171) that can be used to monitor that the API service is responsive, but it won’t check that it can connect to ElasticSearch and Postgres.

cc @sunu

**Comment by lyz-code** [comment]
Hi @tillprochaska we're trying to access the `/heathz` endpoint of the API through the UI with no success. We've seen that the UI does call the API on the endpoints `https://our_domain.org/api/2/...` so we've tried the next endpoints:

* https://our_domain.org/api/2/healthz
* https://our_domain.org/api/healthz

But both return a `{"status": "error", "message": "This path does not exist."}` json answer. Is the endpoint exposed through the UI or it's only available if you request the `/healthz` directly to the API docker?

I guess that the check to the databases could be done by enhacing the `/healthz` endpoint you showed me. Once we find how to query the endpoint from the outside we can change the issue description to Enhacement if you want

**Comment by tillprochaska** [comment]
Hi @lyz-code, the endpoint is `/healthz` (not `/api` or `/api/2/healthz`), but if you’re using the default Docker setup, nginx is only configured to forward requests under the `/api` path to the api service, i.e. you won’t be able to access that endpoint via the UI. As a workaround, you might be able to use another endpoint that doesn’t require authentication and is publicly accessible, for example `/api/2/statistics`.

**Comment by lyz-code** [comment]
Awesome, that endpoint works for us :) thank you!
