### ISSUE TITLE
FEATURE: Make collection_id filter accept multiple values on entities search endpoint

### ISSUE THREAD

**Issue by thimios** [alephdata/aleph#2521]
**Problem Description**
We keep multiple datasets in our Aleph instance and we need to query the entities API in order to search in a subset of the available datasets. 

**Proposed solution**
[The search entities API endpoint](https://redocly.github.io/redoc/?url=https://aleph.occrp.org/api/openapi.json#tag/Entity/paths/~1api~12~1entities/get
) currently accepts a collection_id filter. It would be great if that could be a collection_ids array of multiple dataset ids.

**Alternatives we have considered**
Of course we could just make multiple requests, one for each collection_id that we need to search in and afterwards merge the results, but it would be much more efficient to just make one API request with a collection_ids array filter.

We could also create different users each of whom would have access only to a subset of the available datasets and each time use a different API key depending on the subset we need to query. This would make our implementation more complex but would be an efficient solution.

**Comment by tillprochaska** [comment]
Hi @thimios, I think you can pass the `filter:collection_id` multiple times to get results from multiple collections.
