### ISSUE TITLE
BUG: Overflow issue on document view

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#2554]
**Describe the bug**
If you have a document name which is long without breaks it can overflow it's contain producing a poor looking interface

**To Reproduce**
1. go to an investigation
2. upload a document with a very long title and no spaces
3. wait
4. click to view document and observe broken UI

<img width="1440" alt="Screen Shot 2022-10-06 at 9 01 58 am" src="https://user-images.githubusercontent.com/340405/194236426-6dd7e981-7e22-4b8f-b864-fb6748f9952d.png">

**Comment by tillprochaska** [comment]
Additional context: This only happens when the document title has a transliteration available, as that will wrap the title in an inline-block element.

**Comment by tillprochaska** [comment]
Closed in #2570
