### ISSUE TITLE
Document viewer UI

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#256]
This is a fairly large ticket for implementing the main document viewer in Aleph 2. It includes:

* A sidebar showing common document metadata, such as title, source collection, source URL, dates, etc.
* A body section which differentiates the types of Documents we have. 
* A headers section for E-Mail metadata

Sub-viewers are required for:

- [ ] Plain Text (or email bodies)
- [ ] HTML documents (or email bodies)
- [ ] Folders (which may also be attachments on an email) 
- [ ] Tables (see http://blueprintjs.com/docs/#table-js)
- [ ] PDF Viewer (see also #108 about whether this should render PNGs of pages)
- [ ] possibly: Images

**Comment by pudo** [comment]
Edin's latest mockup: 

![search results 06 entity](https://user-images.githubusercontent.com/41628/33935444-3c456d32-dffc-11e7-9e75-b857c06a2948.png)

Also: 

![search - entity v8](https://user-images.githubusercontent.com/41628/33935461-4c08d7e0-dffc-11e7-8b73-713abf2fc121.png)

**Comment by villewilson** [comment]
Today's versions with breadcrumbs/navigation bar positioned on top and screens separated

![search - document v9](https://user-images.githubusercontent.com/34656275/34115976-5edabb76-e417-11e7-83a2-97ffd68d7c9c.jpg)

![document details](https://user-images.githubusercontent.com/34656275/34115984-664e0be2-e417-11e7-9e6b-75a302a3c2f0.jpg)

**Comment by pudo** [comment]
Currently, the document route does not seem to load if called directly without the apiCache already warmed up.

**Comment by benoccrp** [comment]
All of them have room for improvement, but the basics are done. Closing this.
