### ISSUE TITLE
Entity viewer UI

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#257]
Similar to document viewer, two main components:

* Sidebar with entity attributes, like name, countries, address, phone etc.
* Main bar with linked entities, and documents / similar entities section.

**Comment by pudo** [comment]
Edin's best:

![search results 06 entity](https://user-images.githubusercontent.com/41628/33935567-b2baca16-dffc-11e7-8f51-a9bb5d54af2c.png)

![search - entity v8](https://user-images.githubusercontent.com/41628/33935572-b882a8c4-dffc-11e7-845b-d578045ea600.png)

**Comment by villewilson** [comment]
Today's versions, with breadcrumbs/navigation bar on top.
![search - entity v9](https://user-images.githubusercontent.com/34656275/34115908-2aa38e46-e417-11e7-83b5-be8ca151b1dc.jpg)

![entity details](https://user-images.githubusercontent.com/34656275/34115938-3c9136bc-e417-11e7-9e11-f2d44122a465.jpg)

**Comment by benoccrp** [comment]
Basics have been implemented, additions could be addressed in new issues; closing this.
