### ISSUE TITLE
FEATURE: Allow overriding the pages dir so all files don't have to be duplicated

### ISSUE THREAD

**Issue by brassy-endomorph** [alephdata/aleph#2576]
**Is your feature request related to a problem? Please describe.**

I want to customize a single page on the app and not have to manually manage all the files that are already in the defaults pages dir.

**Describe the solution you'd like**

The `ALEPH_PAGES_PATH` should be supplemented with `ALEPH_PAGES_PATH_OVERRIDE` and app logic should first check for the page in the override dir the the normal pages dir.

**Describe alternatives you've considered**

None tbh

**Comment by tillprochaska** [comment]
To be honest, I think it’s very unlikely that we implement this. Aleph currently ships with only two pages that contains very simple contents intended for demonstration purposes. Also, if you want to actually keep those demo files, copying them to your custom directory is a simple, one-time task. I’m going to close this for now.
