### ISSUE TITLE
Upgrade command does not work

### ISSUE THREAD

**Issue by PlainSite** [alephdata/aleph#2609]
Hi,

I am running `docker-compose run --rm shell aleph upgrade` and the output is as follows:

Starting aleph_convert-document_1 ... done
Starting aleph_elasticsearch_1    ... done
Starting aleph_redis_1            ... done
Starting aleph_postgres_1         ... done
Starting aleph_ingest-file_1      ... done
Starting aleph_worker_1           ... done
[2022-10-17 18:28:28,241] ERROR:root:Error: Can't locate revision identified by '274270e01613'

I'm not sure what to do from here. Any help would be appreciated. Also, the issue described at https://github.com/alephdata/aleph/issues/1838 is still a problem even when the command does work.

Thanks!

**Comment by tillprochaska** [comment]
Hi @PlainSite, could you please let us know which version of Aleph you’re running? Thanks!

**Comment by PlainSite** [comment]
I can no longer sign into the web-based UI (the normal home page loads and then immediately redirects to a white screen), so how would I find that out?

**Comment by tillprochaska** [comment]
You can for example check the version in the `docker-compose.yml` file: https://github.com/alephdata/aleph/blob/main/docker-compose.yml#L83

**Comment by PlainSite** [comment]
`image: alephdata/aleph:3.7.1`

**Comment by tillprochaska** [comment]
You’re running a very old version of Aleph, 3.7.1 was released in 2020. However, you have previously migrated your database schema to use a newer version of Aleph. In your case, it seems you had already upgraded to Aleph 3.10.1 or newer before. Also, please keep in mind that this is not a support channel (see [SUPPORT.md](https://github.com/alephdata/aleph/blob/3.10.1/SUPPORT.md)).
