### ISSUE TITLE
Search results categories

### ISSUE THREAD

**Issue by villewilson** [alephdata/aleph#264]
Having a far higher number of categories than initially expected (when I was creating the previous mockups), I switched the search results display to a more iconic approach.

This is the mockup of what it could look like
![topbarcategories](https://user-images.githubusercontent.com/34656275/34168565-1be61b02-e4e5-11e7-945e-27ad8d49cdb9.jpg)

and these are the icons we will use for each category, sourced from FontAwesome
![categoryicons](https://user-images.githubusercontent.com/34656275/34168587-317d1312-e4e5-11e7-955f-cdb8f64b88d1.png)

Each icon is supposed to have clearly visible overlay popup on mouseover event, so users can be easily informed what they mean.

**Comment by pudo** [comment]
Loving these icons :)

**Comment by pudo** [comment]
We need to revive these icons, but the function is redundant for now.
