### ISSUE TITLE
Email preview UI

### ISSUE THREAD

**Issue by villewilson** [alephdata/aleph#266]
ideas on how to preview eml files

![emailpreviewa](https://user-images.githubusercontent.com/34656275/34216982-534e8654-e5aa-11e7-9ea4-236634c64dd1.jpg)

![emailpreviewb](https://user-images.githubusercontent.com/34656275/34216987-57904b58-e5aa-11e7-84ba-6baddbd7706e.jpg)

**Comment by pudo** [comment]
I think this is solved in the latest version. Attachments are still shown down below the message button (because that way it can be a simple folder view), but there's a link from the headers which indicates how many attachments there are.
