### ISSUE TITLE
BUG: Password protected PDF files throw errors, user not notified

### ISSUE THREAD

**Issue by jlstro** [alephdata/aleph#2696]
**Describe the bug**
We ingested PDF documents in Aleph and some of them where password protected. Instead fo notifying the user, Aleph returns a *OSError('Error opening file)* when accessing the document in question.

**To Reproduce**
1. Upload password protected PDF
2. open Aleph preview

**Expected behavior**
Aleph should show a clear message exlaining that the file was not processed due to password protection.

**Aleph version**
3.13

**Screenshots**
<img width="730" alt="image" src="https://user-images.githubusercontent.com/3785873/202452100-6bc548ee-5fb0-43df-bc85-a1d1b66c6056.png">

**Comment by stchris** [comment]
Fixed by @catileptic in https://github.com/alephdata/ingest-file/releases/tag/3.18.2, will likely make the next Aleph release.
