### ISSUE TITLE
FEATURE: Integrate OpenCensus metrics & traces

### ISSUE THREAD

**Issue by stchris** [alephdata/aleph#2714]
**Is your feature request related to a problem? Please describe.**
In terms of observability we often need to have more insights into the state of Aleph. Typical examples include: how long does an ingest job take on average? How often do retries occur when converting documents? How many files were processed in a given time?

**Describe the solution you'd like**
Google Cloud [describes](https://cloud.google.com/monitoring/custom-metrics/open-census#monitoring_opencensus_metrics_dependencies-python) how to use [OpenCensus](https://opencensus.io) for emitting metrics and traces. We want a setup which is able to emit a metric (say: number of ingest jobs started) and a trace (say: duration of odt -> pdf conversion).

**Describe alternatives you've considered**
Extracting metrics from logs is a possibility and it works well for some scenarios (e.g. "How many pdf parse attempts have failed because of a password protection"), but not for the majority of instances where we just want to count stuff and look at distributions.

**Additional context**
`servicelayer` seems like the obvious target for the scaffolding and for the long-running exporter. 

- [ ] Implement the flask opencensus integration for aleph (https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-flask)

**Comment by Rosencrantz** [comment]
Superceeded by the work that @tillprochaska has been doing on Prometheus #3214
