### ISSUE TITLE
FEATURE: Show the deployed FtM version on Aleph about page

### ISSUE THREAD

**Issue by uhhhuh** [alephdata/aleph#2742]
**Is your feature request related to a problem? Please describe.**
(In)ability to quickly figure out what the currently deployed version of FtM is wrt the available entities etc.

**Describe the solution you'd like**
FtM version number alongside Aleph version on /pages/about

**Comment by Rosencrantz** [comment]
@stchris Fixed this so closing with a 3.13.1 fix version.
