### ISSUE TITLE
port assignment in aleph.env doesn't take

### ISSUE THREAD

**Issue by scarnecchia** [alephdata/aleph#279]
```
ERROR: for 594f45504d09_aleph_web_1  Cannot start service web: driver failed programming external connectivity on endpoint aleph_web_1 (78ffa064921f5296fe0dba3aa5a79759b386ec81222a089962636eab1ab3ef98): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint aleph_web_1 (78ffa064921f5296fe0dba3aa5a79759b386ec81222a089962636eab1ab3ef98): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

I changed the port in aleph.env to no avail. I've tried changing the web port in docker-compose.yml under. That sort of works, in that when I run docker-compose build I get a different error, further along the process.

**Comment by pudo** [comment]
Thanks for trying out Aleph. You're on the right track, you'll want to edit the web port to be "12345:8080" (currently that's line 120 in `docker-compose.yml`). You'll also need to edit the environment variables for `APP_UI_URL` in `aleph.env` to point there. Can you give me an indication of what that error you are seeing down the line is?

**Comment by scarnecchia** [comment]
Excellent! The second error may be related. `docker-compose run` runs through its process until it gets to ui_1, at which it spits some instructions related to npm install, and pauses.

I won't have access to that machine until later today, but I'll post the terminal output when I do.

**Comment by pudo** [comment]
`ui_1` will cease doing stuff once it's built the UI code, that's expected. You should only see `api_1` and possibly `web_1` output stuff in reaction to individual requests.

**Comment by scarnecchia** [comment]
Hmm, this may be user error at this point, so if you'd prefer I take this to the google group, let me know. At this point, when I navigate to `localhost:8080`, a blue-green page loads with a circle graphic that just spins infinitely. When I navigate to `/api/2/sessions/login` I get an internal server error.

In both cases I get the following spit out at me:

`postgres_1       | 2018-01-12 12:58:38.485 UTC [35] ERROR:  relation "role" does not exist at character 397
postgres_1       | 2018-01-12 12:58:38.485 UTC [35] STATEMENT:  SELECT role.id AS role_id, role.created_at AS role_created_at, role.updated_at AS role_updated_at, role.deleted_at AS role_deleted_at, role.foreign_id AS role_foreign_id, role.name AS role_name, role.email AS role_email, role.api_key AS role_api_key, role.is_admin AS role_is_admin, role.type AS role_type, role.password_digest AS role_password_digest, role.reset_token AS role_reset_token 
postgres_1       | 	FROM role 
postgres_1       | 	WHERE role.deleted_at IS NULL AND role.foreign_id = 'guest' 
postgres_1       | 	 LIMIT 1
api_1            | ERROR:aleph:Exception on /api/2/login [GET]
api_1            | Traceback (most recent call last):
api_1            |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
api_1            |     response = self.full_dispatch_request()
api_1            |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
api_1            |     rv = self.handle_user_exception(e)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
api_1            |     return cors_after_request(app.make_response(f(*args, **kwargs)))
api_1            |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
api_1            |     reraise(exc_type, exc_value, tb)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
api_1            |     rv = self.preprocess_request()
api_1            |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
api_1            |     rv = func()
api_1            |   File "/aleph/aleph/views/sessions_api.py", line 39, in load_role
api_1            |     request.authz = Authz(role=role)
api_1            |   File "/aleph/aleph/authz.py", line 16, in __init__
api_1            |     self.roles = set([Role.load_id(Role.SYSTEM_GUEST)])
api_1            |   File "/aleph/aleph/model/role.py", line 122, in load_id
api_1            |     role = cls.by_foreign_id(foreign_id)
api_1            |   File "/aleph/aleph/model/role.py", line 73, in by_foreign_id
api_1            |     return cls.all().filter_by(foreign_id=foreign_id).first()
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2778, in first
api_1            |     ret = list(self[0:1])
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2570, in __getitem__
api_1            |     return list(res)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2878, in __iter__
api_1            |     return self._execute_and_instances(context)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2901, in _execute_and_instances
api_1            |     result = conn.execute(querycontext.statement, self._params)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
api_1            |     return meth(self, multiparams, params)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
api_1            |     return connection._execute_clauseelement(self, multiparams, params)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
api_1            |     compiled_sql, distilled_params
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
api_1            |     context)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
api_1            |     exc_info
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
api_1            |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
api_1            |     context)
api_1            |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 507, in do_execute
api_1            |     cursor.execute(statement, parameters)
api_1            | ProgrammingError: (psycopg2.ProgrammingError) relation "role" does not exist
api_1            | LINE 2: FROM role 
api_1            |              ^
api_1            |  [SQL: 'SELECT role.id AS role_id, role.created_at AS role_created_at, role.updated_at AS role_updated_at, role.deleted_at AS role_deleted_at, role.foreign_id AS role_foreign_id, role.name AS role_name, role.email AS role_email, role.api_key AS role_api_key, role.is_admin AS role_is_admin, role.type AS role_type, role.password_digest AS role_password_digest, role.reset_token AS role_reset_token \nFROM role \nWHERE role.deleted_at IS NULL AND role.foreign_id = %(foreign_id_1)s \n LIMIT %(param_1)s'] [parameters: {'foreign_id_1': 'guest', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)`

I'm not sure if the issue is that I haven't created a user yet, or if the I set up the google API wrong. It happens in cases when I leave `ALEPH_OAUTH=false` too though. In the later case, I `make shell` and then:

`root@2002d8f0fa65:/aleph# aleph createuser --email="example@domain.com" --name="Dan" --is_admin=True userid123
Traceback (most recent call last):
  File "/usr/local/bin/aleph", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aleph' distribution was not found and is required by the application
root@2002d8f0fa65:/aleph# `

Any thoughts? I'm using the docker production image, but I've also tried a clean build and the results are the same.

**Comment by pudo** [comment]
This is quite informative, thanks for keeping sharing it here. The first error is certainly cause by the fact that your database isn't initialised. You'd fix that by running `aleph upgrade` inside the worker once (i.e. start the worker shell via `docker-compose run worker /bin/bash`).

However, the second error indicates that something is odd with your build. Perhaps you can just try to run `docker-compose build` once before re-starting the worker shell. If that doesn't fix it, the output of `pip install -e .` from inside the worker shell might be very useful to share here. 

Sorry for all the trouble.

**Comment by scarnecchia** [comment]
Ah, no need to apologize! `Docker-compose build` seems to have worked, and my database initializes fine. I've configured OAuth incorrectly, but I'm sure that's entirely user error.

Would it be helpful if I organized some of the steps here and made pull request against the docs for production environments?

**Comment by pudo** [comment]
That would be extremely useful! We've changed quite a bit of the procedure around in the last couple of months, and for the 2.0 release the prod docs are definitely due a bit of an overhaul!

**Comment by scarnecchia** [comment]
Great! Thank you for the help! I'll try to turn to that this evening or over the weekend. I have some other questions which I suspect are related to the updates not jiving with the documentation as it currently stands, but I'm going to go ahead and close this, and open new issues related to those when I start working on the docs.
