### ISSUE TITLE
BUG:  Registering blocks a user from Singing In

### ISSUE THREAD

**Issue by catileptic** [alephdata/aleph#2806]
**Describe the bug**
This bug was reproduced on Aleph running in development mode. 
When a user Registers using an e-mail on the landing page, they can no longer access the username & password modal when clicking Sign In. 

**To Reproduce**
1. Navigate to the Aleph landing page an a unauthenticated user.
2. Click `Sign In`
3. Click `Don't have account? Register!`
4. Fill in your email, click `Sign Up`
5. Close the modal.
6. Click `Sign In` again
7. What the user now sees in a modal titled `Check your inbox`. There is no way for the unauthenticated user to see the username & password modal again. 

Restarting the docker containers clears up this bug.

**Expected behavior**
After registering, when an unauthenticated user clicks `Sign In`, they expect to be able to see the username & password fields in the modal window.

**Aleph version**
3.13.0

**Screenshots**
![image](https://user-images.githubusercontent.com/14028425/211779324-e0a6ddb4-3da7-49c6-bbf8-6d6e2cf7d09b.png)

**Comment by tillprochaska** [comment]
Fixed in #2817
