### ISSUE TITLE
BUG: Banner message not shown

### ISSUE THREAD

**Issue by lyz-code** [alephdata/aleph#2824]
**Describe the bug**
When setting the `ALEPH_APP_BANNER` environment variable the message is not shown

**To Reproduce**
1. Add to the `.env` file: `ALEPH_APP_BANNER='Planned downtime today at 12:15'`
2. Restart the docker
3. Log in the site
4. See only an orange bar
![aleph](https://user-images.githubusercontent.com/24810987/213426810-248dc818-b114-4a18-a257-ce41dad15c8f.jpg)

**Expected behavior**
The message is shown

**Aleph version**
Aleph 3.13.0

**Comment by tillprochaska** [comment]
Thanks for reporting this bug. The fix will be shipped with the next release.
