### ISSUE TITLE
FEATURE: Persist bookmarks server-side

### ISSUE THREAD

**Issue by tillprochaska** [alephdata/aleph#2831]
**Is your feature request related to a problem? Please describe.**
We have implemented an experimental bookmarks feature a while ago (see #2572). The current implementation stores bookmarks on the client-side. The feature has been received positively by users.

The current implementation has a major downside: bookmarks are stored in local storage. That means users can’t access bookmarks on other devices/in other browsers and users can delete all their bookmarks unintentionally by clearing their browsing data.

**Describe the solution you'd like**
Bookmarks need to be stored on the server side.

- [ ] Bookmarks currently stored in local storage need to be migrated automatically, i.e. we probably need an API endpoint to bulk-add bookmarks. Bookmarks currently stored in local storage shouldn’t be overriden by bookmarks stored on the server, i.e. if a user has local bookmarks in multiple browsers and logs in, bookmarks from all browsers need to be migrated successfully.
- [ ] We need API endpoints to add and remove a bookmark for an entity.
- [ ] We need an API endpoint to list all bookmarks (probably with support for pagination).
- [ ] The `GET /entities/:id` endpoint needs to return whether an entity is bookmarked if the user is authenticated (this can be a request option)

**Additional context**
* We should focus on adding a server-side implementation for the feature that is currently available first. However, we should consider potential future enhancements of the feature (e.g. filtering search results for bookmarks, sharing bookmarks with other users, adding multiple separate bookmarks lists/tags, searching bookmarks, bookmarking collections etc.)
* I think there were ideas to make bookmarks FtM entities and/or to store bookmarks in ES.

**Comment by tillprochaska** [comment]
The most straight-forward implementation that comes to mind would be storing bookmarks in our app Postgres database in a separate table `bookmarks`. This table would store `entity_id`, `role_id`, `created_at`, ….

## Storing bookmarks in Postgres

* Adding/removing a single or multiple bookmarks is as easy as inserting/deleting a row.

* Retrieving a list of all bookmarks requires fetching all bookmarks from the `bookmarks` table first, then fetching entity data from ES. Not ideal, but probably still easy enough to implement and maintain.

* When visiting an entity detail page in the UI, users need to be able to see whether that entity is currently in their bookmarks. We would need to send a separate request to Postgres in `GET /entities/:id`. Currently, this endpoints retrieves data from ES only.

  Alternatively, we could check this in a separate API endpoint. However, the additional HTTP request also seems a bit wasteful given that we almost always need to get this information when we show entity details.

In addition to supporting the current bookmarks feature, we should also consider potential future enhancements of the feature.

* One thing many users have requested is tagging entities/documents as "read", "interesting", "irrelevant" etc. Currently bookmarks are a boolean toggle, but I could imagine extending this to something that is similar to tags. This could be as easy as adding a separate `label` column to the `bookmarks` table. But even migrating to a slightly more complex schema shouldn’t be a problem using Alembic.

* Filtering search results to show only bookmarked entities would require additional queries to Postgres (and may even be impossible if we need to support users with maaany bookmarks).

* Showing whether an entity is bookmarked on search results pages is possible, but requires an additional request to Postgres.

**Comment by stchris** [comment]
Thanks for properly describing the possible implementation scenarios in such detail, @tillprochaska ! At first it did sound inefficient to store bookmarks in Postgres when we’d need to query ES as well, but I feel like this could be a good first implementation. We could think about options once we see significant issues with this design, perhaps.

**Comment by stchris** [comment]
> we probably need an API endpoint to bulk-add bookmarks

I’m not sure if we’d need bulk endpoints, we could in theory send them from local storage to the API one by one?

**Comment by tillprochaska** [comment]
> At first it did sound inefficient to store bookmarks in Postgres when we’d need to query ES as well,

Not sure if this is what you mean, but storing bookmarks *only* in ES would be an option as well, yes. However, I think one of the main architectural decisions in Aleph is that the source of truth for all data is in a data store other than ES – entities are stored in ftm-store, and all other app data is stored in the app database. This allows us to rebuild the ES index at any time (even though it would take a very long time to do so at OCCRP’s scale). The only exception I’m aware of are notifications, which are ephemeral.

> I’m not sure if we’d need bulk endpoints, we could in theory send them from local storage to the API one by one?

Yes, this is true. However, I think a robust implementation of this would become more complex. Browser limit the number of concurrent active requests, so for someone with hundreds of bookmarks, this could take some time. Also, the probability that at least one request fails out of 100 requests is a problem, so we’d need to track individual requests that failed in order to retry. Sending many requests at the same time may trigger rate limits etc.

I’d prefer implementing a bulk endpoint on the backend that we can properly test if it allows us to avoid this complexity.

**Comment by tillprochaska** [comment]
Another option that is slightly different from the first approach, that can reduce the ES performance overhead if we do not support the full range of filters, offsets, limits etc that the default search endpoint (`/entities` etc.) do support.

When requesting a list of bookmarked entities, we fetch only n entity IDs from Postgres. Then, we request the entity data for these entities from ES. This means that the number of filters of the ES query is limited by the number of items per page (probably something like ~20-30) instead of the total number of bookmarks of a user (which could probably be in the thousands).

The downside is that we already have all the logic and API endpoints in place to filter, search, and paginate entities via ES. So we’d have to reimplement some basic pagination and filter API for this bookmarks endpoint -- but I think this is a fair tradeoff.

**Comment by tillprochaska** [comment]
> The downside is that we already have all the logic and API endpoints in place to filter, search, and paginate entities via ES. So we’d have to reimplement some basic pagination and filter API for this bookmarks endpoint -- but I think this is a fair tradeoff.

Quick update: We do actually already have [an abstraction](
https://github.com/alephdata/aleph/blob/ba37501f1d087aac5d711dc35611134c271f2ab5/aleph/search/result.py#L74) in place that handles pagination etc. for database queries (i.e. queries that aren’t handled by ES) as well. In practice, it can be used like this:

```py
query = Bookmark.query.filter_by(role_id=request.authz.id)
result = DatabaseQueryResult(request, query)
return BookmarkSerializer.jsonify_result(result)
```

This gives us a simple API endpoint that supports `limit` and `offset` parameters and automatically populates results with metadata like the current page, the total number of results etc.
