### ISSUE TITLE
BUG: PDF image extraction is incomplete

### ISSUE THREAD

**Issue by stchris** [alephdata/aleph#2833]
**Describe the bug**
Some PDF documents result in no searchable text (or much less than can be seen when previewing it).

**To Reproduce**
Upload a PDF file which contains vector graphics or scanned text in different image formats. Check the list of images in a PDF file with `pdfimages -list some.pdf`.

**Expected behavior**
Reasonable searchable text in the preview pane after OCRing images.

**Aleph version**
3.13.1

**Comment by Rosencrantz** [comment]
@stchris Any chance you could like related PRs to this issue?

**Comment by stchris** [comment]
Sure @Rosencrantz,  this was fixed in https://github.com/alephdata/ingest-file/pull/449

**Comment by Rosencrantz** [comment]
Moving to 'Done' because it's done.
