### ISSUE TITLE
Error during Installation

### ISSUE THREAD

**Issue by vpramoth** [alephdata/aleph#285]
While running make web command, Iam getting the error "api_1 | ProgrammingError: (psycopg2.ProgrammingError) relation "role" does not exist"
![screenshot from 2018-01-16 02-54-02](https://user-images.githubusercontent.com/8606203/34962318-30a33bee-fa69-11e7-9ee5-89e08e5f6474.png)

**Comment by pudo** [comment]
Did you run `aleph upgrade` from within a worker container? It looks like the database wasn't properly created.

**Comment by vpramoth** [comment]
I tried running upgrade. It throws out "Distribution not Found
![screenshot from 2018-01-16 07-46-56](https://user-images.githubusercontent.com/8606203/34968871-dd62c11a-fa91-11e7-8cb8-55f14b27d053.png)
"

**Comment by pudo** [comment]
Can you try again now? This should be fixed in #296.

**Comment by vpramoth** [comment]
@pudo Thanks, It is now working.
