### ISSUE TITLE
Installation docs not up-to-date

### ISSUE THREAD

**Issue by scarnecchia** [alephdata/aleph#286]
Per #279, docs are out of sync with recent changes. Update docs with feedback from @pudo in that thread with eye towards 2.0.

Document
- [ ] Port variables: changes needed in `docker-compose.yml` and `aleph.env`. This said, I assume `docker-compose.yml` will be updated prior to release of 2.0 and this will become moot?
- [ ] Database init
- [ ] `aleph crawl` appears to have been replaced with `aleph bulkload` 
- [ ] `aleph crawldir` behavior is confusing. Better reflect processes which allow worker shell to see directories/docs to crawl.

@pudo: This is here as a mental reminder to myself, but also to document what I plan to do so that I don't document that will either be soon out-of-date or isn't actually desired behavior on the part of the app. Feel free to assign the issue to me.

**Comment by pudo** [comment]
I think this is all up to date now, living in the Wiki: https://github.com/alephdata/aleph/wiki
