### ISSUE TITLE
Dates histogram

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#288]
For a date facet (e.g. creation date), show a little histogram below the search box in which the user can select an active data range for their search. 

This will need extensions of the API for range searches and date histograms, but nothing super exotic.

**Comment by pudo** [comment]
@davo11122 In Kibana, there's a [really nice date histogram on searches](https://www.elastic.co/guide/en/kibana/current/discover.html). What do you think we could do to get a similar feature? We'll probably need to expose some additional facet API on the backend, but on the front-end I'd love to figure out if we can do it in React only, or if we need to add a dependency on some of D3 to get it done. Do you have any ideas?

**Comment by davo11122** [comment]
@pudo in Kibana they use http://visjs.org/ for histogram visualization, there is a react wrapper for this lib https://www.npmjs.com/package/react-vis which can be super helpful if we decide to implement histogram on our side.

**Comment by pudo** [comment]
Fixed in #1258.
