### ISSUE TITLE
BUG: update ftm docs link

### ISSUE THREAD

**Issue by stchris** [alephdata/aleph#2885]
**Describe the bug**
Aleph docs still reference followthemoney.readthedocs.io

**To Reproduce**
See https://docs.alephdata.org/developers/followthemoney

**Expected behavior**
We should point to https://followthemoney.tech/

**Aleph version**
latest

**Screenshots**
-

**Additional context**
-

**Comment by akrymets** [comment]
As far as I can see `followthemoney.tech` link isn't relevant.
I found a more relevant link - `https://docs.aleph.occrp.org`.
Hope it'll be useful
