### ISSUE TITLE
BUG: uploading a password protected .xlsx document results in a vague message

### ISSUE THREAD

**Issue by stchris** [alephdata/aleph#2957]
**Describe the bug**
Previewing a password protected .xlsx file is not possible and the message `Format not supported` could be more specific

**To Reproduce**
1. Go to `Documents` in an investigation.
2. Click on an `.xslx` file with password protection
3. The error message says "No preview is available for this document. Format not supported"

**Expected behavior**
A more precise message would be great: "This document can't be previewed because it is password protected."

**Aleph version**
3.14.0-rc6

**Screenshots**
<img width="669" alt="Screenshot 2023-03-24 at 14 23 48" src="https://user-images.githubusercontent.com/217554/227532859-270574a2-8824-4379-8c4c-a3a7d01ae59e.png">

**Additional context**
-

**Comment by catileptic** [comment]
This was fixed in [this commit](https://github.com/alephdata/ingest-file/pull/551) in `ingest-file`. It's available in version `3.20.0` of `ingest-file`.
