### ISSUE TITLE
Crawldir Does Not Execute in Ubuntu

### ISSUE THREAD

**Issue by DtorrX** [alephdata/aleph#305]
When I run docker-compose run app python aleph/manage.py crawldir /somepath to crawl my data, I get the following: ERROR: No such service: app. What am I doing wrong here? Aleph has deployed correctly otherwise.

**Comment by pudo** [comment]
[Paste from email comms]: There are two modes of running Aleph: production mode and developer mode. It mainly affects whether the code of the app is editable while it is running. The difference is made via two docker-compose files: ``docker-compose.yml`` for production and ``docker-compose.dev.yml`` for developer mode. The ``app`` container only exists in developer mode, and could be invoked like this:

```
docker-compose -f docker-compose.dev.yml run app [… command …]
```

(There’s a shortcut for this, which is to run ``make shell`` — that also starts up the necessary background services). Note also that when you do crawldir in developer mode, you need to prefix file paths with “/host” to get outside of the docker environment: e.g. if you want to import /home/user/MyLeak, it would be /host/home/user/MyLeak inside docker.

In production mode, we’re moving away from having people load data via the docker container, instead we’re encouraging the use of the REST API. There’s a command-line utility, ``alephclient`` that you can install on your host computer from pip which will upload a local directory via the API.
