### ISSUE TITLE
BUG: Once populated, a dataset's metadata URL field will reject (validation) empty string/no value

### ISSUE THREAD

**Issue by brrttwrks** [alephdata/aleph#3060]
**Describe the bug**

Once a dataset's metadata field is populated, it is not possible to remove the value altogether - validation rules require that there be value.

**To Reproduce**
1. In a dataset, add a value to any of the URL fields and save.
2. Now try and delete the value to the URL field, but not replace it with another value. Just an empty string.
3. Aleph returns a validation error.

**Expected behavior**
We should be able to remove a value if that value is incorrect or no longer necessary, from any of the metadata fields. 

**Aleph version**
Aleph production (aleph.occrp.org): 3.14.1rc17

**Screenshots**
None

**Additional context**
None.

**Comment by tillprochaska** [comment]
Additional context:

This affects the `data_url`, `info_url`, `publisher_url` fields. All of these use the custom `ftm-url` string format.

My best guess would be that `nullable` only allows actual `None`/`null` or absent values, but not empty strings.

In that case, we could either change the validation or adjust the UI form to send proper `null` values if a field is empty. I’d be slightly in favor of the former, I think.

**Comment by tillprochaska** [comment]
The next release will include a fix for this bug :)
