### ISSUE TITLE
BUG: XREF is not matching against all the things that it should

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#3062]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Aleph version**
We need to know which version of Aleph you’re using to be able to reproduce the bug. If you aren’t using the latest version, please make sure to verify that the bug is still present in the latest version of Aleph.

**Screenshots**

**Additional context**

**Comment by brrttwrks** [comment]
I am going to add more detail to this issue as we are dealing with it now. 

What is occurring now:

When you XREF a collection with documents, Aleph only XREFs the mentions if the collection is an Investigation, not a Dataset. If XREFing mentions in documents is important for our needs/research, then we must:
- change the dataset to an investigation first
- run the xref
- then change the investigation back to a dataset

I would expect XREF to work the same on both Datasets and Investigations. Is there a reason this doesn't or shouldn't happen?

**Comment by Rosencrantz** [comment]
This issue is dead. There are better issues detailing this problem
