### ISSUE TITLE
FEATURE: Display the version of ingest-file used to process a document in the UI 

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#3063]
**Is your feature request related to a problem? Please describe.**
When tracking down issues with ingested documents it's important that we are able to identify the version of ingest-file used to ingest the document along with a timestamp of when the document was ingested.

**Describe the solution you'd like**
Update ingest file to incorporate this information into the entity metadata then pull this information when displaying in Aleph.

**Comment by catileptic** [comment]
Fixed by [this commit](https://github.com/alephdata/aleph/commit/e3771d17c4ac3786a61b29c65aab229a75de4106) which bumps the version of `ingest-file` to the version that contains this fix.
