### ISSUE TITLE
Wireframes for Aleph 2

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#307]
These are some of the wireframes for the interface have been working on for Aleph 2.

The approach is conservative and actually not radically different to Aleph 1; the idea behind having wireframes is to have a reference so we understand what we are building towards and more easily discuss issues we might have by starting from the same point during discussions.

* These have not been tested with users yet. I aim to start doing that this week.
* There is a 3 pane metaphor intended to be consistent with user expectation based on how other applications behave - to make it easy for users we always display filters on the left, content is largest / in the middle and metadata on the right.
* These are are open for review, iteration and debate! They will certainly be shaped by actual feedback once we start putting it in front of users.
* If you think one is problematic please to take it out and make a comment or issue about it and we can figure out how to make it work better.
* If you think there is a problem with the metaphor it would be helpful to have examples of some different use cases so we can understand the problem.
* Not every screen is framed yet (e.g. settings, entities, editing entries). Please feel free to add your own! I'm also happy to work on these or to turn paper sketches into these if that would be helpful.

I've just exported these quickly, if you'd like the Omnigraffle origional, PDF or blank templates let me know.

![alpeh_2_wireframes_v1_0](https://user-images.githubusercontent.com/595695/36370554-7b4f8a10-155f-11e8-9735-5501a694c0d9.png)
![alpeh_2_wireframes_v1_1](https://user-images.githubusercontent.com/595695/36370555-7b70f1c8-155f-11e8-8769-12cb2f1d5eac.png)
![alpeh_2_wireframes_v1_2](https://user-images.githubusercontent.com/595695/36370556-7b8d4418-155f-11e8-83f8-43669a1c6694.png)
![alpeh_2_wireframes_v1_3](https://user-images.githubusercontent.com/595695/36370557-7baa50a8-155f-11e8-947a-9f0432a5c18d.png)
![alpeh_2_wireframes_v1_4](https://user-images.githubusercontent.com/595695/36370559-7bc7bf76-155f-11e8-939c-d85543e111df.png)
![alpeh_2_wireframes_v1_5](https://user-images.githubusercontent.com/595695/36370560-7be50284-155f-11e8-8eca-d96b3d724cfb.png)
![alpeh_2_wireframes_v1_6](https://user-images.githubusercontent.com/595695/36370561-7c0254d8-155f-11e8-814c-f28b995d1c41.png)
![alpeh_2_wireframes_v1_7](https://user-images.githubusercontent.com/595695/36370562-7c20fc8a-155f-11e8-9912-f9570aab3504.png)
![alpeh_2_wireframes_v1_8](https://user-images.githubusercontent.com/595695/36370563-7c404f5e-155f-11e8-96a6-d752b7d801ac.png)
![alpeh_2_wireframes_v1_9](https://user-images.githubusercontent.com/595695/36370564-7c5eacd8-155f-11e8-9c89-2d149c81df87.png)

**Comment by pudo** [comment]
I think this is all implemented now :)
