### ISSUE TITLE
BUG: "-" in country name gets interpreted as "Zimbabwe"

### ISSUE THREAD

**Issue by zufanka** [alephdata/aleph#3128]
**Describe the bug**
while uploading entites to Aleph from CSV "-" in country name gets interpreted as "Zimbabwe"

**To Reproduce**
- yaml: https://pastebin.com/Fd1Z9jS2
- csv: https://pastebin.com/iS2UgM6V

**Expected behavior**
not assigning any country

**Aleph version**
3.13

**Screenshots**
![image](https://github.com/alephdata/aleph/assets/2411066/6234b172-ceaa-4b1e-8cbb-6117d48f0ded)

**Comment by tillprochaska** [comment]
Hi @zufanka, thanks a lot for opening an issue and providing the example spreadsheet and mapping. This makes reproduction much easier for us!

I have uploaded the CSV file and generated entities using the mapping you provided. However, I could not reproduce the issue. All generated entities are assigned the correct country or no country.

<img width="227" alt="Screen Shot 2023-06-14 at 19 48 34" src="https://github.com/alephdata/aleph/assets/1512805/7021751c-5c80-462b-b213-027b7a45555e">

Could you double-check that you can reproduce the issue with the CSV file and mapping you provided by uploading the CSV file to an empty investigation and running the mapping there?

**Comment by tillprochaska** [comment]
Hi @zufanka, any chance you could try to reproduce this issue as per my comment above?

> Could you double-check that you can reproduce the issue with the CSV file and mapping you provided by uploading the CSV file to an empty investigation and running the mapping there?
