### ISSUE TITLE
Make relationships clickable

### ISSUE THREAD

**Issue by rhiaro** [alephdata/aleph#313]
Some relationships have a bunch more metadata that isn't shown in the summary list. Each row in a list of relationships needs to be clickable to take you to the full entity display for them.

**Comment by pudo** [comment]
I'm still a little bit -1 on this. I understand that some of the contract lot things can go a bit heavy, but perhaps then we should make their listings better. Navigating people to lots of `Directorship` pages which have 2 entities and no label etc. will IMO be a usability nightmare.

**Comment by rhiaro** [comment]
Maybe they could be clickable iff there's more data that is not shown in the table. Or show all data in the table, which currently I don't think it is.

**Comment by rhiaro** [comment]
I think I found the problem. If a relationship is specific, say a `Payment` the view on the related entities is actually the *least* specific parent, in this case a `Transaction`. So a bunch of info (`amount`, `toAccount`, `purpose`, etc) is missing from the table with no way to get to it.

So we either need to use the most specific schema in the listing, or if that's gonna pack in too much stuff to look good, a little 'details' button (in the case where there's more) to slide open another row underneath with more info (or something).

**Comment by rhiaro** [comment]
`Contract` is a special case because `Contract` is a Thing which has the `authority` property which is also a Thing. So a `LegalEntity` which has awarded many contracts displays this as a relationship-type list, but you can't click on any of the contracts (which would in turn take you to the `Contract` entity view, which would show the relationship with one or more `supplier`s).

So the rule would be: "if something in a relationship listing is a `Thing` (not an `Interval`) make the whole row or something in the row clickable" (it should have a `name`).

**Comment by pudo** [comment]
FWIW, I actually think entity previews are the way out of this. So we should render only the featured props of a relationship entity, plus an expand button -- and then pop up a sidebar for details if needed.

/cc @iaincollins
