### ISSUE TITLE
FEATURE: Support IAM role-based authentication to S3

### ISSUE THREAD

**Issue by zekehuntergreen** [alephdata/aleph#3185]
**Is your feature request related to a problem? Please describe.**
At the moment, if storing and retrieving files in S3, the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` need to be set.
For stacks that use EC2, role-based rather than key-based authentication would have a few advantages:
- better security: admins wouldn't need to store, and manage, and rotate secret keys, risking their being compromised.
- more specific access control: only the EC2 instance would have access to the S3 bucket, rather than any client with the access key

**Describe the solution you'd like**
We could support IAM role authentication by making a few changes:
- a change to the environment variable template to explain that `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are optional and that if they are not provided, role-based auth will be used.
- ~An update to the [s3 client](https://github.com/alephdata/servicelayer/blob/ceb20c34ce141796c46585247cb88607299f3d1c/servicelayer/archive/s3.py#L21C2-L21C2) so that access key ID and secret key are only passed to `client` if they are non-null. Otherwise, assume that we're running on an EC2 instance with an IAM role configured with access to the appropriate S3 bucket. Boto3 will [fall back to role-based auth](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#id1).~

I'd be happy to submit a PR for this change if it sounds reasonable to others!

**Comment by stchris** [comment]
Hey @zekehuntergreen , thanks for your detailed submission. This totally makes sense to have and if you are able to submit a PR we would be very glad! Let us know if you need any guidance.

**Comment by zekehuntergreen** [comment]
> Hey @zekehuntergreen , thanks for your detailed submission. This totally makes sense to have and if you are able to submit a PR we would be very glad! Let us know if you need any guidance.

Thanks very much, @stchris! @philmcmahon and I are working on a PR and will send you a message if we could use a hand.
