### ISSUE TITLE
Search view / facets improvements

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#319]
- [x] Facet sidebar should have no elevation
- [x] Remove right hand border from facet sidebar
- [x] Remove breadcrumb bar from search results view
- [x] Make selected facet values bold
- [x] Make "more" link visially similar to values in list 
- [x] Use larger and bold font for facet titles
- [x] Use FormattedNumber for facet titles 
- [x] Move search input into main nav menu
- [x] Remove facet tags from search input (but keep folders for in-folder searches?)
- [x] Use icons for different types of facets
- [ ] Use Collection.Icon lock to show private collections

### Nice-to-have

The following are not known blockers, but would be good to address if we can.

- [x] Make facet count API calls happen after result is returned if possible
- [x] Don't refresh lists until after new result has returned (i.e. don't zero the list of each type of filter when the filter list changes, just gray them out while it's fetching updated details)
- [ ] Improved error handling (sometimes callbacks fail, forcing a refresh)
- [ ] Provide a way to search for specific filters (collections, names, etc) to apply

**Comment by pudo** [comment]
Plus feature request: can we make the types facet contain the icons for the different types? And can we show the little Collection.Icon lock with those collections that are private?

**Comment by iaincollins** [comment]
Just recording some addendum based on discussions:

- [ ] Remove right hand border from facet sidebar
- [ ] Remove breadcrumb bar from search results view

**Comment by iaincollins** [comment]
I'm at the stage where we would like to pause for review and see what we want to do next (and respond to any issues raised with the UX by this so far).

We might want to do some additional things next we hadn't anticipated and possibly push some outstanding items for the search into a future issue and spend our time bringing other views up to par.

<img width="1590" alt="screen shot 2018-02-28 at 10 40 51" src="https://user-images.githubusercontent.com/595695/36780754-2fdc06c8-1c74-11e8-8ace-23bb13193e5c.png">

**Comment by iaincollins** [comment]
The main bugs here are done and we have agreed we will move the rest of the unresolved issues into a follow up ticket (e.g. in to a 2.1 update).

**Comment by pudo** [comment]
Closing this because it seems reasonably stable and evolved now. Let's open more tickets if needed.
