### ISSUE TITLE
Re-organize React components.

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#321]
It's become messy, we need to split it out.

**Comment by pudo** [comment]
Some examples:

* https://github.com/meedan/check-web/tree/62de4496a5f04ff8b73af3d8406118f8d32c407b/src/app
* https://github.com/huridocs/uwazi/tree/development/app/react

Proposal (inside `src/`):

```
screens/
  CollectionScreen/
    index.jsx
    style.scss
  CollectionEditScreen/
    index.jsx
    style.scss
  CollectionIndex/
    index.jsx
  [...]
components/
  Collection/
     Browser/
     Card/
     Info/
       index.jsx
     index.jsx
   Entity/
   Document/
      Viewers/
actions/
app/
assets/
content/
reducers/
util/
```

**Comment by iaincollins** [comment]
I like the idea of cleaning this up and am happy to jump on it.

Are we sure we are happy with:

```
screens/
  CollectionScreen/
    index.jsx
    style.scss
```

vs:

```
screens/
  CollectionScreen/
    CollectionScreen.jsx
    CollectionScreen.scss
```

Not advocating anything! Just asking one last time before we do it so (a) it only has to be done once for now and (b) avoids as much disruption as possible :-)

Tagging in @pudo @emmina for comments!

**Comment by pudo** [comment]
I'm happy with either, I guess a) is easier to interface with externally so it may be the better answer :)

**Comment by pudo** [comment]
Closing after emina has done this to the extent we're gonna get around to at the moment.
