### ISSUE TITLE
Folder view improvements

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#336]
Some improvements have been made to the Folder View in in the `view-fixes` branch for #330 but this is to capture the larger work on the folder view we want to do.

The main ticket item is really to fix the searching in folders to work with the new search view (which means restoring tags into the global search bar, but only for things like searching in folders/emails and other special cases), but anyone has any other suggestions they want to add to this ticket please add them!

- [x] Handle empty folders gracefully
- [x] Restore search to folder view

**Comment by pudo** [comment]
I've done the folder search now. My intuition upon using it is that switching to recursive search once the user starts typing a query may actually end up being intuitive. It would produce the same behaviour currently used in Mac OS X finder. OK to do?

**Comment by iaincollins** [comment]
Ooh awesome! Yes I think that's good.

I was thinking more about both folder view and previews last night, and can imagine we might think about folder view differently later but I don't think it's any reason to stop us improving what we have on that view.
