### ISSUE TITLE
FEATURE: Indexing Email Headers

### ISSUE THREAD

**Issue by TheDataHunter** [alephdata/aleph#3377]
Hello I just want to ask if aleph is already indexing email headers (containing sometimes useful metadata)? and if not if it would be considered to be a new feature of aleph in near future. thx for the great work already and all the best!

**Comment by tillprochaska** [comment]
Hi @TheDataHunter, Aleph currently parses and indexes a subset of common email headers such as `From`, `To`, `Cc`, `Bcc`, `Reply-To`, `Message-ID`, `References` etc. Aleph currently does not index the raw headers. However, in addition to parsing and indexing, Aleph also stores the original source file, so you can always download that for further analysis.

If you think that Aleph should parse and index additional email headers, feel free to suggest that as a feature request. In that case, please make sure to use the issue template for feature requests and to provide context around your use case.

**Comment by TheDataHunter** [comment]
perfect! thank you for your fast reply. I'll consider of doing so.

**Comment by tillprochaska** [comment]
I’ll close this issue for now, but feel free to reopen with additional information :)
