### ISSUE TITLE
Unsupported file type shows wrong error message

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#347]
For [this MP3 file](https://beta.data.occrp.org/documents/10287756) I get this error:

```
No search results

Try making your search more general
This folder is empty.
```

We might need to check the fall through behaviour for files like this. I thought we had 'unsupported file type' fallback behaviour but I'm maybe wrong, or it's just not worked in this case.

**Comment by pudo** [comment]
Is this fixed, @emmina ?

**Comment by emmina** [comment]
Yes it is @pudo.
