### ISSUE TITLE
How to add document metadata fields

### ISSUE THREAD

**Issue by jbothma** [alephdata/aleph#349]
https://github.com/alephdata/aleph/wiki/Metadata states that metadata fields can be added but doesn't say how.

Could you give some hints as to what needs to change to add a metadata field, and as bonus, how to make it appear in 1) search results and 2) to the UI?

I'm running the stable branch. So far adding a property setting a field in Metadata.meta and re-ingesting hasn't resulted in the field showing up in the DB.

**Comment by jbothma** [comment]
I've got it showing up in search results API responses now https://github.com/public-people/aleph/commit/06c2c8e2b4506379489ba647eecf701025f2fded

I've learned (again - been a long time since I hacked on aleph)
- dates can't be datetimes - they'll get ignored.
- a celery worker does the indexing so no matter how many times I run `aleph index` or `aleph crawl`, nothing will index until I run the worker

This is sufficient for me for now.

If there's a way of extending metadata without forking aleph, that'd be sweet. In the meantime I'll run a fork.

**Comment by pudo** [comment]
Hey @jbothma -- sorry for not getting back to your emails this weekend. Some comments:

a) `stable` is eight months out of sync with `master` and migration will be hell-ish. Are you absolutely sure you want to base off `stable`? It is definitely unmaintained and unsupported by OCCRP.

b) `master` has a metadata field called `published_at` (which can be set from a datetime).

c) I'd be keen to merge PRs for other fields, as long as their specificity is somewhere in the neighbourhood of DublinCore fields (e.g. `publisher`).

d) If you want to go proper exotic (`my_reference_id`), it wouldn't be ultra-hard to add support for writing random fields. My main concern would be that data validation, and properly mapping them into the search index. But it's solvable.

happy hacking!

**Comment by jbothma** [comment]
On 12 March 2018 at 14:43, Friedrich Lindenberg <notifications@github.com>
wrote:

> Hey @jbothma <https://github.com/jbothma> -- sorry for not getting back
> to your emails this weekend. Some comments:
>

No worries! It was weeked :D


> a) stable is eight months out of sync with master and migration will be
> hell-ish. Are you absolutely sure you want to base off stable? It is
> definitely unmaintained and unsupported by OCCRP.
>
I'd love to work closer to master - is master expected to be in a working
state always - i.e. should I try and run master and see how far I get? And
report issues when I get stuck?

Otherwise can you make a tag or give a commit hash that's known to work?

On master I had an issue with queues not being iterable (looked related to
a recent PR) and ui not building
https://github.com/alephdata/aleph/issues/348

> b) master has a metadata field called published_at (which can be set from
> a datetime).
>
That's all I need for now - hurra!

> c) I'd be keen to merge PRs for other fields, as long as their specificity
> is somewhere in the neighbourhood of DublinCore fields (e.g. publisher).
>
> d) If you want to go proper exotic (my_reference_id), it wouldn't be
> ultra-hard to add support for writing random fields. My main concern would
> be that data validation, and properly mapping them into the search index.
> But it's solvable.
>
Both reasonable for later, thanks!
