### ISSUE TITLE
BUG: development testing `make upgrade` fails with postgres address error

### ISSUE THREAD

**Issue by exprez135** [alephdata/aleph#3494]
In my attempt to follow the installation instructions for development, I am hitting an error while the `make build` section is running:

`sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Name or service not known`

I saw that this was referenced in #125, but I have not yet found a way to get around it. Might anyone have some advice for me?

The full text of the log is uploaded here: https://transfer.sh/get/hvdhPK6tGb/errors.txt

**Comment by Rosencrantz** [comment]
Hi @exprez135 I suspect that this is more of a support request than a bug. Could ask you to a create a support question on our Discourse instance https://aleph.discourse.group/. You'll likely need to create an account.

The support space can be found here:

https://aleph.discourse.group/c/get-help-with-installing-maintaining-and-using-aleph/6

In the request can you include information on what version of Aleph (or which commit) you are using. It will help us to help you.

Thanks!
