### ISSUE TITLE
Public search/metadata but not content

### ISSUE THREAD

**Issue by jbothma** [alephdata/aleph#352]
I'd like to provide a public search API with the search/sort/filter and metadata results available in Aleph but I don't have the right to redistribute the content of my corpus.

Basically, I want to make everything public except the content.

Is this something aleph currently supports, or something that makes sense to build into aleph? Or is it better done using a restrictive proxy in front of aleph?

**Comment by pudo** [comment]
That's difficult, I think: it'll mean not rendering any PDF, email, text file or preview. It would also probably mean turning off the records API, and file API. It's somewhat hard to predict how many things would be killed by the knock-on effects of doing that....

**Comment by jbothma** [comment]
Thanks. In that case the easiest thing would be for me to make a little proxy API exposing only what I'd like to publicly.
