### ISSUE TITLE
BUG:  'aleph.manage' has no attribute 'app'

### ISSUE THREAD

**Issue by Paradoxxs** [alephdata/aleph#3606]
Just downloaded Aleph, and changed the configuration file according to the installation guide 
And start the container with docker-compose up -d

The problem is with the API container where I get the error of  'aleph.manage' has no attribute 'app' and here after it shutsdown.

**Aleph version**
3.15.5

**Additional context**
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 414, in import_app
app = getattr(mod, name)
AttributeError: module 'aleph.manage' has no attribute 'app'
Failed to find attribute 'app' in 'aleph.manage'.
[2024-02-03 08:09:01 +0000] [9] [INFO] Worker exiting (pid: 9)

**Comment by tillprochaska** [comment]
Hi @Paradoxxs, thanks for reporting this problem. Unfortunately the installation guide referenced a configuration template on the unstable `develop` branch. I’ve just opened a PR with a fix in #3608 to fix this.

In the meantime, until this is merged, you should be able to use the Docker Compose configuration from the `main` branch: https://github.com/alephdata/aleph/blob/main/docker-compose.yml
