### ISSUE TITLE
Improved table view (new viewer, searchable)

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#362]
1. We want to be able to filter table views again.

    This was disabled in refactoring for the Preview mode as it didn't work well combined with main search view. We need to refactor the search code for it to use the new approach (with the Query class) now used in the Folder preview and also do some refactoring to simplify the logic.

2. We would like to show other sheets if the table is from a workbook.

3. We would like to try using the Blueprint.js spreadsheet view to see how it works out.

    One problem we have with the current table view is that windows are not horizontally scrollable unless you have a trackpad (or a mouse that supports side scrolling) and this would resolve that.

   We have some concerns about performance with it though, so we might want to try it out and see.

    We have had feedback that users like the current simple view, so we might also want to consider how that could be improved (e.g. toggle to hide overflowing row contents?) as an alternative.

**Comment by pudo** [comment]
It's now searchable, but it should get a little bit of a make-over.
