### ISSUE TITLE
BUG: language used to describe email entities and email addresses is ambiguous 

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#3668]
**Describe the bug**
On the dataset homepage there is some confusion between email addresses found and emails indexed. Both use the same text 'emails' but it should be made clear that one is the number of email entities whereas the other is the number of unique email addressed found in the data.

**Screenshots**

<img width="721" alt="Screenshot 2024-04-02 at 5 02 59 pm" src="https://github.com/alephdata/aleph/assets/340405/cb10eebc-0222-4c92-b7ac-8be5fc547e1f">

**Comment by tillprochaska** [comment]
For future reference:

I think this is the file that we’d need to update: https://github.com/alephdata/aleph/blob/develop/ui/src/components/SearchField/util.js#L38

This will likely also update the title of the emails search facets, but that’s not a problem. Search facets also filter for email addresses (not emails), although arguably the UI is less ambiguous there.
