### ISSUE TITLE
How to handle multiple properties on model?

### ISSUE THREAD

**Issue by terion-name** [alephdata/aleph#3730]
Let's assume ftm model `Person`. Person has phone and email, for example. Singular.

But in real life most people have multiple phones and/or emails. How to handle this with ftm and aleph?

**Comment by tillprochaska** [comment]
Properties in FollowTheMoney are multi-valued, and Aleph has full support for multiple values for properties, too.

You might want to also check out the FollowTheMoney introduction here: https://followthemoney.tech/docs/
