### ISSUE TITLE
Geography Extraction

### ISSUE THREAD

**Issue by jcshea** [alephdata/aleph#376]
Goal : Extract reliable country / region / ... / address tags from Aleph corpus.

* As a user, I want to know what countries are discussed in a particular document so that I can filter.
* As a user, I want to know what other companies are registered at the same address so that I can check for related entities. 
* As a user, I want to see a map of companies or events so that I know what geographic extent the case has. 

Tools: 
* geonames
* libpostal
* polyglot_entity
* spacy

**Comment by jcshea** [comment]
current draft pipeline / toolset :

- geonames : list-level import of hierarchy-categorized geo entities (country/region/city/etc)... pseudonyms and multi-language support available)
- ahocorasick : build automaton of selected geonames hierarchies
- spacy : entity extraction and output on doc level 
- efficiently search spacy entities with geonames automaton to identify & disambiguate (map USA; United States; 'Murica to the same)

toy version of the above up & operational.  will draft code to repo as time allows.

other immediate spacy goals include:
explore other relevant extraction levels, very possibly including noun chunks, which might be matched to multiple geo-hierarchy levels : see : https://spacy.io/usage/linguistic-features
also interested in linking existing entity extraction (the BIG LIST) with 'dependency parsing' output... ie $oligarch traveled to $extracted_geoloc



tools to experiment with and consider for incorporation:
- https://github.com/openeventdata/mordecai
- https://github.com/openvenues/libpostal

**Comment by pudo** [comment]
TODO: gotta check out https://github.com/jmbielec/geograpy3

**Comment by pudo** [comment]
One more: https://clavin.bericotechnologies.com/

**Comment by pudo** [comment]
Storing this here for a bit:

```bash

# sudo apt-get install curl autoconf automake libtool pkg-config
# git clone https://github.com/openvenues/libpostal
# cd libpostal
# ./bootstrap.sh
# ./configure --datadir=[...some dir with a few GB of space...]
# make -j4
# sudo make install

# # On Linux it's probably a good idea to run
# sudo ldconfig
```

**Comment by pudo** [comment]
All of this is done except libpostal, which I've filed as #505. Closing.
