### ISSUE TITLE
BUG: link to localhost on sign up

### ISSUE THREAD

**Issue by hjnormey** [alephdata/aleph#3786]
**Describe the bug**
After receiving the sign up email, the link contains a locahost url:

http://localhost:8080/activate/[characters]

**To Reproduce**
1. Go to site
2. Click on signup
3. See signup mail

**Expected behavior**
A link to the site, resulting in an account.-

**Comment by tillprochaska** [comment]
Hi @hjnormey, please make sure to set the `ALEPH_UI_URL` configuration option: https://docs.aleph.occrp.org/developers/installation/#configuration-options

Feel free to reopen this issue if this doesn’t resolve the problem.
