### ISSUE TITLE
BUG: Information in JSON for an ingesting dataset does not seem to be entirely correct

### ISSUE THREAD

**Issue by Rosencrantz** [alephdata/aleph#3787]
**Describe the bug**
From the status page when reviewing active ingest jobs the start_time,  end_time, and last_updated don't seem to reflect what I would expect for a dataset.

**Expected behavior**
I would expect start_time to be a static time from when a dataset started being ingested. end_time should show the point at which a dataset completed. last_updated should show the last time a file was ingested, analysed, or indexed.

**Aleph version**
4.0.0 (aleph.occrp.org)

**Comment by tillprochaska** [comment]
Fixed in https://github.com/alephdata/servicelayer/pull/190
