### ISSUE TITLE
OpenGraph / Twitter Card to layout

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#380]
It would be good to add some metadata so when people share links to an instance of Aleph - e.g. via Twitter, Facebook and within an organisation on Slack, Skype, Wiki's etc. -  it then pop ups a description and info about the URL, with an appropriate logo or thumbnail.

Ideally it would also reflect the current page (title, description and maybe image) but that would have to wait until server side rendering is in, but we could still do something now if we wanted.

The standards for this are OpenGraph (Facebook) and Twitter Cards, which both use HTML <meta> tags that go in the page <head> (although I _think_ in practice they can be put anywhere on a page).

```javascript
// Variables
const description = "";
const title = "";
const url = "";
const imageUrl = "";
const twitterUsername = "";
const twitterImageUrl = "";
```

```html
<!-- Facebook OpenGraph -->
<meta name="description" content={description}/>
<meta property="og:title" content={title}/>
<meta property="og:url" content={url}/>
<meta property="og:description" content={description}/>
<meta property="og:image" content={image}/>

<!-- Twitter Cards -->
<meta name="twitter:card" content="summary"/>
<meta name="twitter:site" content={url}/>
<meta name="twitter:title" content={title}/>
<meta name="twitter:description" content={description}/>
<meta name="twitter:image" content={twitterImageUrl}/>
```

You can test this mark up with the following URLs:

https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/

The tricky thing with this is we don't have server side rendering currently, so would need to be injected into the template the same way the API URL is and be the same for all pages (which would be fine, but is a bunch of vars).

As a workaround, we could make some of the data generic.

Note the image URL could be variable with an absolute path to an image on the website - it doesn't have to be hosted on the same sub-domain (e.g. a value like http://www.occrp.org/image/some-image-path.jpg would be fine). You can use the same image for both OpenGraph and Twitter cards, but by default the image sizes and ratios are different (e.g. Twitter is square unless you say use a large format card).

**Comment by pudo** [comment]
I've looked into this a little bit and we basically have two options: 

a) Set up server-side rendering for the React application 
b) Implement a simple HTML renderer in the backend that emits valid metadata and forwards to the actual resource. 

Both seem like a lot of effort to circumvent this issue. Proposing WONTFIX for now.
