### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#381]
I have seen PDF documents indexed by Google appear on Aleph 1 API URLs (e.g. at data.occrp.org).

These URLs no longer work under Aleph 2 as the URLs have changed slightly.

I wonder if we include a robots.txt file that tells search engines not to index files under `/api/`.

**Comment by pudo** [comment]
I've looked into this a little, and there really doesn't seem to be a way to prevent google from indexing based on a pattern (e.g. ``/api/2/documents/*/file``). I've therefore added ``Link`` headers to all file downloads which define the canonical URL to be the UI url of the document. This way Google can index the PDF, but the results should show the UI url as the link. Let's hope this works well.
