### ISSUE TITLE
BUG:  Problem when running aleph on raspberry pi 5 8gb

### ISSUE THREAD

**Issue by Paradoxxs** [alephdata/aleph#3810]
**Describe the bug**
When I run "docker-compose up -d"  on my raspberry pi, I get the error show in log, I think the problem is that it have not been design to run on arm processor. 

I also have tried the command "make build" command to build the images, but faced the same problem.

**Aleph version** : latest

**log**

aleph_shell_1 exited with code 1
aleph_ui_1 exited with code 1
aleph_worker_1 exited with code 1
aleph_ingest-file_1 exited with code 1
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
aleph_worker_1 exited with code 1
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
aleph_ingest-file_1 exited with code 1
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
aleph_worker_1 exited with code 1
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
aleph_ingest-file_1 exited with code 1
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
ingest-file_1    | exec /bin/sh: exec format error
aleph_worker_1 exited with code 1
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error
worker_1         | exec /usr/bin/aleph: exec format error

**Comment by stchris** [comment]
Hi @Paradoxxs , unfortunately we don't support Raspberry Pi as a target platform. The issue you are facing is likely because we don't provide compatible container images, so you could always try and build these yourself. It is quite possible that you will be facing other problems, quite likely related to being memory constrained.
