### ISSUE TITLE
BUG: Metadata API Request Error Handling

### ISSUE THREAD

**Issue by richardjennings-occrp** [alephdata/aleph#3812]
**Describe the bug**
The UI does not utilise a retry limit or backoff for retrying Metadata API requests when the API is not available.

**To Reproduce**
1. Start the UI without an Aleph API available

**Expected behaviour**
The UI should retry a number of times delayed by some form of backoff. 

If a maximum number of retries is reached there should be some button to try again (refresh).

**Aleph version**
Current

**Screenshots**
<img width="484" alt="network-error-spinning" src="https://github.com/user-attachments/assets/d9e7d579-f5a2-46cf-9ced-e08a5c27cc2c">

**Additional context**

**Comment by dimitardanailov** [comment]
Dear @richardjennings-occrp 

I've created a new pull request: https://github.com/alephdata/aleph/pull/3813
I'd like to request to review my patch / pull request.
