### ISSUE TITLE
BUG: missing text box to add new users in "Access control" dialog

### ISSUE THREAD

**Issue by ltrgoddard** [alephdata/aleph#3867]
**Describe the bug**
I noticed yesterday that the "Access control" dialog for Investigations in OCCRP's hosted Aleph web UI is missing a component — namely, the text box where you can enter the email address of a user to share the Investigation with them.

All Investigations where I have sharing permissions now show the "Groups" and "Users" lists, but give no ability to share with new users.

**To Reproduce**
1. Open any Investigation in the web UI
2. Click on the cog/gear icon at the top-right
3. Click 'Share'
4. Text box to add new users is missing

**Expected behavior**
Text box allows you to enter the email address of a user to share the Investigation with.

**Aleph version**
Aleph 4.0.0rc57 (via OCCRP web UI)

**Screenshots**
![Screenshot 2024-09-18 at 13 24 05](https://github.com/user-attachments/assets/df823e81-836d-4823-9048-b7f72936b386)

**Comment by ltrgoddard** [comment]
This appears to be resolved now.

**Comment by tillprochaska** [comment]
Indeed, thanks for reporting!
