### ISSUE TITLE
Display more source info on source search screen

### ISSUE THREAD

**Issue by rhiaro** [alephdata/aleph#390]
When you click to search a collection it would be nice to still have a button or sidebar or something to open the source summary view alongside the results.

Specifically sometimes I forget which collection I'm in, and when I have two open with similar names the blue filter box thing with the name of the collection is so small it cuts off enough characters that if the first word of the collection names are the same I can't tell which is which. I'd also like to sometimes be able to see the updated date and description without having to go back.

**Comment by pudo** [comment]
Do you mean that the facet values should link to two different outcomes?

**Comment by rhiaro** [comment]
When the search is filtered on a source, a link to the source info would be handy. So maybe a link on the blue filter box with the source name (is that the 'facet value'?), or even a hover which at least expands to the full name if it's cut off.

To be consistent, I imagine the link would open the right sidebar with the details.
