### ISSUE TITLE
Mini UI issues

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#401]
* [x] Clicking a folder in a folder view currently does a preview sidebar, which is not useful. Do we want to hot-wire the preview for folders?
* [x] When the collection preview pane is open but another collection is loaded, the access dialog is unpopulated.
* [x] In some cases the result preview for text searches does not seem to be triggered even if there are matching records
* [ ] The previews that pop up in an alert notification should be searches for the alert query text

**Comment by emmina** [comment]
* fix loading tabs in preview. When there are still stuff to load, tabs are disabled. Put some loader icon.

**Comment by pudo** [comment]
moved remaining items to separate tickets.
