### ISSUE TITLE
Document paging controls broken in Preview

### ISSUE THREAD

**Issue by iaincollins** [alephdata/aleph#403]
It looks like the document paging controls broke in recent refactoring:

https://data.occrp.org/search?q=#page=8&preview%3Aid=1564385&preview%3Amaximised=true&preview%3Atype=document

The URL is updated, but the view no longer updates. I guess we might need to add something to the PDF Viewer component to have it watch for changes and update the current view. The Paging Control also needs to be aware of changes to the URL so it updates. I can't remember without looking how the `currentPage` is passed down.

It used to work, so my guess it's impacted by taking logic out of Preview.

The paging controls do work fine in the normal view still:

https://data.occrp.org/documents/1564385#page=5

I'm not sure why they work here and *not* Preview, but I assume there is a way to also make it work in Preview, given the components are shared between both Document View and Toolbar. Maybe just by passing down `currentPage` correctly, or by updating the view.

I'm happy to be assigned this, but wanted to raise it as a bug in case it's on anyone's radar already - and to open up the discussion on if we just don't want to allow PDF previewing at all in search if we think it's a janky experience for users.

(Personally I think it would be neato have it always be possible to toggle PDF previewing in search, even when there are results shown, but appreciate we might want to make a tactical call on how we approach it, with a view to doing it better later.)

**Comment by pudo** [comment]
I got curious about this and it seems the render for when the location hash changes stops propagating between the Preview and PreviewDocument compontents. If I pass the parsedHash from Preview into PreviewDocument it works, but that's hacky.

p.s. We may want the EntityListRow component to overwrite page when it does a new preview.
