### ISSUE TITLE
FEATURE: Suggest using faster hash algorithm like XXHASH3-64 rather than SHA1 in servicelayer

### ISSUE THREAD

**Issue by amone-bit** [alephdata/aleph#4061]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by catileptic** [comment]
What would be the problem addressed by this? 

Closing this - but please feel free to re-open with more details if you would like to see this replacement happen.
