### ISSUE TITLE
Feature request: Way to return list of collections that a given collection has already been cross referenced with?

### ISSUE THREAD

**Issue by noelmas** [alephdata/aleph#413]
I would like to be able to make an API request that returns the collections a given a collection has already been cross-referenced against. If there is already a way of doing this would love to know it!

**Comment by pudo** [comment]
I think that's ``/api/2/collections/:id:/xref`` if I understand you correctly.

**Comment by pudo** [comment]
Can you confirm this is resolved?

**Comment by noelmas** [comment]
Resolved thanks Pudo
