### ISSUE TITLE
Missing error-info during installation

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#424]
Hi,

Friedrich pointed me to this project, so i am currently checking it to see how it works locally. Upon running "make all" i am greeted by an error which i understand, but i do not get enough information aback to figure out where the issue is, and fixing it.

As the output below shows, installation fails. And i kinda need to figure out which domains is unresolvable so i can investigate further

(in this case i had to restart Docker, so it got resolved, but it would still help with more info in this case)

`tep 3/10 : RUN pip install --upgrade -r /tmp/requirements-generic.txt && rm -rf /root/.cache
 ---> Running in 37f6a024672c
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/six/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e08d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/six/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/six/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/six/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0c90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/six/
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from -r /tmp/requirements-generic.txt (line 1)) (1.11.0)
Collecting Flask==0.11.1 (from -r /tmp/requirements-generic.txt (line 3))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/flask/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0e90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/flask/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/flask/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/flask/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7feced0e0790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/flask/
  Could not find a version that satisfies the requirement Flask==0.11.1 (from -r /tmp/requirements-generic.txt (line 3)) (from versions: )
No matching distribution found for Flask==0.11.1 (from -r /tmp/requirements-generic.txt (line 3))
ERROR: Service 'api' failed to build: The command '/bin/sh -c pip install --upgrade -r /tmp/requirements-generic.txt && rm -rf /root/.cache' returned a non-zero code: 1
Makefile:49: recipe for target 'build' failed
make: *** [build] Error 1
`

**Comment by pudo** [comment]
Can't think of a further action on this, short of hacking docker. Closing unless someone has an idea.
