### ISSUE TITLE
Add support for authentication via Azure Active Directory

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#437]
As we need to get some AD/LDAP authenticaton into Aleph in order to use it, i will start off contributing to this project by removing some dust from this PR, and send it back inn after seeing that it works.

https://github.com/alephdata/aleph/pull/162

Feel free to assign this issue to me

**Comment by Ueland** [comment]
As @pudo earlier mentioned that the previous LDAP support was not used by anyone, i will take a look on that code and see how it can be rewritten to support Azure Active Directory instead. That should make it possible to simply plug Aleph into any organization that uses Office65/Exchange for authenticaton.

**Comment by pudo** [comment]
Sounds great. I'm curious, though, if Office365 could be linked on with OAuth, it strikes me as a somewhat cleaner solution...

**Comment by Ueland** [comment]
I do believe that it is just that which happens actually, the OAuth request goes to "https://login.microsoftonline.com/<login type>/oauth2/v2.0/authorize". Our organization uses office365 too. So not quite sure if we should call this OAuth via office65 or Oauth via Azure AD.

I have a fork where i am working on it, will do a PR when i have it working.

**Comment by Ueland** [comment]
Just adding some notes here, the following are required for OAuth 2.0 auth against Azure/AD, and should  be added to the Wiki after merge:

> Create a new app over at https://apps.dev.microsoft.com, make a note of the KEY and secret you generate there. Callback URL should be as follows: https://<hostname>/api/2/sessions/callback .
Then add the following to aleph.env, remember to update KEY and SECRET with your values.

>ALEPH_OAUTH=true
ALEPH_OAUTH_KEY=***************************
ALEPH_OAUTH_SECRET=***************************
ALEPH_OAUTH_NAME=Azure
ALEPH_OAUTH_BASE_URL=https://login.microsoftonline.com/organizations/oauth2/v2.0/
ALEPH_OAUTH_AUTHORIZE_URL=https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
ALEPH_OAUTH_TOKEN_URL=https://login.microsoftonline.com/common/oauth2/token
ALEPH_OAUTH_SCOPE=openid profile email user.read
ALEPH_OAUTH_TOKEN_METHOD=POST
`

**Comment by pudo** [comment]
Are you using a custom handler in `aleph/oauth.py` for handling the returned token?

**Comment by Ueland** [comment]
Yup, have it working in my branch now. Hoping to finish off support for verifying the returned token tomorrow, then i will push it up.  Getting the verification method within the jwt decoder to work was a bit more work than i first  assumed.

**Comment by pudo** [comment]
@Ueland would you perhaps do the honors on updating the wiki? You have a write invite.

**Comment by Ueland** [comment]
Thanks, will go ahead and update it as soon as time permits it. Will comment and close this issue when done.

**Comment by Ueland** [comment]
Wiki updated.
