### ISSUE TITLE
Unable to create new collection via API

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#459]
> curl -H "Authorization: XXXXXX"-H "Content-Type: application/json" --request POST --data '{"name":"Ueland test1", "collection_id":"uelandtest1"' http://localhost:8080/api/2/collections
{"status": "error", "message": "You are not authorized to do this.", "roles": [1]}

User error or something else?

To quote the Wiki:
>To create a new collection, POST the JSON metadata to:
> /api/2/collections

It would also be nice if the wiki could go a bit in depth on which metadata is needed in such cases. All-though i can edit the wiki now, i do not know that answer yet :)

**Comment by pudo** [comment]
Hm, weird. Can you try -H ``"Authorization: apikey XXXXXX"``? 

The fields are: ``label``, ``foreign_id``, ``category`` (use "other"), ``description``.

**Comment by Ueland** [comment]
No dice, even did a aleph evilshit, logged in again, got my new API-key, and retried both your and my curl example. The e-mail address i use is also added as admin in the Aleph env file.

**Comment by Ueland** [comment]
The fact that i forgot a space between the first and second H did not exactly help on my issues... ;)

Resolved by not doing silly typing errors.

**Comment by pudo** [comment]
damn, I saw that and thought it was a copy paste artifact, so I didn't mention it :/
