### ISSUE TITLE
Date of the format "%Y" shown as "%Y-01-01"

### ISSUE THREAD

**Issue by uhhhuh** [alephdata/aleph#475]
Mapped as:
```
          birthDate:
            column: x.birth_year
            format: "%Y"
```
becomes:
Birth date
1981-01-01

**Comment by pudo** [comment]
Can you propose a solution around here?

https://github.com/alephdata/followthemoney/blob/master/followthemoney/types/date.py#L72

**Comment by pudo** [comment]
Fixed here: https://github.com/alephdata/followthemoney/commit/4dff47a27f9e9956813b28c2d897dcb3ff874f73
