### ISSUE TITLE
Not possible to truncate a collection?

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#477]
When having a collection with a large amount of entities, it will in certain cases be interesting to truncate a collection, before re-uploading the entities. (programmatically)

I would assume the solution is to get all the entities, then do a HTTP DELETE on them, but the API has a limit for 10K entries today. 

Another solution would be to delete the collection and create it again, but then you have the issue of losing access rights etc.

What would be the correct way of truncating a collection?

**Comment by pudo** [comment]
There's a CLI command called ``aleph flushentities <foreign_id>``, but that's not currently exposed via the API, I think. We might want to come up with a pseudo-resource (e.g. ``/collections/id/entities`` that can be DELETE'd.

**Comment by Ueland** [comment]
Some way to solve this would be very nice yes. I can look into it if nobody else does it but that will be a while into the future as i have to focus on getting some data into my installation first.

**Comment by pudo** [comment]
This will be available when we merge ``develop``. Calls:

* ``DELETE /api/2/collections/X/entities``
* ``DELETE /api/2/collections/X/documents``
