### ISSUE TITLE
Deleting a collection does not remove entities

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#478]
Performed the following:
> curl -H "Authorization: ****" -H "Content-Type: application/json" --request DELETE http://localhost:8080/api/2/collections/1

Checked that it was removed:

> curl -H "Authorization: *****" -H "Content-Type: application/json" "http://localhost:8080/api/2/entities?filter:collection_id=1&offset=0&limit=0"

Yet, the result is full of entities:

> {"status": "ok", "results": [], "total": 2157947, "page": 1, "limit": 0, "offset": 0, "pages": 1, "next": null, "previous": null, "facets": {}}

Expected a total of 0.

**Comment by pudo** [comment]
Are you running a worker service? The problem is that Elasticsearch doesn't really like deletes, it requires running a query and deleting each result. That's pretty slow, so we're doing it in a queue worker rather than the HTTP lifecycle.

**Comment by Ueland** [comment]
Yup, its running in the k8s world. So i assume that it will get deleted over time then? I will update the documentation and add a note about it in such case.

**Comment by Ueland** [comment]
Closing as issue was related to a crashed DB-sidecar for the worker service.
