### ISSUE TITLE
Show query logs to users.

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#479]
We have an API, ``/api/2/querylog``. This returns the search queries the user has run, aggregated by how often the term has been searched. We should have a way for the user to see this analysis, with the following actions for each queried term: 

* Create an alert from the query term (existing API)
* Re-do the search now
* Delete the query log for the term (API not yet implemented).

**Comment by davo11122** [comment]
- [ ] Create auto-suggest component for logs
- [ ] Create a new screen for query logs management

**Comment by davo11122** [comment]
All the functionalities available only for authorized user.

- On the welcome page users can find a their 10 last searches as a suggestions, pick a one my clicking on it or navigating by keyboard
![image](https://user-images.githubusercontent.com/3075886/46535335-2251e780-c8bc-11e8-9ab3-8b0372121e1b.png)

- On the search page suggestion will appear as well
![image](https://user-images.githubusercontent.com/3075886/46535438-7066eb00-c8bc-11e8-98f4-9ab8c0e7934d.png)

- There is a new menu item called `Activity Log` on navigation bar, by clicking on it user will be redirected to `Activity Screen`
![image](https://user-images.githubusercontent.com/3075886/46535541-c8055680-c8bc-11e8-8915-485e8bcb5bce.png)

- On `Activity Screen` user can find whole search history
![image](https://user-images.githubusercontent.com/3075886/46535742-5ed21300-c8bd-11e8-9289-9af8f0f4b29d.png)

**Comment by davo11122** [comment]
Implemented in https://github.com/alephdata/aleph/pull/568

**Comment by pudo** [comment]
Now in 2.3
