### ISSUE TITLE
Add Kubernetes config to repo

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#483]
Just a reminder to myself to add a version of my k8s config files to the main repo, so we have a shared configuration that everybody running on k8s can use.

I have it configured for one stage and one production env, just gotta finish the last part first.

Have also noted that the db-sidecars need a health check, will add that also

**Comment by pudo** [comment]
I wonder if it'd be too early in this project to consider drafting a Helm chart to be used for deployment...

**Comment by Ueland** [comment]
I haven't looked into Helm, but one important factor that must be looked into is that the resource limits and requirements that should be specified for all containers, and should be customizable  as every project will most likely have different amounts of data, and thus different needs.

**Comment by Ueland** [comment]
@pudo 2.2 is "official" now? As in, safe to upgrade my stage-setup to 2.2 and do the k8s-config changes so i can push them up to this repo?  Or do you recommend waiting a bit longer?

**Comment by sunu** [comment]
I have a local branch with helm charts that make resource limits, environment varibales in configmaps, some nginx configs customization. The charts are based on our production k8s configs, minus the secret bits. What I'm not so sure about is how to make the database settings flexible enough to be usable for both cloudsql and non-cloud dbs.

@Ueland If you can push your k8s configs, that would be awesome. I can base the helm charts on your config files then. Re 2.2: we have it in production, so I guess that makes it official?

**Comment by pudo** [comment]
@sunu We're leaking memory like it's nobody's business, so I'd give it another week with deploying 2.2

**Comment by Ueland** [comment]
I have created PR #518 for this work.

Here are some points somebody should look into as i did not found a easy solution to them as i am not 100% into all the code yet:

1. The container "search-extract-countries" need a health check
2. The container "search-extract-entities" need a health check
3. The container "elasticsearch" need a health check
4. The container "search-queue" need a health check
5. The container "search-recognize-text" need a health check
6. The container "search-scheduler" need a health check
7. The container "search-worker" need a health check

**Comment by Ueland** [comment]
@sunu you can grep for REPLACEME to find everything i *think* should be user-configurable
