### ISSUE TITLE
Document the permissions API

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#484]
It is possible to programmatically create/update collections via the API, but is it also possible to set permissions for a collection?

If no, we should get that in place.
If yes, does anybody have an example? I can update the wiki in such case.

**Comment by pudo** [comment]
Should work like this when you're logged in as a user with collection write privs:

![screenshot 2018-09-14 12 27 35](https://user-images.githubusercontent.com/41628/45545130-ab27b700-b819-11e8-8c7f-16d3845bfd91.png)

![screenshot 2018-09-14 12 27 53](https://user-images.githubusercontent.com/41628/45545133-aebb3e00-b819-11e8-9dd9-330da45c9901.png)

**Comment by Ueland** [comment]
Yeah, that does work fine, but it would be neat to do the same via API. Including managing groups. When one have many users or many collections, it wont be very trivial to manage it manually via a GUI.

**Comment by pudo** [comment]
But this is the API, it's just talking to ``/api/2/collections/X/permissions`` :)

**Comment by Ueland** [comment]
Ah, neat!
I will update the wiki and add a section on this then, il just keep this issue open until i have done it if that is okay. (as a reminder for myself)

**Comment by pudo** [comment]
So to clarify a few things: 

* There aren't really groups, or users, just roles that can either be of type user and type group.
* There's no REST API to make a group role, it's usually done by deriving it from OAuth in the oauth handler (like you did for Azure). 
* A permission is an intersection between a collection and a role. It can either be read, write or nothing (in which case it'll be deleted).

**Comment by Ueland** [comment]
Updated the API documentation now, will create a new issue with regards to groups
