### ISSUE TITLE
Split each screen to separate chunk

### ISSUE THREAD

**Issue by davo11122** [alephdata/aleph#489]
### Purpose 
Performance optimization

### Description
Splitting each screen to separate chunk will decrease bundle size and allow the application be loaded much faster.

**Comment by davo11122** [comment]
What is done?
- Each route/screen was separated from main bundle to chunk. 
- Created common and vendor chunks by upgrading react-scripts _(doesn't work good enough)_
- Optimized some of `import` statements to minimize chunk sizes

– | Before[develop] | After [davit/screen-as-chunk]
-|-------|------
Lighthouse| ![image](https://user-images.githubusercontent.com/3075886/46105815-17c28e80-c1e8-11e8-909a-49812e7deb27.png) |  ![image](https://user-images.githubusercontent.com/3075886/46105633-9b2fb000-c1e7-11e8-9f73-82c15a1ff446.png)
Chunks|  ![image](https://user-images.githubusercontent.com/3075886/46106262-59076e00-c1e9-11e8-93eb-b9ac5832c14d.png) | ![image](https://user-images.githubusercontent.com/3075886/46105755-e6e25980-c1e7-11e8-9ff5-e78ba55d3977.png)

So as you can see we saved ~2 second for users which is good but still not our enough.
After different experiments and researches I've found several ways to improve performance, for implementation I need more control over app configuration which is impossible because of react-scripts. 

So react-scripts team is [about to release](https://github.com/facebook/create-react-app/issues/5103) I suggest eject react-scripts once v2 will become stabile. 
We need ejection for SEO as well.

**Comment by pudo** [comment]
Seems like https://reactjs.org/blog/2018/10/23/react-v-16-6.html has a new way of doing this - is that worth exploring?

**Comment by pudo** [comment]
Done. Thanks @davo11122 !
