### ISSUE TITLE
data.occrp.org activity logging

### ISSUE THREAD

**Issue by jcshea** [alephdata/aleph#492]
ahoy front_&_back-enders of the 'leph : i want user data!  
annnnnd in a perfect world you snap your fingers and create it (along with a fair few hundred thousand hours of activity-logs, but i am willing to negotiate) from the void.  not trying for anything definitive here, just to get a little conversation going.  a little research plus my previous web/user-analytics experience suggests the low hanging but tasty fruit of:

- Dwell Time : how long someone stays on the page
- Scroll Depth : how far down the user scrolls
- Return visits: s/e but would require basic user-level identification obs
- Advanced features: associate query / common activity with pattern-search / case-files / VIS
- View-port: the new gold standard in user analysis, see: http://www.dcs.gla.ac.uk/~mounia/Papers/wsdm2016.pdf
- To collect viewport data for our study, we used JavaScript tracking instrumentation that allowed us to track user scroll positions, the size of the user browser viewport (width and height), as well as the position of key page elements, such as article header, body and comment blocks. This information allowed us to reconstruct the scrolling actions and calculate the amount of time users spend at given portion of the news article.

**Comment by Ueland** [comment]
Just to nitpick. This seems like analytics data, not logging per se. I do believe that Aleph already have activity logging, which are actual activity within the system?

So a suggestion from me to whoever implements this is to keep those two worlds separated

**Comment by pudo** [comment]
I assume we can sort this out by including some nasty third-party JS in the production site? We should then try and make this into an experiment, where we define a couple of user behaviour hypotheses we wish to work out and enable tracking only for the amount of time needed to check these aspects?
