### ISSUE TITLE
UI Feature request: "Read" function on documents

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#493]
One of my colleagues misses a feature which simply shows which documents in a search/document list is unread. Which makes it easier to come back to an old view to read up on new documents.

**Comment by pudo** [comment]
Yes, I've heard this feature proposed by multiple reporters as well, and seen it implemented in some commercial solutions. More recently, I've had discussions about whether a tool like this should support a notion of "result sets" as a sort of task management feature. These could be bulk copied into a case file, assigned to reporters for processing, etc. 

/cc @knowtheory @stephengrey

**Comment by pudo** [comment]
Closing in favor of https://github.com/alephdata/aleph/issues/493 where it can be done in a systematic way.
