### ISSUE TITLE
CI pipeline suggestion "Lighthouse CI integration"

### ISSUE THREAD

**Issue by dkhurshudian** [alephdata/aleph#499]
Lighthouse is an open-source, automated tool for improving the quality of web pages.

The repo [Lighthouse CI](https://github.com/ebidel/lighthouse-ci) implements full CI processing for [Lighthouse](https://developers.google.com/web/tools/lighthouse/) tool.
As a result we will get a stats about app stats especially by criteria **PWA**, **Performance**, **Accessibility** and **Best Practices**. For more details see Lighthouse CI repo.

Having this output attached to each PR we can understand quality and usability of the feature implementation and prevent merging in case results does't meet requirements.

**Comment by pudo** [comment]
I like this, but I'm not sure we need it in the CI chain since we can run it as a browser plugin. What do you think? If you want to have it around, would you be up for adding it to our travis config?
