### ISSUE TITLE
Xref UI Facelift

### ISSUE THREAD

**Issue by jcshea** [alephdata/aleph#503]
right now the interface is, imho, rather difficult to survey and extract critical results from.  today's default representation :
all xref results by xref-source => xref entities within source => individual docs associated with xref entities => individual doc details
...for large xref's this results in a rather unwieldy pile of xref'd sources and documents.  there are amazing results in there!  we can do better with these.

my ideas: 

- drop tab interface; immediately pop to new page.  
- add ENTITY-FILTER command to results display, to select only a given set of x-ref'd entities.  
- option to view top level results by x-ref'd entity (as opposed to source - ie "show me all the x-ref'd docs associated with this entity").  
- add export-to-csv option for (an abstraction of) xref results = source/entity/doc OR entity/source/doc hierarchy to allow investigators a "map" of x-ref'd results which can then be used as a reference / to go back and search for individual doc sets
- i imagine a sort of directory/document hierarchy browser, similar to what we use as a code editor, that could be used to quickly scan through xref-results by entity/source "paths" and let the investigator preview docs in various paths.  might be a bridge too far though.

**Comment by pudo** [comment]
Links to #535.

**Comment by pudo** [comment]
Next iteration of this done in `3.6.0`.
