### ISSUE TITLE
Use libpostal to normalise extracted addresses

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#505]
libpostal (and it's Python binding, [pypostal](https://github.com/openvenues/pypostal)) allow for the parsing and normalisation of address strings using a model trained against OpenStreetMap data. This would be useful in order to increase the likelihood that addresses are going to match based on string value (and those provide connectivity between disparate source records).

Open points on this:

* Should we do proper geocoding instead of these name-based hacks? 
* libpostal requires a few gigabytes of training data - should this be a gRPC service that gets called rather than a core component (spoiler: probably yes).

**Comment by pudo** [comment]
Thanks for the pointers to offline geocoders, that would indeed be an amazing piece of infra to get going. 

Note to self: Working on `alephdata/opensanctions` right now, and it's obvious we need an `Address` object in `followthemoney`. Every sanctions list has them split into components, and we're just string-joining it into a mess.

**Comment by pudo** [comment]
No actual momentum for doing this, closing.

**Comment by rjurney** [comment]
I have a great use case for this... and can do it in open source.

**Comment by Rosencrantz** [comment]
@rjurney We'd be really interested to accept any changes that you might want to add to implement address normalisation.
