### ISSUE TITLE
Amazon S3 error when trying to download a document

### ISSUE THREAD

**Issue by PastNullInfinity** [alephdata/aleph#529]
I've set up an Aleph instance on a VPS, and the corresponding S3 Bucket for data storage.

Everything seems to work fine, until I try to view any kind of document. The web preview does not work, and when I try to download from Aleph, this comes up:

```
The authorization mechanism
you have provided is not supported. Please use
AWS4-HMAC-SHA256.
````

The S3 instance is located in eu-west-3, which uses the Signature Version 4 for all API requests, maybe this is the problem?

I should note that downloading the files directly from the bucket works fine.

The Aleph build is the latest available, version 2.2.1

**Comment by PastNullInfinity** [comment]
Seem to have found a fix. There are some environment variables that are not shown in the default `aleph.env.tmpl` file. 

The culprit was the `ARCHIVE_AWS_REGION` variable, which defaults to eu-west-1. Adding the proper AWS region in the `.env` file fixed my problem.

Here is the problematic code.
https://github.com/alephdata/aleph/blob/656b9dbea5243d020eddc3c46fb0879899fdd27a/aleph/settings.py#L72-L82

If it's okay, I'll submit a pull request to add this variable as a default in the `aleph.env` template, since to properly configure a s3 Bucket this option is mandatory to properly work.

Also, but this is more of a request, we can discuss this in another issue if it's more appropriate, but there are a number of very useful variables that are nowhere to be seen in the default aleph.env, and only by digging around in the code one can find and add these variables. Could it be better to have a more complete default file, maybe with an "advanced" section for the people that need this level of customization?

**Comment by pudo** [comment]
I would love to see a better env template -- you are right, all the fun stuff only becomes visible when you dig into ``settings.py``. Would you be up for drafting a PR?

**Comment by PastNullInfinity** [comment]
Sure, I'll work on it
