### ISSUE TITLE
UI performance optimisation plan

### ISSUE THREAD

**Issue by davo11122** [alephdata/aleph#549]
I've done some optimization in #544 but there is always something that could be done better. This issue will serve as a place for performance-related suggestions and discussions.

**Comment by davo11122** [comment]
* blueprint icons has font-based and svg-based implementation each is ~100kb gzipped, our project uses both, we need to get a rid of font-based one. Additional keep an eye to this issue https://github.com/palantir/blueprint/issues/2193 to load only required icons.

**Comment by pudo** [comment]
Good stuff. I've spent a little bit of time thinking about (3) and short of introducing a node server process I can't really think of a good way for doing it. It's also locale-dependent, so it would need to be able to either do content negotiation, or get much larger.

**Comment by davo11122** [comment]
> Good stuff. I've spent a little bit of time thinking about (3) and short of introducing a node server process I can't really think of a good way for doing it. It's also locale-dependent, so it would need to be able to either do content negotiation, or get much larger.

Actually I don't think embedding is the best solution, this is kind of reminder for us to keep in mind that we have to do something with this request.

**Comment by pudo** [comment]
Aye. In general I feel like the bulk of our performance issues is now back-end related, so I'd propose we focus on doing speed-ups there (already started), and do other work on the front-end.
