### ISSUE TITLE
SEO ideas

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#553]
* [ ] Implement very basic schema.org itemprops (like Dataset) 
* [ ] Make it possible to pass a description into a screen. Define descriptions for common object types.

What else?

**Comment by pudo** [comment]
@davo11122 it looks like we're failing to render in googlebot again. Can you check that out asap?

**Comment by davo11122** [comment]
@pudo I've been looking at this issue, something terrible happens in Chrome v41, Polyfils are getting loaded after application code itself, working on this now

**Comment by pudo** [comment]
cf. #574 - fixed the immediate issue.

**Comment by pudo** [comment]
Closing, as basics are done.
