### ISSUE TITLE
Move collection actions to drop-down

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#554]
The collection sidebar has a growing number of actions (see below):

<img width="485" alt="screenshot 2018-11-06 13 20 43" src="https://user-images.githubusercontent.com/41628/48063972-d8b03180-e1c6-11e8-9416-ef26b8a17f1e.png">

It might be time to move them to a drop-down menu, so they don't clutter up the UI. I'd propose "Manage" as a title. The dropdown should also include:

* Delete (already implemented inside settings dialog, can be moved up) 
* Re-process (a new action, which would have a warning like the xref alert, and then post to ``/api/2/collections/<id>/process``. This would re-analyze all the data in the collection.

**Comment by davo11122** [comment]
Implemented in #554 PR

**Comment by pudo** [comment]
Merged and deployed.
