### ISSUE TITLE
Data not deleted from buckets

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#562]
I drained a Aleph-instance the other day. Upon checking the bucket Aleph uses, i noticed that documents were still in the bucket. There appears to not be any cleanup being performed against the storage itself?

**Comment by pudo** [comment]
Indeed, that's not currently implemented. I'd love to see it added to ``storagelayer``.

**Comment by Ueland** [comment]
I noticed that data is not deleted in Postgres either, just marked as deleted. Should one consider to also remove data from Postgres? In such case i think a dedicated cleanup worker would be the way to go.

**Comment by pudo** [comment]
I think there's a few data types that get marked deleted, rather than removing the rows (Collections, Roles, Alerts). Documents should be removed straight away.

**Comment by mattcg** [comment]
Is this still the case that when users delete personal/shared datasets, the files are left lying around? If so, will prioritise a PR for this.

**Comment by pudo** [comment]
That's a really cool idea! One of the stoppers on this for a long time was that the file system abstraction we've been using (servicelayer) didn't support deletion, but it now does: https://github.com/alephdata/aleph/blob/main/aleph/logic/export.py#L146 

So I guess the main thing that's missing is a refcounter.
