### ISSUE TITLE
Finalize helm chart

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#565]
Some ideas: 

* Move it to ``platform/helm``
* Name containers without the ``search`` prefix
* Make namespace configurable
* If we're going to switch over our prod site, we need to make sure there's a way of injecting the existing ES PVCs into the new config.
* I've added support for mlockall to our ES in prod, we almost certainly want that

**Comment by Ueland** [comment]
The ingress config should also get their hardcoded occrp.org-domains either removed or changed into config and/or templates somehow.

Example: kubefiles/core/ingress.yaml:15

**Comment by pudo** [comment]
Status update on this: there's a complete `helm` configuration in `platform/helm`, but I think it could do with a fair bit of simplification and contains some OCCRP-specific settings. Gotta review this a bit.

**Comment by pudo** [comment]
Calling it quits on this.
