### ISSUE TITLE
Instructions in wiki on Production Deployment aren't complete

### ISSUE THREAD

**Issue by rappdw** [alephdata/aleph#571]
Following instructions in [Production Deployment](https://github.com/alephdata/aleph/wiki/Production-deployment) doesn't result in a working system. 

```
curl http://localhost:8080/api/2/statistics
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

To get a system up and running I did the following for version 2.2.2:

1. Update `docker-compose.yml` and set all alephdata images to use tag version `:2.2.2`
2. `docker-compose -f docker-compose.yml run --rm shell aleph upgrade` (To initialize database, elasticsearch, etc.)

Once I did this I was able to successfully make requests

```
curl http://localhost:8080/api/2/statistics
{"entities": 0, "collections": 0}%
```

**Comment by pudo** [comment]
Thanks for pointing this out, Daniel! I've added the suggested step to the production manual: 

https://github.com/alephdata/aleph/wiki/Production-deployment
