### ISSUE TITLE
Group support in API

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#576]
The API should get support for some basic group features, like:
* Create|Update|Delete group(s)
* Create|Update|Delete user-group mapping(s)

I suspect that there should also be a way to search up a user, it does not appear to be that today. 

This should be in order to make it easier to make use of the group feature, without administrators having to implement their own group handling directly into the Aleph code itself.

Perhaps this should be added to the aleph client also?

**Comment by Ueland** [comment]
Reminder: Any update events needs to clear cached data with regards to this. Simply manually adding groups via Postgres shows that something is cached in the API-container.

**Comment by Ueland** [comment]
Reminder: Also check that cach is cleared when any updates are done, permissions changes directly in Postgres appears to not take effect before a restart of the API container.

**Comment by pudo** [comment]
Closing in favor of #1115.
