### ISSUE TITLE
Admin: Not possible to give permissions to collections i dont have edit permissions for

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#577]
As an admin, i have access to view all collections, but should it not be possible for me to give permissions to users even if i do not have edit rights? The GUI allows for me to do it, but the changes are not saved in the API.

Permissions are changed correctly if i work on a collection which i have edit permissions for.

So as an admin, i can demote and remove my edit access to a collection, but not recover it again.

**Comment by pudo** [comment]
Hm, weird. What you describe as desired behaviour is what I experience both on my local setup and in production, it's basically how permissions for anything are bootstrapped. Can you perhaps provide more detailed steps to reproduce? 

(It's surprising, too. Being admin basically hot-wires authorization entirely, so it's hard to conceive how any access rules would apply to an admin).

**Comment by Ueland** [comment]
I will try to recreate this issue and come back to you

**Comment by Ueland** [comment]
Testet in new and upgraded development environment, cannot reproduce.
