### ISSUE TITLE
archive.pudo.org (used in building aleph-extract-entities image) returns 404

### ISSUE THREAD

**Issue by rappdw** [alephdata/aleph#581]
```
Step 8/20 : RUN curl -s -o /tmp/polyglot.tar http://archive.pudo.org/aleph/polyglot/polyglot-data-201809.tar     && cd /opt/data     && tar xvf /tmp/polyglot.tar     && rm /tmp/polyglot.tar
 ---> Running in 8f17ba1c6c35
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```
![screen shot 2018-12-06 at 1 00 59 pm](https://user-images.githubusercontent.com/210863/49608867-184d7300-f957-11e8-8459-f660d5bc4ec9.png)

**Comment by pudo** [comment]
Sorry about this. It's fixed in ``develop`` which I'm hoping to merge tonight or tomorrow morning. I just got a $120 bill from AWS for hosting that file on my personal bucket and decided to hard-shift that to @occrp.

**Comment by rappdw** [comment]
I notice that the curl of polyglot.tar is commented out on the develop branch (with a comment "slow!"). Is this not required?

**Comment by pudo** [comment]
This is driving me mad. We're using both spaCy and Polyglot in 2.2 to do NER. spaCy is good for latin-based, European languages. Polyglot does Russian, Arab, lots of languages (35?). The theory is we'll look at what they find and merge it. However, Polyglot is a) unmaintained, b) leaking memory. For the thing not to die we need to run it with 4-5GB memory (spaCy is 500MB). So I'm oscillating on the judgement call to kick it out.
