### ISSUE TITLE
Xref.csv doesn't contain the xref'd collection

### ISSUE THREAD

**Issue by felixebert** [alephdata/aleph#591]
Affects the live-generated xref.csv file, linked on the xref-page of a collection.

A csv of collection 1027 on data.occrp.org contains a column named "MatchCollection", but this refers always to the same collection (the collection where you started the download, 1027) and is therefore not useful.

In collection 724 (US OFAC Consolidated List) the column "MatchCollection" does correctly refer to the xref'd collection, so i suspect that somehow the xref-direction seems to be switched on collection 1027.

**Comment by pudo** [comment]
I can't reproduce this, even with 1027. Since some of the underlying code has changed, I am going to assume this is closed. Please advise otherwise.
