### ISSUE TITLE
Entity tags API causes index to be hammered

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#603]
The `/api/2/entities/X/tags` API is called pretty routinely at the moment. What it does is to find all `names`, `addresses`, `phones` and `identifiers` linked to a particular entity and construct a search query for each of them to determine how many other mentions there are of this tag. For a long text document that has been processed with NER, this can easily add up to around a 1000 tags that are being queried.

The load caused by running these bulk queries is pretty substantial, and this is done even when a user only chooses to preview a thing in the UI. The results are mediocre, given that many documents are tagged with trivial entities like `European Union`.

Here's a few thoughts:

* We could exclude names, and only run this for strong identifiers like phones, emails etc. 
* Currently, the query to match a name is `match_query` to allow for cross-translit results. We could instead index names as transliterated keyword and do precise matching on this. 
* Could this be handled via the emerging graph API somehow?
* Can we cache this? (It is authz-dependent, so probably not super helpful)

Relevant code section: 

https://github.com/alephdata/aleph/blob/d644e5f8b956c7186a59f3ce1c16798017961765/aleph/logic/entities/__init__.py#L109-L152

**Comment by davo11122** [comment]
I would also suggest to not load whole tags on preview mode, having only the count of tags will be enough, in a nutshell implement lazy-loading for tags.

**Comment by pudo** [comment]
I've now refactored the API a bit to skip low-specificity cross-ref possibilities. I'm hoping that'll take off some load, but it's not a given.

**Comment by pudo** [comment]
Ok, it seems like this is not the key problem post #618. It's always going to be a performance-sensitive operation but seems to work more smoothly now.
