### ISSUE TITLE
Bulk entity mapping loads are prone to abort

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#604]
When aleph is instructed to load a mapped dataset (e.g. from a SQL or CSV data source) into OCCRP Data, it currently has a tendency not to complete the process. This is not an error in the software, but rather related to the fact that aleph's deployments are not suited for extremely long-running tasks (a large mapping may take 12 hours to load, and our preemptive nodes are more short-lived than that).

This could be addressed by introducing an additional queue buffer, where the mapping itself is generated without touching ElasticSearch and many child tasks are spawned to process the generated entities into the search index. This way each of the individual tasks would be short-lived.

The problem with doing this, however, is the way that RabbitMQ is designed: it's meant to store small messages, 16K max. So I'm not sure it can/should be used to store entity batches. Celery used to have a batch mode in 3.x, too, but that's been removed in 4.x.

**Comment by Ueland** [comment]
To avoid adding new components to the stack, this could be solved by first dumping every line in the source file into Postgres. Then having a task going by and picking X rows at the time from the todo-pile in Postgres. I have a similiar setup going through PubSub and that works splendidly.

**Comment by pudo** [comment]
I think we're also settling on a strategy that doesn't live inside of Aleph for the moment: basically we're using the command-line version of `followthemoney` to generate mapped entities, then store these to a local leveldb instance using `balkhash`. From there, we can export to JSON files, RDF or punch the stuff into alephclient and thus into the `_bulk` API. Here's the script, with credits to @uhhhuh:

```bash
#!/bin/bash

DATASET=$1
MAPPING=$2
JSON_OUT=$DATASET.json
RDF_OUT=$DATASET.rdf

ftm map $MAPPING | balkhash write -d $DATASET
balkhash iterate -d $DATASET -f $JSON_OUT
balkhash iterate -d $DATASET | ftm export-rdf > $RDF_OUT
gsutil mb -p occrp-data -c regional -l us-east1 gs://xxx_$DATASET
gsutil cp $JSON_OUT gs://xxx_$DATASET/entities/$JSON_OUT
gsutil cp $RDF_OUT gs://xxx_$DATASET/entities/$RDF_OUT
```

**Comment by pudo** [comment]
The external workflow seems to work much better. This raises the question whether we need to remove the built-in mapper long-term. But that's a separate discussion.
