### ISSUE TITLE
aleph command to delete data from Postgres

### ISSUE THREAD

**Issue by Ueland** [alephdata/aleph#605]
Another variant of #562.

Some data in Postgres are marked as deleted, instead of getting deleted. A command option in the aleph client would be nice to have in order to keep the database in tip top shape.

I might end up implementing this myself as i am doing it manually now, just making a note of it here.

**Comment by pudo** [comment]
It should be possible to just add a `.cleanup` staticmethod to `aleph.model.common:SoftDeleteModel` and then figure out the right order of classes to run it on (probably: `Alert`, `DocumentTag`, `DocumentRecord`, `Document`, `Collection`).
