### ISSUE TITLE
Factor out JavaScript-side FtM handling into TypeScript library

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#614]
This has already started, but the idea is to take all the functionality related to interpreting FollowTheMoney schema specifications across the Aleph UI app and to put it into a separate JS package written in TypeScript. This will then also be the foundation for the visualisations, including the network visualisation. 

Current impl: https://github.com/alephdata/aleph/tree/master/ui/src/followthemoney 

What we need at the minimum (not to sweat the specific naming, just in principle):

* `Model`
  * `get_schema`
  * `schemata`
* `Schema`
  * `name`, `label`
  * `is_a`, `schemata`, `descendants`
  * `featured`, `sorted` (properties)
  * `isDocument`, `isThing`
* `Property`
  * `type`, `name`, `label`
* `Node`
  * `type` / `id`

Probably the model also needs to be somewhat aware that it's in a specific language, so that users can change the language and the app realises it now has to load another model.

Then, let's put a `schema` object on each entity before we put it into Redux so that the schema functions are automatically available.

**Comment by pudo** [comment]
Fixed in #618 & #617

**Comment by pudo** [comment]
I think the notifications API is broken here, let's chat.

**Comment by dkhurshudian** [comment]
@pudo notification API issue is fixed in #619 PR
