### ISSUE TITLE
Misc UI issues (v. 3.0.0)

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#625]
Fixes: 

* [x] BUG: Cannot save collection access settings for some reason, state seems broken. 
* [x] BUG: Pressing "register" in the sign-in dialog crashes the app hard.
* [x] Remove relative imports 
* [x] Several errors in console saying `mapStateToProps` is returning `null`, not `{}`
* [ ] Sometimes the breadcrumbs for a deeply nested folder overlap the search and pile into two rows. Perhaps we should instead show only the last ~2-3 steps? Also, I think all the entity data is in `properties.ancestors` - are you aware? 
* [x] For all the places where we show counts, can we enable the CSS setting that makes numbers fixed-width? (`font-variant-numeric` I think).

Features:

* [x] Can we make a button `Browse` in the CollectionToolbar which just points to `/collections/X`? With a little folder icon?
* [x] I'd really like to show an additional section on the home page, but I don't know where. When a user is not logged in, this should just be a nag-bar, saying "Please sign in to see more ....". When the user _is_ signed in, I would like to include (in `/api/2/statistics`) all the groups they are part of. So then, when you are signed in, the new section would say: here's all the security groups you are part of, click one of them to see the associated collections.

**Comment by dkhurshudian** [comment]
>Sometimes the breadcrumbs for a deeply nested folder overlap the search and pile into two rows. Perhaps we should instead show only the last ~2-3 steps? Also, I think all the entity data is in properties.ancestors - are you aware? 
In my opinion it's better to have the whole ancestors shown in the breadcrumbs. 
Also I couldn't access the `properties.ancestors` any extra steps to get the data?

**Comment by dkhurshudian** [comment]
## signed in
![image](https://user-images.githubusercontent.com/3075886/53811449-e1492680-3f72-11e9-9a35-ac808507d13b.png)
## not signed in
![image](https://user-images.githubusercontent.com/3075886/53811480-f02fd900-3f72-11e9-8715-f7b5b491f11b.png)
