### ISSUE TITLE
Installation Error. 

### ISSUE THREAD

**Issue by rwer81** [alephdata/aleph#630]
Hi ,
I try to install aleph following instructions(make build). After many successful steps, installation process hangs on step:
--> fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
After long waiting, I canceled command. Then I run 'make build' again but output:

.....
.....
Sending build context to Docker daemon  11.78kB
Step 1/11 : FROM alpine
 ---> caf27325b298
Step 2/11 : RUN apk update && apk upgrade &&     apk add --no-cache python3 libstdc++
 ---> Running in 3b7f834d9cc5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.b89edf6e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
2 errors; 14 distinct packages available
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.9/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.737f7e01.tar.gz: No such file or directory
The command '/bin/sh -c apk update && apk upgrade &&     apk add --no-cache python3 libstdc++' returned a non-zero code: 2
make: *** [build] Error 2

Thank you.

**Comment by pudo** [comment]
Hey @rwer81! It looks like you're installing aleph! We're just about to release a major revamp of the backend so you might want to run on `develop` right now, which is going to become `master` and `3.0.0` some time tomorrrow!
