### ISSUE TITLE
Add lead list excel export to entity view

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#64]
Offer a download option to fetch adjacency lists for all the entities and documents in a particular collection. This should have a sheet for each entity type, links where available and as much provenance as we can rustle up.

**Comment by jbothma** [comment]
what do you ve in mind in terms of provenance?

**Comment by pudo** [comment]
I guess this could start out at a serialisation of the ``Path`` domain object, with the various steps of the path and all the properties of the start and end nodes. This also then includes the "end_collection" for provenance -- or did you mean something more specific?

**Comment by jbothma** [comment]
as Friedrich suggested, could do this by making current export logic more generic https://github.com/pudo/aleph/blob/master/aleph/views/exports_api.py
