### ISSUE TITLE
Previewing emails in 3.0.0 not working.

### ISSUE THREAD

**Issue by automatingosint** [alephdata/aleph#642]
When clicking on an email that has been processed (countries and date extracted) causes a blank screen and a React traceback. 

<img width="1664" alt="Screen Shot 2019-03-16 at 8 37 08 AM" src="https://user-images.githubusercontent.com/12143192/54476768-be1a4480-47c6-11e9-8474-01062145f285.png">

**Comment by dkhurshudian** [comment]
@automatingosint thanks for letting us know, this issue is fixed now in #643 PR, and will be available in next release.
