### ISSUE TITLE
Make facets configurable

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#647]
As a user, I want to be able to add or remove facets on the main search. There are two types of facets: `group` facets (such as `names`, `phones`, `ibans` and `property` facets (such as `BankAccount.bankName`). Both should be selectable from a menu or drop-down.

**Comment by kjacks** [comment]
- Remove final three facets (names, addresses, file types)
- Create button to add additional facets at bottom of list
- Additional facets dialog allows to select from property groups and maybe properties (from ftm model)
- search bar to find facets
- facet choices do not persist

**Comment by jbothma** [comment]
Is the thinking here that a user can select which facets to include (perhaps with some sane defaults) when they're logged in?

So not something that's configured system-wide?

Perhaps the defaults could be defined system-wide by an admin.
Perhaps an admin could completely disable some that don't make sense for a particular installation?

What is your Must, Could, Should, Would of these sub-features?

**Comment by pudo** [comment]
Yes, I like that proposal: admin sets default facets, user then has a little "add" button (maybe optional) that they can use to pull in more facets as needed.

**Comment by lucmichalski** [comment]
I have a suggestion for managing many regexes for facets, it is to use http://github.com/intel/hyperscan with its python wrapper https://github.com/darvid/python-hyperscan.
