### ISSUE TITLE
make upgrade: Elasticsearch exception

### ISSUE THREAD

**Issue by msat-cont** [alephdata/aleph#669]
ES 7.0 does not start during "make upgrade" (developer setup) due to an exception:

```
"2019-05-24T09:40:02,122+0000", "level": "WARN", "component":
"o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name":
"docker-cluster", "node.name": "elasticsearch",  "message": "uncaught
exception in thread [main]" ,
elasticsearch_1     | "stacktrace":
["org.elasticsearch.bootstrap.StartupException:
ElasticsearchException[Failed to create native process factories for
Machine Learning]; nested:
FileNotFoundException[/tmp/elasticsearch-17583908043322914660/controller_log_1
(No such file or directory)];",
elasticsearch_1     | "at
org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163)
~[elasticsearch-7.0.0.jar:7.0.0]",
...
```
It seems to be the same exception as the one seen at:
"Cannot start ES 7.0.1 on Fedora 30 unless "xpack.ml.enabled: false" is set #41867"
https://github.com/elastic/elasticsearch/issues/41867
possibly resolved by installing libxcrypt-compat

Notice that I have set sysctl -w vm.max_map_count=262144

**Comment by pudo** [comment]
I'm not sure that we can provide meaningful support with this, it looks a bit like an upstream problem with ElasticSearch - our use of it is pretty standard. Is there more to this error message?

**Comment by msat-cont** [comment]
Hi, sorry for a late answer, am doing this as a sidewise stuff (for testing the suitability of aleph for a project of ours) and the main work takes the most of my time.

I've thought that you use your own image of Elasticsearch, that is
`alephdata/aleph-elasticsearch:10`
and that by that you set the OS and specify the ES options.

Regarding the errors, am adding it as attachments. Even though I have a feeling that it was telling `Connection refused` initially, it states `Name or service not known` by now.
[make_upgrade_001.txt](https://github.com/alephdata/aleph/files/3233302/make_upgrade_001.txt)
[logs_elasticsearch_001.txt](https://github.com/alephdata/aleph/files/3233304/logs_elasticsearch_001.txt)

**Comment by msat-cont** [comment]
BTW It would be cool if you could comment on the issue, e.g. whether it works correctly for you with the current Elasticsearch version. I mean that if doing the make build/upgrade works for you, I have to look for a solution by myself. If contrary to it, it does not work for you, I guess that even you need to find a solution.

**Comment by pudo** [comment]
This is super strange. The docker image you point at is a minimal configuration for elasticsearch documented here: https://github.com/alephdata/aleph-elasticsearch 

I've just re-built that image and pushed it, but it apparently did not change. So there's no changes available upstream, either. We can try upgrading this to ES 7.1.0 but they're quite amazing at breaking upstream features.

Is there anything exotic in your environment? Can you shut down aleph with `make stop`, then run `docker system prune -af` and check your disk space is above 10G?

btw. all the errors in `make upgrade` are because ElasticSearch is not up.

**Comment by msat-cont** [comment]
Hi, thanks for looking at it.
My environment is a common Xubuntu 18.04 64b desktop system.
Free disk space on the system is fairly over 100G.
I'll try to look at your ES system config during the week.
With some luck, I only did something dumb.

**Comment by msat-cont** [comment]
I've just tested ES docker image itself, according to:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
and I get the same error.
Thus apparently something wrong on my system, though having no idea what it should be.
I'll ask them, since it is apparently not related to Aleph.

PS When I run ES without docker, it runs for me.

**Comment by msat-cont** [comment]
Hi, the issue is caused by requirement of Intel's SSE4.2 for ES's ML part. The machine where I had tested is an AMD one with SSE4a only (while SSE4.2 was already in Intel machines then, it was not on AMD ones yet). When I tried it on a (newer) Intel machine, it ran well.

**Comment by pudo** [comment]
This is weird as hell. Anything we can do?

**Comment by msat-cont** [comment]
Well, either to leave it for just computers with SSE4.2 (may be to mention it somewhere), or possibly provide an additional version with `xpack.ml.enabled: false` at `/etc/sysconfig/elasticsearch` (generally at the file that is used as config for ES) if those somewhat older computers are expected to be used.

Notice that for computers without SSE4.2, it is not sufficient to install `libxcrypt-compat` that is actually necessary on some systems (unsupported by ES), see: https://github.com/elastic/elasticsearch/issues/41867
