### ISSUE TITLE
Whats our plan for rendering CSV in the UI?

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#677]
So we're switching the way that tabular data is stored in aleph from `followthemoney` entities to having a CSV file that is output and stored. That means we need to be able to preview tabular data on the basis of the CSV file. Two methods come to mind: 

* Parse in JavaScript from URL data. There seem to good CSV parsers for JS, e.g. [PapaParse](https://www.papaparse.com/), but their default premise is that we can load the full file. We don't want that, at most we want to load maybe 1000-10000 rows of data for a preview.
* Or, we could write a backend proxy that reads the CSV from archive storage and converts it into a paged pseudo-API that produces a JSON representation. 

We also need to make a call on whether we treat tables as all having headers, or headers as some sort of optional extra.

**Comment by pudo** [comment]
@sunu The parser in #680 isn't working in production because of CORS. It turns out that range queries are severely restricted by CORS and I cannot figure out how to convince either the UA or GCS to make an exception for us. We might have to either return to the previous model, introduce an interim proxy, or maybe you can have another look at the CORS settings for GCS?

**Comment by sunu** [comment]
Ok, I'll see if I can figure something out for the CORS settings.

**Comment by pudo** [comment]
Declaring this to be working unless otherwise proven :)
