### ISSUE TITLE
Split queue processes into jobs

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#678]
This will need to be implemented in `servicelayer`. We need to have an abstraction between the current notions of `dataset` and `operation` that allow us to manage all the tasks belonging to a particular load action being executed on a particular dataset. This way we can also relatively cleanly remove test mappings again.

**Comment by sunu** [comment]
We are going to show status grouped by `job`, right? Should we record the job start time as well?

**Comment by pudo** [comment]
I agree status should be as granular as it comes out of the backend. Where would you put the start time, in an extra field? I assume this makes memorious more rich?

**Comment by sunu** [comment]
I want to use the start time in 2 places: to list Memorious start times and may be to list Aleph data loading jobs in a reverse chronological order. I'm using a list to store the latest 10 runs and their start time for each dataset. Just a list is enough for retaining the order but I guess we need the time for Memorious anyway.

**Comment by pudo** [comment]
[ This is being implemented in https://github.com/alephdata/servicelayer/pull/3 ]

**Comment by pudo** [comment]
This was fixed in 3.2.5
