### ISSUE TITLE
[SimSec] Sign in suggestion banner

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#696]
- (+/-) Clicking on this banner leads to the sign-in screen.
    Current undismissable banner warning anonymous users that they are not signed in.
    However, this isn't made obvious by any on-screen cues. Suggestion: underline or bold the words "sign in," or make "sign in" into a button. [Heuristic(s): Help users recognize, diagnose, and recover from errors; User control and freedom]

- For many users, signing in may not actually get them access to data that they care about. They may also have security reasons for browsing anonymously rather than signing in. The banner takes up valuable real estate at the top of the screen and may not be relevant to all users. Suggestion: instead of an alert bar, which looks like an error state, add a one-time notification. 
If the user continues to search without signing in, a dismissable notification could be shown once.

**Comment by kjacks** [comment]
- add x to dismiss
- change from whole banner clickable to just sign in text

**Comment by pudo** [comment]
Fixed in #720.
