### ISSUE TITLE
Search tips box for advanced search documentation

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#697]
+/-) The documentation explaining the searching language is thorough and clear, with good examples. In particular, the section on "Spelling errors" is highly applicable to these datasets and would be very useful to beginning users. However, this help is difficult to locate. 

Suggestion: have a "tips" section that is targeted towards users, not developers, and has a link in the top toolbar. Also, surface these tips in the home screen. [Heuristic(s): Help and documentation]

**Comment by kjacks** [comment]
- add general search tip banner below search bar at the bottom of search history suggestions list
- will link to help screen (when created)

**Comment by pudo** [comment]
See also #710 :)

**Comment by kjacks** [comment]
<img width="878" alt="Screenshot 2019-08-28 at 15 00 20" src="https://user-images.githubusercontent.com/6720200/63857783-9d286300-c9a4-11e9-9908-745c076faa76.png">
