### ISSUE TITLE
[SimSec] Search Results - Collapsing of filter categories

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#699]
- When the user clicks on "sources," the filter panels are no longer collapsible. I'm not sure if this is by design or whether it's a bug. [Heuristic(s): Consistency and standards]
(dropdown arrow provides additional confusion)

- Clicking the X in the title bar of a filter panel when results are filtered looks like it would collapse the list, but instead it removes the filter. As in an OS, anything in the title bar seems like it should manipulate the panel element itself, rather than having an effect on the search results. [Heuristic(s): Consistency and standards]

**Comment by pudo** [comment]
See also #647.

**Comment by kjacks** [comment]
- remove dropdown arrow from sources facet titles
- remove X in title bar of facets -> just show the count at all times
- clear filter functionality will be handled by #711
