### ISSUE TITLE
[SimSec] Search Results - Icon selected state

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#702]
(-) Until a filter is applied and the user sees a clear difference between grey and blue checkmarks, it is not clear that the grey checkmark means "not shown." Suggestion: remove the grey checkmarks. [Heuristic(s): Visibility of system status]

- It's not clear that clicking the √ next to a filter will remove it, especially since the other way to remove a filter involves clicking an X. Suggestion: use X exclusively for removing a filter. [Heuristic(s): Consistency and standards]

**Comment by kjacks** [comment]
change grey checks to grey bullets, keep blue check mark for selected

**Comment by pudo** [comment]
Fixed in #719.
