### ISSUE TITLE
[SimSec] Icon Disambiguation

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#703]
- The icon for "types" and the icon for "categories" are the same. [Heuristic(s): Consistency and standards]

-  Icons are only useful when they help distinguish things from each other, and some of the icons are very close to each other but mean confusingly different things. Suggestion: make the entity and filter icons more distinct from each other. For example, entity icons could all appear light-on-dark in a circle or rounded rectangle. [Heuristic(s): Aesthetic and minimalist design; Consistency and standards; Recognition rather than recall]

- (-) Many of the different "entity" icons look similar. Suggestion: don't use any "stack of papers" icons at all. Focus on the type of information contained within the stack of papers. In general, the icons that don't have the "stack of papers" are clearer than those that do. [Heuristic(s): Aesthetic and minimalist design; Consistency and standards; Recognition rather than recall]

**Comment by kjacks** [comment]
- look for different icon for types or categories
- will do icon review/ redesign later

**Comment by pudo** [comment]
Looking for a designer to implement a new set of entity icons: 

https://docs.google.com/document/d/1aYx7F4U_yc-v76WU62GfEdTKnAE10JSbnzxcW3rGCs4/edit#heading=h.9scdm1e7hkka

**Comment by pudo** [comment]
Fixed in #719.
