### ISSUE TITLE
[SimSec] Search Results - Hiding of non-selected filters

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#704]
When a user applies a filter, then would like to apply another filter from the same category, they need to first remove the first filter. This may be a technical barrier, but if it's possible, it would be more intuitive to show all filters, whether they're selected or not, when the filter panel is opened. [Heuristic(s): Flexibility and efficiency of use]

**Comment by kjacks** [comment]
- Kirk will research way to distinguish multi-select from single select facets

**Comment by pudo** [comment]
Addressed in #719.
