### ISSUE TITLE
[SimSec] Search Results - Export button inconsistency

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#705]
(-) The Export button is always visible, but is sometimes available, and sometimes disabled. The user isn't provided with any information about why they can sometimes export the list, and sometimes can't. I'm not sure about the technical reasons here, but my guess is that some lists are just too big. Solution: either don't show the Export button when it's not usable, or better still, provide a message on hover letting users know WHY Export isn't available.  [Heuristic(s): Visibility of system status; Consistency and clarity]

**Comment by kjacks** [comment]
- add tooltip explaining "Cannot export more than 10,000 results at a time" on disabled state

**Comment by pudo** [comment]
Fixed in #719.
