### ISSUE TITLE
[SimSec] Collection/Entity Toolbar

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#707]
- There are three labels close to each other in the source drawer that appear similar but actually mean different things. Two of them are buttons, one is a label, but they all look the same.
Suggestion: Remove **Source**, because the rest of the interface makes it quite clear that the user is looking at a database, not a single record. [Heuristic(s): Aesthetic and minimalist design]

- The **Browse** button ****is not very descriptive, because what the button actually does is expand all the current content into an easier-to-view full-screen view. Suggestion: use wording like **Open** or **Expand**, with a matching icon**.** [Heuristic(s): Visibility of system status, Match between system and real world]

- The Search button is also not very descriptive, because what the button actually does is open a list view with entities that are then filtered by belonging to the current source. This then allows further filtering, but it doesn't allow searching. The way to search within the source is actually to click Browse and then to search within the source using the search bar in the upper right. Suggestion: change the name to Add filter. This probably needs a custom icon. [Heuristic(s): Match between system and real world]

**Comment by kjacks** [comment]
- hold for future larger redesign of this element

**Comment by pudo** [comment]
I think we're done with this :)
