### ISSUE TITLE
[SimSec] Make source privacy and last updated status more clear

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#709]
Feedback from user interviews:

Unclear whether sources are available elsewhere or exclusive to OCCRP
Unclear whether sources are private or public
Unclear whether sources are housed within OCCRP
If they are: is it a recent version, or is the version located elsewhere more authoritative?
Unclear whether sources are verified or changed
Unclear when sources were last updated (does date refer to the entity, or the source?)

**Comment by kjacks** [comment]
- wait for Nadine mockups

**Comment by pudo** [comment]
I think this is resolved in 3.8.2
