### ISSUE TITLE
Import docs from Dropbox

### ISSUE THREAD

**Issue by jbothma** [alephdata/aleph#71]
would be really nice if this integrated with aleph with a pluggable interface, perhaps part of the crawler API, so that a crawler can expose UI that becomes part of the collections interface. Then I could create a collection, select from e.g. a gdrive or dropbox crawler, use oauth to connect to my account and select the folder I want it to crawl

**Comment by jbothma** [comment]
Just had a quick look at the first online example site with integrtion with dropbox and it took full dropbox access which is pretty horrid. I'd prefer to only give permission to specific folders. It looks like dropbox can get access to an **App Folder** and/or  **File Chooser** and the latter doesn't need to get **Production Approval** https://www.dropbox.com/developers/reference/developer-guide#app-permissions

**Comment by jbothma** [comment]
google drive also seems to have an app folder, and https://www.googleapis.com/auth/drive.file "_Per-file access to files created or opened by the app_" but the latter didn't seem able to list a directory so it doesn't seem quite like the dropbox **chooser**.

The downside of full drive/box access is trust.

The downside of app folders is potentially using more disk space because the user might want to copy stuff to the app folder and also keep files in their usual file structure.

So I'd say the ideal model for Dropbox is the chooser, and hopefully I misunderstood the google drive API and it has something similar to chooser.
Any comment or preferences?

**Comment by jbothma** [comment]
ah, the metadata.readonly permission allows listing folders, but I guess one would have to do that from root, which is basically full readonly permission anyway, isn't it?

**Comment by pudo** [comment]
I think we'd be perfectly fine just starting off with Dropbox support, I know more reporters who use this for file storage than GDrive. The Chooser looks like an exact match for our needs -- my sense would be to add this to the collections feature and to store any generated metadata alongside a specific collection. Then we can have a crawler in the background which uses the collection's metadata to resume an OAuthed session for scheduled (daily? hourly?) crawls.

**Comment by jbothma** [comment]
No progress to report here, unfortunately. We currently need an external processing step for the docs we put into aleph and our user-provided doc use case is satisfied by documentcloud.

**Comment by pudo** [comment]
This doesn't seem to be happening, closing.

**Comment by jbothma** [comment]
Yup, Sorry about that. Ended up not getting prioritised on this end so
didn't happen. Thanks for closing.
