### ISSUE TITLE
Facet count disappearing bug

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#712]
When one facet value is selected, facet counts in title bars of other facets disappear

**Comment by kjacks** [comment]
@pudo I think this bug is occurring in the api - where the /entities endpoint returns null facet totals for other facets when an individual facet value is selected

(when no facet value is selected)
<img width="306" alt="Screenshot 2019-07-11 at 16 23 22" src="https://user-images.githubusercontent.com/6720200/61064626-7026ed80-a402-11e9-993b-67975d19df47.png">

(when a facet value is selected)
<img width="301" alt="Screenshot 2019-07-11 at 16 23 32" src="https://user-images.githubusercontent.com/6720200/61064634-74530b00-a402-11e9-9add-d38592b98381.png">

**Comment by pudo** [comment]
Outch. Clearly a backend issue, gonna look into it!
