### ISSUE TITLE
[SimSec] Document view when no search term present

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#713]
(+/-) When a user searches for a certain phrase, that phrase is then highlighted in search results, which makes sense. However, it is not always immediately clear why a document has shown up in search results. That's not in itself a problem, but the interface should give users the opportunity to look at the document for themselves. In the example below, the document is not even viewable because the text doesn't match the search terms. Suggestion: give users the option to view the document, regardless of their search terms. [Heuristic(s): Flexibility and efficiency of use; User control and freedom]

**Comment by kjacks** [comment]
Solution: show first page by default if no match for search term found

**Comment by pudo** [comment]
Fixed in `develop`.
