### ISSUE TITLE
Date range API spec

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#721]
For an upcoming interactive, we need to support the filtering and faceting of date values. This ticket will serve as a place to discuss the API for this, which might also serve as a template of similar advanced filters for other data types (i.e. numbers). 

Current filters:

`?filter:collection_id=2000`

Date fields: 

`dates`, `properties.startDate`, `properties.date`, `properties.birthDate`  etc. 

Filter pptions:

* `?filter:ge:properties.startDate=2001&filter:le:properties.startDate=2007`
* `?filter@ge:properties.startDate=2001&filter@le:properties.startDate=2007`
* `?filter!ge:properties.startDate=2001&filter!le:properties.startDate=2007`

Facet options:

* `?facet=properties.startDate&facet_interval.properties.startDate=month` or `?facet=properties.startDate&facet_interval.properties.startDate=day`

We already have similar facet options, like `facet_size:schema=20` and `facet_total:schema=true`.

What does the most extendable and intuitive approach for this look like?

Refs #288.

**Comment by kjacks** [comment]
For the histogram referenced in #288 - would the lowest level of granularity be years?  Or would there be cases where we would want to filter within a year?

In this system, I'm guessing filtering for an exact year (i.e. 2001) would still look like 
`?filter:startDate=2001`

Otherwise the filter formats presented seem roughly equivalent to me

**Comment by jbothma** [comment]
I have a case where I'd like to see

- number of documents published per year/month 
- number of documents published per year/month in given collection
- number of documents published per year/month containing the given named entity

I'll let you know when I'm back on Aleph to help justify/build it.

**Comment by pudo** [comment]
Fixed in #1229.
