### ISSUE TITLE
Can't download the Aleph ZIP file 

### ISSUE THREAD

**Issue by dekomomo** [alephdata/aleph#730]
When doing it Windows flagged it as a virus.

Thanks in advanced.

**Comment by pudo** [comment]
I think this has to do with one of our test fixtures which some virus scanners tag as a virus. It's not, but they are trained to see it still. In any way, it should be safe. Does your virus scanner tell you which file it's got its eyes on? It should be one of these: 

https://github.com/alephdata/aleph/tree/master/services/ingest-file/tests/fixtures

**Comment by pudo** [comment]
Closing because reporter is unresponsive.
