### ISSUE TITLE
Landing page redesign (unauthenticated)

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#740]
<img width="568" alt="Screenshot 2019-08-28 at 15 22 02" src="https://user-images.githubusercontent.com/6720200/63859417-9bac6a00-c9a7-11e9-96c4-240261139796.png">

Would follow above design, except:
- maintain entity count preview from current home page
- different background image?
- move "Learn more about aleph" to its own section

**Comment by pudo** [comment]
Edin's assets: 

![Screens3_UploadDocuments](https://user-images.githubusercontent.com/41628/89528393-3eda4600-d7eb-11ea-8dd5-9d864289568c.png)
![Screens3_TrackAlerts](https://user-images.githubusercontent.com/41628/89528399-400b7300-d7eb-11ea-83c7-ec2f907339fe.png)
![Screens3_SketchNetworks](https://user-images.githubusercontent.com/41628/89528400-400b7300-d7eb-11ea-8d94-9b68c335b143.png)
![Screens3_SearchRecords](https://user-images.githubusercontent.com/41628/89528401-40a40980-d7eb-11ea-93cb-84ccb3f81f8d.png)
![Screens3_AccessDatasets](https://user-images.githubusercontent.com/41628/89528403-40a40980-d7eb-11ea-8605-4e1a2658b9b1.png)
![Screens3_CrossReferenceFindings](https://user-images.githubusercontent.com/41628/89528404-40a40980-d7eb-11ea-8883-a4b69e7e5324.png)
