### ISSUE TITLE
Entity view - remove "Tags" list

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#742]
Currently the Tags list in the entity screen is used to convey two different types of information:
1. entities that share the same property value for a given property with the current entity
2. entities mentioned within a text document like a pdf or email

<img width="1161" alt="Screenshot 2019-08-28 at 15 27 27" src="https://user-images.githubusercontent.com/6720200/63860019-af0c0500-c9a8-11e9-9c9e-a12214155503.png">

For use case 1 -> annotate the entity metadata property listing itself to allow users to view entities with the same property value.  Something like: "2 related entities" that, when clicked, brings users to the current tag search results page

For use case 2 -> rename from "Tags" to "Mentions"

**Comment by pudo** [comment]
Done in 3.3.0
