### ISSUE TITLE
Sitewide vocabulary changes

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#743]
<img width="596" alt="Screenshot 2019-08-28 at 15 36 00" src="https://user-images.githubusercontent.com/6720200/63860522-94865b80-c9a9-11e9-8438-c77609464bfc.png">

**Comment by kokoroko2** [comment]
I would love to see the first two suggestions implemented. Today I showed Aleph to a friend and he was very confused exactly about the concepts of Sources and Cases. 
Regarding the concept of Entity, I believe it is part of the job to understand that there is a database behind and an ontology. So I'm dont know if I agree.
