### ISSUE TITLE
Homepage counter not updating

### ISSUE THREAD

**Issue by kokoroko2** [alephdata/aleph#744]
I have uploaded many entities and documents, but the homepage counters do not update. What am I doing wrong?
![aleph](https://user-images.githubusercontent.com/54646945/63893891-ad9b0680-c9c1-11e9-9bd2-d52d6a28372f.png)

**Comment by kokoroko2** [comment]
![aleph2](https://user-images.githubusercontent.com/54646945/63893946-cefbf280-c9c1-11e9-82d6-140903003d27.png)

**Comment by pudo** [comment]
The numbers on the home page are cached, usually for an hour. If you want to force an update, run the following commands:

```
make shell
$ aleph update
```

**Comment by kokoroko2** [comment]
Hi Pudo! 
I had already forced the update, but realized it wasnt enough.
The counters only updated for me when I logged out and logged in again. 
Something about the cache in Chrome. When accessing as a visitor, a Ctrl + f5 is not enough. I have to open a new incognito window to see the numbers updated.
Thanks for the help. Congratulations on the project. 
I hope to start collaborating with the python part when I understand the architecture.

**Comment by kokoroko2** [comment]
I also need to logout/login to see changes to Tags in a document (after aleph update).

**Comment by pudo** [comment]
That's surprising to me -- login/logout has very little to do with the tags function. Can you make sure that it doesn't refresh if you just hit the reload button in your browser?

**Comment by kokoroko2** [comment]
Yes.. Closing because it appears to be a problem with my browser configuration, because it works with incognito window...
