### ISSUE TITLE
Ingestor not processing the zipped XLSX 

### ISSUE THREAD

**Issue by kokoroko2** [alephdata/aleph#745]
When I upload a .zip file that contains an .xlsx inside, its spreadsheets are not extracted. 
(If I upload only the Xlsx file, the spreadsheets are extracted normally.)

**Comment by pudo** [comment]
Interesting failure. I just tried to reproduce this with a random file from my desktop and it worked alright: 

```
DEBUG:aleph.logic.processing:Index: <E('249','Reyestr 2011.xlsx.zip')>
DEBUG:aleph.logic.processing:Index: <E('c93d8ef147eba8e1d77762c92a85ffc07bf36a01','Reyestr 2011.xlsx')>
DEBUG:aleph.logic.processing:Index: <E('370d653fc4fc4ac20804dad2de0a80eec3ab5693','Protokol')>
DEBUG:aleph.index.util:Bulk write: 0.4242s
```

Can you perhaps post some of your output from the aleph worker and ingest-file container?

**Comment by pudo** [comment]
Not enough information to reproduce, closing. Please provide additional information so that we can debug properly. Thanks!
