### ISSUE TITLE
Cant find the list of document types with support for Tags generation

### ISSUE THREAD

**Issue by kokoroko2** [alephdata/aleph#746]
Only application/pdf and plain/html documents generate Tags?
I am trying to upload some small texts (text/plain) and it doesnt generate tags.

**Comment by pudo** [comment]
Entity extraction will be run from each type of entity that has a `text` type field. This includes plain text documents, emails, PDF files etc. Those extracted names aren't all shown in the "Tags" section by default, though -- they only pop up there if there's at least one other document (or entity) that mentions them. The goal of the tags thing is to show connections, not just extracted names :)
