### ISSUE TITLE
Bug in language identification

### ISSUE THREAD

**Issue by moreymat** [alephdata/aleph#750]
I have a collection of monolingual documents for which the identified language is always wrong (but always the same language).
I was able to reproduce this behavior locally with pyfasttext, providing the same text and getting the same wrong language.

The official fasttext package (https://pypi.org/project/fasttext/) won't accept this text as is though because it contains newlines.
When I replace newlines with a regular space, I get the right language.
When I split the text on newlines, the first line is predicted to be of the same wrong language pyfasttext was returning.

I see at least two possible fixes :
1. Keep pyfasttext and replace newlines, for example with whitespaces:
```python
langs = settings._lang_detector.predict([text.replace('\n', ' ')])
```
2. Or drop pyfasttext that is no longer maintained in favor of the official fasttext package, and replace newlines with an almost identical call:
```python
langs = settings._lang_detector.predict(text.replace('\n', ' '))
```

**Comment by sunu** [comment]
Thanks for filing the issue. I hadn't realized pyfasttext was not the official package. Switching to the official package definitely makes more sense to me.

**Comment by pudo** [comment]
Fixed.
