### ISSUE TITLE
User & Group Management in UI

### ISSUE THREAD

**Issue by felixebert** [alephdata/aleph#755]
It shouldn't be necessary to use the command line for managing users & groups in aleph. Therefore it should be implemented in the UI of Aleph, for Admin-Users only.

related: https://github.com/alephdata/aleph/issues/576

**Comment by pudo** [comment]
For what it's worth, Aleph 3.3 introduces a `groups_api` and pages in the UI for each group. That should make it relatively simple to implement the remaining CRUD operations and UI.

**Comment by pudo** [comment]
Closing in favor of #1115.
