### ISSUE TITLE
Refactor the mappings API 

### ISSUE THREAD

**Issue by sunu** [alephdata/aleph#762]
We want to enable our users to define mappings for `Table` entities. The defined mappings can be used to generate FtM entities out of the table content and users can easily cross reference them against other collections.

- Each `MappingQuery` will be against a single `Table` entity. No joins allowed.
- Each `MappingQuery` created by the user will be stored in the db
- We need to assign an ID to each saved `MappingQuery`, and allow users to retrieve all the mappings for a `Collection`, and all the mappings for a `Table`; and perform CRUD operations. API endpoints will look something like:
`/api/2/collections/XXX/mappings`
`/api/2/collections/XXX/mappings?filter:table=YYY`
- Needs a “trigger” operation to start loading entities.
  - Need to be able to stream from own archive
  - Does the table have headers (csv headers)? (Let a UI flag tell us -- is first row a header?)
- Needs a “unload” operation to delete all the loaded entities
- Each FtM entity generated by the mapping gets a `proof` property pointing to the `Table`.
- We will need a new database table, a new view controller. Database schema will look roughly like: `mapping_id`, `collection_id`, `table_id`, `entities_query`: JSON BLOB

We may get rid of the existing mapping API afterwards.

**Comment by pudo** [comment]
Landed in develop :)
