### ISSUE TITLE
[UI] Login to upload tooltip on dataset button obstructs login in datasets page

### ISSUE THREAD

**Issue by DavidLemayian** [alephdata/aleph#769]
The "New Dataset" button is really close to login one in the datasets page so when your cursor is headed that way to log in, it hovers over the former obstructing the latter with no way to dismiss.

Perhaps click to dismiss might solve this?

![image](https://user-images.githubusercontent.com/877919/66125783-8fdc4500-e5f0-11e9-9e70-0199e19cc3da.png)

**Comment by pudo** [comment]
Turns out this has to do with the fact the button is disabled. Good to know.
