### ISSUE TITLE
Body text of msg messages rendered in wrong charset

### ISSUE THREAD

**Issue by anderser** [alephdata/aleph#809]
When uploading Outlook `.msg` files with Norwegian text, the body of the email shows up in Aleph UI with chinese symbols. Probably some wrong encoding guessing based on the `.msg` file.

The language is detected correctly by Aleph as Norwegian, and the encoding shows up as utf-16-le

This seems to only apply to emails with html body, not pure text body emails. 

Enclosing an example `.msg` file which shows up with chinese characters in body.
[test.msg.zip](https://github.com/alephdata/aleph/files/3752585/test.msg.zip)

**Comment by pudo** [comment]
Fixed in 406f7d10826228381086353acb85eebd9b0cd520
