### ISSUE TITLE
Sign In doesn't work in a new production setup

### ISSUE THREAD

**Issue by josreijers** [alephdata/aleph#822]
Hi,

I have used the docs.aleph.org site to create a production server and we went through all the steps successfully. Now we want to load data and there we need to sign in. however that button doesn't work at all. so either I missed something completely or there is something that needs a fix.

To produce;
1) Go to  http://51.144.6.159:8080
2) Click right upper corner on Datasets
3) Click on sign-in

Any help for a newbie :)

**Comment by josreijers** [comment]
Thanks! I rebuild the stuff and now the login prompts works. However after adding a use though the docker compose command I cannot login. In order to create user you needs to have mail server , which I don't have and don't want to use. Is there an admin panel? Sorry again for the newbie question. This isn't a bug of course but a configuration issue.

**Comment by pudo** [comment]
There isn't really a workaround to the config issue per se, but the server prints the token link that's in the email to its API server logs. So you can just fish it out of there and open it to confirm an account, that's sort of why I do in development. Does that work/make sense?

**Comment by josreijers** [comment]
That’s one way. But how do I load a case file without credentials?

**Comment by josreijers** [comment]
Hi Friedrich,

Getting the activation link in the API log does the trick,

Regards,

Jos

**Comment by pudo** [comment]
Ok, assuming this is fixed, otherwise re-open.

**Comment by josreijers** [comment]
Yes. Really appreciated the help.
