### ISSUE TITLE
Issues creating user and installing Aleph

### ISSUE THREAD

**Issue by OSINT007** [alephdata/aleph#876]
Hello,

I am trying to create a user under shell. I tried to do a copy and past from the Aleph website, but it tells me missing Foreign ID. Now, I went to the help menu and then known the options, I ran the following:

`root@aleph:/aleph# aleph createuser --name john smith --email john.smith@example.com --is_admin  --password 1234567`

I don't know what to put after -i. I am really trying to install this, but I am not familiar with python or any coding. I keep getting an error message. I'm stuck here...I can't log into the website. 

In fact, I cannot see the webstie anymore. It tells me Secure Connection failed. I really need help as I'm completely stuck. Any guidance on how to properly install this would be greatly appreciated! I have followed all steps but no results...I'm sure I'm missing something.

**Comment by thimios** [comment]
you need to put the name in quotes and add a username in the end, try something like:

```
 aleph createuser --email="user@example.com" --name="Alice" --is_admin --password=123abc alice
```

**Comment by pudo** [comment]
@OSINT007 if you're stuck, come ask for advice in the Aleph slack: https://docs.alephdata.org/get-in-touch - we use this issue tracker to work on errors in the software & extensions.
