### ISSUE TITLE
VIS Integration

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#886]
The primary goal for the first iteration of the integration of VIS into Aleph is to provide the basic infrastructure to support users' ability to create/edit/delete VIS diagrams within the context of a personal collection.  The diagrams will reference entities stored in the db, and any edits to the diagram should persist these changes to the entities themselves.

#### This iteration will explicitly not cover
* Editing of VIS diagrams for non-personal collections
* Canonical entity related features (integration of entities from across Aleph, merging, etc.)

#### Access Control
By storing the diagram as a 'Diagram' entity member of an existing collection, read/write access will be inherited from the collection permissions, so we shouldn't have to implement any additional permissions management.

### API
* Creation of 'Diagram' model to store JSON representation of VIS diagrams
* CRUD API endpoints for Diagrams
* JSON Schema to validate Diagram objects
* Diagram creation will involve:
  - Creating entities in the database; will reuse the `create_entity` function
  - Replacing entity ids with the signed version.
  - Storing only references to the created entities in the JSON blob
* Serializing Diagrams will involve:
  - De-referencing entity ids to include them inline in the JSON data being returned

#### Screens

* __*Collection Views > Diagrams Index Screen*__
  * create/edit/delete of diagrams for the collection
* __*Personal Settings Area > My Diagrams Index Screen*__
  * create/edit/delete of diagrams for the given user
  * (all diagrams must be tied to an existing collection)
* __*Diagram Edit Screen*__
  * full screen VIS window below the Navbar
  * visibility of toolbars/editing components controlled by user's write permssions
  * existing collection entities passed to vislib as datasource
  * delete button, .vis download button

#### Aleph <-> Vislib Message Passing
Vislib modifications required: See [alephdata/vislib - #120](https://github.com/alephdata/vislib/issues/120) 

##### Instantiation
Diagram view component in Aleph must pass the following parameters to instantiate a VisGraph component:
* `config`: GraphConfig object (can be default config params for now)
* `layout`: GraphLayout object reference
* `viewport`: Viewport object reference (could mayyyybe be made optional/ created internally within vislib)
* `updateLayout`: function called whenever layout is updated
* `exportSvg`: function to handle writing svg to file 
* `isEditable`: boolean (to be implemented)
* `datasource`: Datasource object (to be implemented)

##### Update frequency
* should follow Google Docs style delayed (5s ?) autosave
* whenever updateLayout function is called, sends delayed update API request

**Comment by pudo** [comment]
One nitpick -- we've referred to `isEditable` as `writeable` in other parts of the code base. Would propose we remain consistent on that.

**Comment by pudo** [comment]
I reckon we want two filters on `/api/2/diagrams`: one for filtering by role_id, the other by collection_id. I'm not super sure if the filter by role_id should return all diagrams a user can access, or the ones they have created....

**Comment by pudo** [comment]
It's aaaalive!
