### ISSUE TITLE
File issue setting up 

### ISSUE THREAD

**Issue by bryanrscott** [alephdata/aleph#909]
Hi while running "make all" command I get

` ---> Running in 61f044690332
Collecting xx_ent_wiki_sm==2.2.0
  Downloading https://github.com/explosion/spacy-models/releases/download/xx_ent_wiki_sm-2.2.0/xx_ent_wiki_sm-2.2.0.tar.gz (3.7MB)
ERROR: Exception:
Traceback (most recent call last):`

If I try and directly download the link in chrome I get a forbidden error.
I have tried a few times.

Just wondering if it could be checked.  
cheers

**Comment by pudo** [comment]
I can't seem to reproduce this: the file downloads just fine from my laptop and the GitHub CI. Is it possible you're doing this from some corporate setting that firewalls spaCy?

**Comment by bryanrscott** [comment]
Yep, I am behind a corporate firewall, but that is not the issue.
Checking this morning I can download.   Thanks for looking into.
The country is swapping from sat to fibre this week, maybe that was the cause of the issue.
