### ISSUE TITLE
Install Question

### ISSUE THREAD

**Issue by jigsawsecurity** [alephdata/aleph#923]
Is there an easy way to put a certificate in the system and configure it. Currently I have it running http but would like to implement https with a legitimate certificate but do not see that documented anywhere. I may just be missing something.

**Comment by pudo** [comment]
We usually don't bind the Aleph application to a public interface. Instead, we proxy through an external nginx that does TLS and handling of virtual hosts. If you wanted to bind Aleph in production mode, you'd probably want to build a Docker image derived from `alephdata/aleph-ui-production` (see directory `ui/`) that includes your own nginx configuration and TLS certificates.
