### ISSUE TITLE
health check / crash dump to help analyze problems

### ISSUE THREAD

**Issue by felixebert** [alephdata/aleph#927]
As an admin user of aleph I started multiple ingestions where an internal aleph problem occured.

It would be helpful to have a function which collects logs of all services, their current status, general stats and recent exceptions which we then can analyze ourselfs and / or forward it to aleph developers. 

Additional idea: A "health check" function which just validates all mappings and analyzers in elasticsearch and all schemas in the database. This would e.g. help in case of errors during `aleph upgrade` to check if everything is alright

**Comment by pudo** [comment]
I think the actionable bits from this ticket are pretty well covered in #926 and #956. As for the larger need to centralise logging for all Aleph containers, there's existing software that I'd prefer to use over building something fresh. Relevant references would include: 

* Prometheus
* Fluentd

This seems more sustainable than rolling our own.
