### ISSUE TITLE
`aleph upgrade` doesn't create Elasticsearch mappings

### ISSUE THREAD

**Issue by critocrito** [alephdata/aleph#938]
I remember that I needed to run `aleph upgrade` to create the Elasticsearch index mappings for a new installation. Now when I run it I only see this output:

```
(aleph) crito@aleph:~/aleph$ aleph upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

Querying the Elasticsearch indices using curl gives me an empty list of indices. When I try to `crawldir` a file I receive this error:

```
(aleph) crito@aleph:~/aleph$ alephclient --api-key XXX --host http://localhost crawldir -f test test.pdf
Error: no such index [aleph-collection-v1]
```

How can I create the Elasticsearch mappings? Did the `aleph upgrade` command change?

**Comment by pudo** [comment]
`aleph upgrade` should have created them, you're entirely right -- it should be really verbose, too, not just the two lines you gave. Can you confirm your database has 12 tables, and two entries in the `role` table for `visitor` and `logged_in`? That way we'd know this bit ran completely.

**Comment by critocrito** [comment]
Hey, thanks for your quick response. 

Yes, I do have those 12 tables and the user roles:

```
aleph=# select * from role;
 id |         created_at         |         updated_at         | deleted_at | foreign_id |      name       | email |             api_key              | is_admin | is_muted |  type  | password_digest | reset_token |        notified_at         | locale
----+----------------------------+----------------------------+------------+------------+-----------------+-------+----------------------------------+----------+----------+--------+-----------------+-------------+----------------------------+--------
  1 | 2020-01-13 15:08:57.413655 | 2020-01-13 15:08:57.413662 |            | guest      | All visitors    |       | f95bde1441584f29809e39b50000cd46 | f        | f        | system |                 |             | 2020-01-13 15:08:57.412488 |
  2 | 2020-01-13 15:08:57.417218 | 2020-01-13 15:08:57.417223 |            | user       | Logged-in users |       | 37f10904235d46cb9e7bff4641139f20 | f        | f        | system |                 |             | 2020-01-13 15:08:57.416792 |
(2 rows)
```

Probably relevant to know is that I'm not using the docker containers. I made this [installation tutorial](https://gist.github.com/critocrito/c5afe9c82ba03ecb1cb76b2d50deb75f) that de-dockerifies Aleph (it's still work in progress). I believe I do something wrong the way I initialize the databases. You can see my steps [related to database initialization](https://gist.github.com/critocrito/c5afe9c82ba03ecb1cb76b2d50deb75f#initialize-database) at the bottom of the guide. Without the `aleph db init/migrate` calls I get an error for `aleph upgrade`. But again the Elasticsearch index is not created. I get the same output as reported above.

**Comment by critocrito** [comment]
I could solve it with a little `strace` goodness. 

```
recvfrom(4, "HTTP/1.1 400 Bad Request\r\ncontent-type: application/json; charset=UTF-8\r\ncontent-length: 383\r\n\r\n{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"IOException while reading synonyms_path_path: /etc/elast
icsearch/synonames.txt\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"IOException while reading synonyms_path_path: /etc/elasticsearch/synonames.txt\",\"caused_by\":{\"type\":\"no_such_file_exception\",\"reason\":\"/etc/elasticsearch/synonames.t
xt\"}},\"status\":400}", 8192, 0, NULL, NULL) = 479
```

Clearly the `synonames.txt` was missing and that prevented the indices being created. I followed the instructions of the [Elasticsearch services Dockerfile](https://github.com/alephdata/aleph/blob/master/services/elasticsearch/Dockerfile#L9) that is part of the Aleph repository. So it seems those instructions are either outdated or there is a configuration mismatch between the Elasticsearch Docker container and a stock Ubuntu installation.

Either way, the real issue was a lack of feedback of ~aleph upgrade~. You mentioned that this command should produce quite some output when run successfully. It didn't in my case. This is the full output of the command even though the Elasticsearch indices were created.

```
$ ALEPH_DATABASE_URI=postgresql://aleph:aleph@localhost:5432/aleph ARCHIVE_TYPE=file ARCHIVE_PATH=/home/aleph/data ALEPH_ELASTICSEARCH_URI=http://localhost:9200 aleph upgrade
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
$
```

**Comment by pudo** [comment]
Thanks for the feedback, I've added some appropriate (I hope) error and warning messages, and increased operation timeouts for all operations.
