### ISSUE TITLE
Single-user mode

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#951]
When running locally, or in development, there should be an environment variable that instructs the API to log any visitor in as admin automatically with each request, thus making the notion of access control disappear for all practical purposes. 

There would still be access control dialogs in the UI, but they wouldn't really serve much of a function. I propose we just use the system admin user, `aleph`.

**Comment by zrthstr** [comment]
https://github.com/alephdata/aleph/pull/1126/

**Comment by pudo** [comment]
Implemented in develop.
