### ISSUE TITLE
Delayed data exports

### ISSUE THREAD

**Issue by pudo** [alephdata/aleph#959]
Exporting bulk files, such as Xref Excels, search result bundles etc. takes an unrealistically long time at the moment. Instead, we should generate those files offline and send an email to the user once the process has completed, including a download link.

**Comment by sunu** [comment]
We decided that:
1. We will generate these exports in the background and upload them to cloud storage
2. We'll store export related data - cloud storage hash, user, export type, export time, file size, deleted or not etc in a database table
3.  If the file is unreasonably big (more that 10GB), we'll abort after export and send an email explaining that to the user
4. If the export process is successful, we'll send an email to the user with a link to download the file.
5. The download link will be behind auth
6. The file is auto-deleted from cloud storage after a while (30 days)

**Comment by pudo** [comment]
Ups, fixed in 3.9.0, closing :)
