### ISSUE TITLE
Table editor for personal datasets

### ISSUE THREAD

**Issue by kjacks** [alephdata/aleph#992]
Adapt current table editor (in vislib) to exist as a top-level view mode in personal datasets

Questions:
- Should the table editor support multi-text inputs?  If so, how can this be done in a way that still allows for an easier editing experience than the current setup?
- Should multi-cell pasting be supported?
- How to handle type validation for dates/countries/etc.

**Comment by pudo** [comment]
Random wishlist:

* Make sure that all entries can be completed by keyboard, including country/language/topic selection, date selection etc. 
* Make sure that pressing enter or tab will activate the next column, or jump to the next row (create if needed). Arrow navigation. 
* Somewhere near the table there should be a "import a spreadsheet" button that explains the mapping workflow and/or just opens a file upload dialog.

**Comment by pudo** [comment]
Merged in #1130
